### ISSUE TITLE
Please be clear about what licenses are needed

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/CloudAppSecurityDocs#102]
I do understand that Microsoft creates features that will entice the customer to buy more features. That is OK, as long as it is clear on every path what version/license is needed to be able to do what is recommended in an article such as this one. 

So please be crystal clear as to what E level of Office 365 is needed for this to be available. 
Thank you
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f1881c-1d0b-7a96-f8c1-3989b3b5e0cd
* Version Independent ID: b50ed5b9-18ab-abde-406e-b3fd1ff61fa2
* Content: [What is Cloud App Security?](https://docs.microsoft.com/en-us/cloud-app-security/what-is-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/what-is-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/what-is-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by dvanderslice** [comment]
Completely agree the gap between EMS e3 and e5 is a grey area when reading this stuff. There should be a license prereqs section on every one of these articles

**Comment by rkarlin** [comment]
Hi @blouwagie and @dvanderslice thanks for the feedback - it's a known issue for me that this needs to be clarified - we have been working on a data sheet that should provide some clarity around versions and packages and licenses soon.
thanks!

**Comment by rkarlin** [comment]
#please-close

**Comment by BharathiAN** [comment]
@rkarlin Any clarification on the license required. Whether all the users should have E5 license or only admins in tenant with E5 license is enough for using cloud app security.
