### ISSUE TITLE
Feature Availability 

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/CloudAppSecurityDocs#103]
Is there some documentation on what is available with such integration with ServiceNow? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148367a2-1d5d-a348-e34a-ee5c9e8157dd
* Version Independent ID: 3dee7652-6b47-4523-a530-9b69257950fc
* Content: [Connect ServiceNow to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-servicenow-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-servicenow-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-servicenow-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @Mark7even , thanks for reaching out . You can look at the table on the page https://docs.microsoft.com/cloud-app-security/enable-instant-visibility-protection-and-governance-actions-for-your-apps 
The table there lists everything available for each connected app.

**Comment by rkarlin** [comment]
#please-close @msmbaldwin
