### ISSUE TITLE
Unable to download PDF

### ISSUE THREAD

**Issue by et3rae** [MicrosoftDocs/CloudAppSecurityDocs#104]
I'm trying to download this doc as a PDF using the handy "download PDF" link, but it just errors and will not open as a PDF.  Any downloads are 0 bytes in size. Any suggestions or assistance would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47cc4f8f-f7d2-07ce-4fb2-4e87eef26655
* Version Independent ID: 33d5a394-9e8b-2db5-6a8b-ec6219463b30
* Content: [Setup your organization's settings in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/general-setup)
* Content Source: [CloudAppSecurityDocs/general-setup.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/general-setup.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @et3rae thanks for letting us know. I'm looking into it and will get back to you.

**Comment by rkarlin** [comment]
Hi @et3rae We fixed this - it should work now.
thanks!
