### ISSUE TITLE
Not clear how to find the step

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/CloudAppSecurityDocs#105]
For the step below you failed to explain how to get there. We believe you have to Go under Information Protection &gt; Files &gt; Enable File Monitoring , and then you still need to explain how you get from there to the screenshot you show. 

The text below is copied from the relevant section in this document, for your reference:
Apply labels directly to files
From the Files page under Investigate, select the file you want to protect. Click the three dots at the end of the file's row then choose Apply classification label.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Azure Information Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/azip-integration#how-to-integrate-azure-information-protection-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/azip-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @blouwagie , Thanks so much for reaching out. I believe that you are experiencing this because you don't have file monitoring enabled in Cloud App Security. This article assumes that you have file monitoring enabled. I'll add a note to make sure that's clear. thanks for pointing it out. Rachel

**Comment by rkarlin** [comment]
#please-close @msmbaldwin

**Comment by blouwagie** [comment]
Hi @rkarlin 
File Monitoring is and was enabled on our portal . I find it under portal.cloudappsecurity.com > Settings > Files > Enable file monitoring. 

I now realize what is the issue. In the lines above you are in the settings section.  Can you please add that one has to go out of settings. Then to go Hamburger > Investigate > Files .  

The reason that this is confusing because the word "Files" is still on the screen from the step before (under settings).

I realize that once one knows where it is it is simple, but both me and Microsoft CAS support engineer could not find it.

Bart

**Comment by rkarlin** [comment]
Hi @blouwagie I'll update the document tor reflect your changes. 
I see you've got a lot of feedback on our docs lately! We are happy to connect with our most engaged customers. If you're interested in contributing more to our documentation, we'd be happy to get your feedback in a more consolidated way and maybe set up a time to chat about your overall experiences with our documentation. Please let me know if that's something that you'd be interested in. Thanks!

**Comment by blouwagie** [comment]
Hi,
 Yes is be interested in that direct connection for sure.  Anytime really..
Thank you
Bart
