### ISSUE TITLE
p12 certificate password

### ISSUE THREAD

**Issue by sniedzwi** [MicrosoftDocs/CloudAppSecurityDocs#108]
The document suggest that we will be prompted for the p12 certificate password at upload, but that does not appear to be the case.  Is there a step missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f41e1e-2541-8773-efc2-eeb83a403a15
* Version Independent ID: 2f2d0316-9e75-44d6-0ab6-a56b1352a1e2
* Content: [Connect G Suite to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-google-apps-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-google-apps-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-google-apps-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@sniedzwi  Thanks for reaching out. The Google connection experience changes so rapidly that it's hard for us to keep up to date on what needs to be configured on their end. If you didn't succeed in doing this, please open a support ticket and they will investigate the process and let me know what needs to be done to update the article to reflect changes in the Google experience. Thanks, Rachel

**Comment by rkarlin** [comment]
#please-close @msmbaldwin
