### ISSUE TITLE
Please clarify where to find the "check the Content inspection option"

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/CloudAppSecurityDocs#109]
Microsoft support and I spent hour trying to find the "check the Content inspection option". We have now found it and hope you can update this document to explain this. 

Under the section "Automatically label files" you have a Note that reads:
Automatic scan does not scan existing files until they are modified again. To scan existing files for Azure Information Protection classification labels, you must have at least one Content inspection File policy. If you have none, create a new File policy, delete all the preset filters, check the Content inspection option. Then, under Content inspection, click Include files that match a preset expression and select any predefined value, and save the policy. This enables content inspection, which automatically detects Azure Information Protection classification labels.
 
As we could not find that option, here is revised wording proposal:

Automatic scan does not scan existing files until they are modified again. To scan existing files for Azure Information Protection classification labels, you must have at least one Content inspection File policy. If you have none, create a new File policy, delete all the preset filters, *Choose Inspection Method: Built in DLP: Then set Content Inspection Enabled. Then, under Content inspection, click Include files that match a preset expression and select any predefined value, and save the policy. This enables content inspection, which automatically detects Azure Information Protection classification labels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Azure Information Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/azip-integration#how-to-integrate-azure-information-protection-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/azip-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@blouwagie , Thanks so much for reaching out. You're right, they changed the page. I'll update the documentation to reflect the new language and options. thanks!

**Comment by rkarlin** [comment]
#please-close @msmbaldwin

**Comment by blouwagie** [comment]
Hi @rkarlin  
Thank you for responding. In the meantime I worked with Microsoft Escalation on this.

After talking with an escalation engineer who had said that that to test ALL files we could use for "inspection method" > Built-in DLP >  Check "Include all files that match a preset expression". Doing that resulted in zero (0) files being found.

So I then resorted to using the following workaround to apply inspection to all files: "inspection method" > Built-in DLP > chekc "include files that match a custom expression" and in the search box type [a-z0-9]{1,9} and chose the option "Match a regular expression" . This option worked. 

As long as the system does not provide an option to check all files in a location, it would be really helpful to have the workaround I found documented. I believe that the option to scan ALL files in a location is essential for compliance for many of the AIP users.

Regards
Bart

**Comment by rkarlin** [comment]
Hi @blouwagie , If we understand correctly, you seem to be trying to select which files the policy runs on in the content inspection field. That field only sets what type of inspection to use. To set which files the policy runs on, as it says in the document, delete all the preset filters in the filter scope - did you want me to write "delete all the preset filters under Files matching all the following" is that the part that you found confusing?

**Comment by blouwagie** [comment]
Hi rkarlin, that is an interesting solution that neither Microsoft Support (two engineers, including escalation engineer) managed to conclude from the document. This is not about the filtering.  I read the note again and copy the part that does not work as described. This is the section: "Then, under Content inspection, click Include files that match a preset expression and select any predefined value, and save the policy. This enables content inspection, which automatically detects Azure Information Protection classification labels."
The "select any predefined value" is not something that works, or we (including support) have no idea how to do that. In the end it is in the content inspection area that we had to chose: Regular Expression and then build a regular expression to have one that would match any piece of text or number. 
So no it is not about removing all the filters higher up on that page, it is about the need to do content inspection and making that content inspection match all files, aka any content.
Hopefully that helps
bart
