### ISSUE TITLE
Explain how to create a regular expression, especially one to mathc ALL files.

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/CloudAppSecurityDocs#110]
As there is a feature to scan existing files, we want to scan ALL files (in the selected location) In the note you say that we have to use content inspection to scan existing files. When we chose that option we are asked to define an "expression" for matching the file.  Since I want to match all files and there is no "all files" option I guess that the star (*) could be the regular expression, but you do not explain the regular expression syntax. Maybe it is a standard regular expression syntax. If so please link to a document that explains this syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Azure Information Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/azip-integration#how-to-integrate-azure-information-protection-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/azip-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by blouwagie** [comment]
I did find there is indeed a link to the syntax. Sorry for that oversight. Yet it seems to be really hard to know how to do ALL files since * seems not allowed.

**Comment by rkarlin** [comment]
@blouwagie Thanks for reaching out. I'm sorry this was complicated, and hope the link helped!
Rachel

**Comment by rkarlin** [comment]
#please-close
@msmbaldwin
