### ISSUE TITLE
Multi-instance Support

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/CloudAppSecurityDocs#111]
Does the MCAS have the ability to connect multiple Azure Tenants/Instances? The documentation is really lacking in this area. If it is possible how does one accomplish the multiple Azure Tenant Connections?

**Comment by rkarlin** [comment]
Hi @Mark7even , sorry, Multi instance support isn't supported by Azure. For more information, see https://docs.microsoft.com/cloud-app-security/enable-instant-visibility-protection-and-governance-actions-for-your-apps.
thanks

**Comment by rkarlin** [comment]
#please-close
