### ISSUE TITLE
What does revoking the app actually do?

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/CloudAppSecurityDocs#112]
All I can tell is it disables sign-in to the application in Azure AD Enterprise Applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3543307c-9c07-720c-e4fe-3aa6cb43f680
* Version Independent ID: df363f37-c41a-7493-6573-c7a8f4ff1aaf
* Content: [Control which third-party cloud OAuth apps get permissions - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/manage-app-permissions#feedback)
* Content Source: [CloudAppSecurityDocs/manage-app-permissions.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-app-permissions.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@Mark7even Hi, Yes, that's what it does. It removes the permissions. Thanks for reaching out and let me know if you have any other issues.

**Comment by Mark7even** [comment]
@rkarlin It also appears to turn off the ability to sign-in to the application in Azure AD? Can you confirm?

**Comment by rkarlin** [comment]
@Mark7even Hi Mark, I'm checking into that for you.

**Comment by rkarlin** [comment]
It removes all permissions that were granted to the application under “Enterprise Applications” in AzureAD. I'll make sure that's clear in the article. thanks for calling my attention to this.

**Comment by rkarlin** [comment]
#please-close

**Comment by Mark7even** [comment]
So in testing, it does turn off the "Enabled for users to sign-in?" in Azure AD Enterprise Applications. Is this a bug? or is this intended behavior?

**Comment by rkarlin** [comment]
yes, it should - allowing users to sign in is one of the permissions and revoke app removes all permissions so this is working as expected. thanks.
