### ISSUE TITLE
Importing of groups showing 0 members.

### ISSUE THREAD

**Issue by gimmic** [MicrosoftDocs/CloudAppSecurityDocs#113]
Using a distribution group shows up in autocomplete for manual import, acts like it is trying to import, but ends up with 0 members.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb8d5c18-3f84-f47a-7320-930cbd4ae5a0
* Version Independent ID: aa593032-c7c0-5814-5b18-d360295a260e
* Content: [Import user groups from connected apps in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/user-groups#feedback)
* Content Source: [CloudAppSecurityDocs/user-groups.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/user-groups.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@gimmic Thanks for reaching out to us. It can take up to 2 hours for results to show up. Please let me know if you're still having problems. thanks

**Comment by gimmic** [comment]
I can verify the members are now showing up as expected. The UI should not reflect "import completed successfully" and display 0 members. It should reflect the import is not yet finished.
