### ISSUE TITLE
Update MCASInstallDocker.sh

### ISSUE THREAD

**Issue by sdiver78** [MicrosoftDocs/CloudAppSecurityDocs#114]
Need to update https://adaprodconsole.blob.core.windows.net/public-files/MCASInstallDocker.sh for OS to allow Cent OS 7.2 and above which now works fine with Docker-CE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e21ac1e4-295d-74f4-8217-087203c54bb7
* Version Independent ID: 229ddf62-fd89-8e05-a55a-6a894a57c13a
* Content: [Configure automatic log upload using on-premise Docker](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu#feedback)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @sdiver78 , thanks for taking the time to let us know. we'll take care of it.

**Comment by rkarlin** [comment]
#sign-off
