### ISSUE TITLE
Screenshots need updating

### ISSUE THREAD

**Issue by shawnharry** [MicrosoftDocs/CloudAppSecurityDocs#115]
The menu's have changed in AWS and the above is out of date and needs updating as there's more steps required to enable MCAS/AWS integration than shown above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf4839c-f4e3-5808-c608-f2795f7b640d
* Version Independent ID: 3ccbc129-d930-eb79-a034-365b89f88a13
* Content: [Connect AWS with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-aws-to-microsoft-cloud-app-security#feedback)
* Content Source: [CloudAppSecurityDocs/connect-aws-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-aws-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @shawnharry Thanks for letting us know. They update their screens regularly and we try to keep up but the document is for illustration purposes and can't always be up to date with third-party updates.
thanks

**Comment by rkarlin** [comment]
#please-close
