### ISSUE TITLE
3 dots

### ISSUE THREAD

**Issue by jegilber** [MicrosoftDocs/CloudAppSecurityDocs#123]
I do not see the 3 dots in my tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba61c236-e64a-2835-8fbd-4ff975e78d27
* Version Independent ID: d4394353-4330-05a2-c30b-b2b4bd7b7c2f
* Content: [Generate reports - Microsoft Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/built-in-reports#feedback)
* Content Source: [CloudAppSecurityDocs/built-in-reports.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/built-in-reports.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@jegilber Thanks for reaching out. The ellipses to view the reports should be available unless you're working in a demo tenant. I suggest opening a support ticket. thanks.

**Comment by rkarlin** [comment]
#please-close
