### ISSUE TITLE
vm no longer available

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/CloudAppSecurityDocs#124]
I understand that Docker is the preferred method, however this article says that the virtual appliance is also an option. When you click the link for instructions, the title says "Deprecated", but worse, is that in the MCAS console, we can't actually download the VMs anymore. So, unless something is wrong in the console, you might as well remove all mention of the VM method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e0555c-41e5-0ba3-4c4b-f9c386644a72
* Version Independent ID: 876888bc-8046-0a25-a0b7-67f938cc45c1
* Content: [Configure automatic log upload for continuous reports in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker)
* Content Source: [CloudAppSecurityDocs/discovery-docker.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @Mike-Crowley Thanks for reaching out. We have a few customers who still use this method, so we can't remove the article entirely, but I'll look for ways to mitigate it. Thanks.

**Comment by rkarlin** [comment]
#please-close
