### ISSUE TITLE
Step1 - Enable Policy?

### ISSUE THREAD

**Issue by yoyogin** [MicrosoftDocs/CloudAppSecurityDocs#126]
Hi, It seems that I had to 'Enable Policy' in step 1 to get the whole thing working - can you confirm and if so, update the document (add another step).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f895939-5862-2cfa-3c3d-0afdb95fbba4
* Version Independent ID: b44fdfcf-c0f7-e3f0-103f-2e4dd33a7c9d
* Content: [Deploy Cloud App Security Conditional Access App Control for Azure AD apps](https://docs.microsoft.com/en-us/cloud-app-security/proxy-deployment-aad)
* Content Source: [CloudAppSecurityDocs/proxy-deployment-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/proxy-deployment-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @yoyogin, I actually thought that was intuitive and didn't need documentation, but if you felt it was confusing I'll add it. thanks.
#please-close
