### ISSUE TITLE
Supported data source list gone

### ISSUE THREAD

**Issue by davmhelm** [MicrosoftDocs/CloudAppSecurityDocs#127]
After doc checkin from January 27th 2019, the list of supported data sources was removed from this doc. Diff visible here: https://github.com/MicrosoftDocs/CloudAppSecurityDocs/commit/350ed211a6ddb95bc1cfba79a9e92a97d960044d?short_path=1831463#diff-1831463c3bedf6f41f9204300fda2ef2

Was this removed by mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a419aaf2-b6b9-902a-e186-c5718b9ffd1f
* Version Independent ID: 2a9c599e-306e-490e-2e6d-7642fa71d63c
* Content: [Create snapshot reports of Cloud Discovery cloud app use](https://docs.microsoft.com/en-us/cloud-app-security/create-snapshot-cloud-discovery-reports#feedback)
* Content Source: [CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
I moved it here, because it seemed relevant to more than just the snapshot report article: https://docs.microsoft.com/cloud-app-security/set-up-cloud-discovery

**Comment by davmhelm** [comment]
Thanks for the quick response! Apologies, had I read farther in the diff on the commit I would have seen where you included it. If I could make a suggestion, presently the wording starting at [line 99](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/blame/master/CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md#L99) is:

> 1. Data source is supported (see list below).

But no list is provided. If the content were modified to something like:

> 1. Data source is supported ([see list located here](https://docs.microsoft.com/en-us/cloud-app-security/set-up-cloud-discovery#supported-firewalls-and-proxies-))

I think it could prevent others from being similarly confused.

**Comment by rkarlin** [comment]
Great suggestion. I'm on it! thanks for reaching out and for your helpful contribution!

**Comment by rkarlin** [comment]
It should be updated in a few minutes.

**Comment by rkarlin** [comment]
#please-close
