### ISSUE TITLE
Editor roles does not show up.

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/CloudAppSecurityDocs#128]
It seems the roles have been renamed (or the editor role is not a default role)

Not sure what is the equivalent role of the previous one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f41e1e-2541-8773-efc2-eeb83a403a15
* Version Independent ID: 2f2d0316-9e75-44d6-0ab6-a56b1352a1e2
* Content: [Connect G Suite to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-google-apps-to-microsoft-cloud-app-security#feedback)
* Content Source: [CloudAppSecurityDocs/connect-google-apps-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-google-apps-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by annerajb** [comment]
NVM eventually found it under project.

**Comment by ShlomoSagir-MS** [comment]
closes #128
