### ISSUE TITLE
Can you also document how to configure that action that should happen in case of an Alert

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/CloudAppSecurityDocs#129]
Managing alerts should also include "What has to happen (action) in case of a given alert?" ... Like: Send me an email when this alert  (or an alert like this one) happens. I'd expect to be able to find how to set that action up. But the document does not explain this. Could you please add this or add a link to where that is documented?

Thank you
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70912b42-016b-d311-86cd-86f2e5e04a51
* Version Independent ID: 1744f30c-af16-cf4a-6a91-043e6f92b330
* Content: [Manage alerts raised in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/managing-alerts)
* Content Source: [CloudAppSecurityDocs/managing-alerts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/managing-alerts.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@blouwagie  Thanks for your suggestion. This article focuses on how to work with alerts raised. However, I have taken your remarks into consideration and added a note to the article.
