### ISSUE TITLE
Licensing statement mismatch

### ISSUE THREAD

**Issue by paulhefford** [MicrosoftDocs/CloudAppSecurityDocs#132]
In the second paragraph: "Your organization must have a license to use Cloud App Security.". In the following note: "You don't need an Office 365 license to use Cloud App Security.". Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security#feedback)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by brucelaing** [comment]
As you can buy Cloud App Security as a stand alone licence you do not need an Office 365 licence to use it.

**Comment by ShlomoSagir-MS** [comment]
@paulhefford Thanks for your question and thank you @brucelaing for answering. Since @brucelaing has already responded to your question, I am closing this issue. But thanks again for your inquiry; we always appreciate feedback on our documentation.

**Comment by emilylait** [comment]
Hi regarding this issue, i agree here, while the statements are separate things, and you can buy it standalone, this statement is not clear to users who do not understand our many licensing differences. Even i had to read this twice. I think the note should be further clarified that it can be bought as a standalone. At first glance this looks like it implies no license is required to use MCAS. Thank you.
