### ISSUE TITLE
Content inspection - Protected files

### ISSUE THREAD

**Issue by mohanse** [MicrosoftDocs/CloudAppSecurityDocs#134]
Please clarify  - "Files that were labeled with protection outside of Cloud App Security can't currently be scanned or changed by Cloud App Security." - 

As per the "Inspect protected files" option, protected files (protected from Office clients and uploaded to SharePoint/OneDrive etc) can be inspected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Azure Information Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/azip-integration#feedback)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/azip-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@mohanse Thanks for your feedback; we appreciate it. After investigating, we've discovered that the topic was recently modified and this issue was clarified among other changes; hence, we are closing this issue and thank you again for helping to improve our documentation.
