### ISSUE TITLE
Feature Comparison chart

### ISSUE THREAD

**Issue by bryhall** [MicrosoftDocs/CloudAppSecurityDocs#136]
This table does not include any Information Protection or Threat Detection items, which are present in the Microsoft CAS vs O365 CAS table.  Clarification on whether any of those items are or are not included with Azure AD CAS would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401b0903-938e-9739-49eb-4c28ef10bcfc
* Version Independent ID: 89fc55de-a5eb-c398-4a53-5786f49349f2
* Content: [Discovery capability differences for Cloud App Security and Azure AD](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-aad#feedback)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@bryhall Thanks for your feedback. After investigating, we've discovered that Azure Active Directory Cloud App Discovery is a discovery only product and hence the table compares between the discovery features of both products. However, we've decided to show the comparison of the additional Cloud App Security features as well. We are deeply appreciative for your commitment to help us provide better documentation.
