### ISSUE TITLE
"Global Reader" title

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/CloudAppSecurityDocs#137]
Global reader is defined as - Has full read-only access to all aspects of Microsoft Cloud App Security. Cannot change any settings or take any actions.
This ONLY pertains to cloud app security, and it misleading to the customer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@Strick1969 Thanks for your feedback. We appreciate it. After investigating, we've discovered that you are correct. Therefore, we have revised the topic to make it clearer. Thanks again for helping to improve our documentation.
