### ISSUE TITLE
Click View new apps - ribbon missing

### ISSUE THREAD

**Issue by jaiadityasingla** [MicrosoftDocs/CloudAppSecurityDocs#139]
Click View new apps - ribbon missing
after Step 3: Configure advanced controls and non-featured apps in the Cloud App Security portal

https://docs.microsoft.com/en-us/cloud-app-security/proxy-deployment-aad

**Comment by shsagir** [comment]
@jaiadityasingla Thanks for your feedback. After investigating the issue, the article has been rewritten to  reflect the current experience using proxy deployment. Thanks again for reporting the issue and helping to improve our documentation.
