### ISSUE TITLE
Change Documentation for applying Azure Information Protection classification to PDF

### ISSUE THREAD

**Issue by AWeber78** [MicrosoftDocs/CloudAppSecurityDocs#141]
applying Azure Information Protection classification to PDF is available
https://docs.microsoft.com/en-us/cloud-app-security/release-notes

in
https://docs.microsoft.com/en-us/cloud-app-security/azip-integration
it is still a future state

**Comment by ShlomoSagir-MS** [comment]
@AWeber78 Thanks for your feedback. After investing the issue, the second article you mentioned has been updated accordingly. We appreciate you taking the time to improve the documentation.
