### ISSUE TITLE
Upper case missing

### ISSUE THREAD

**Issue by adzamri** [MicrosoftDocs/CloudAppSecurityDocs#143]
Under The Activity Drawer,
"view activities from the same geographic location" should have a capital V as the rest in the list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f02dc24-a495-59e0-1f78-89b6a0b275e2
* Version Independent ID: 3089ccac-a074-7a99-7078-e28c9432050a
* Content: [Visibility into cloud app activities - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/activity-filters)
* Content Source: [CloudAppSecurityDocs/activity-filters.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/activity-filters.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@adzamri Thanks for your feedback. It's really appreciated. The content has been updated accordingly.
