### ISSUE TITLE
what actions can be taken on each of the 28 featured apps?

### ISSUE THREAD

**Issue by dennisxu2019** [MicrosoftDocs/CloudAppSecurityDocs#145]
hello, assume the actions one can define for each of the 28 featured apps are different depending on what API those SaaS apps make available for MCAS, is there a list of actions one can define for each of the 28 featured apps? 
thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect with Microsoft Cloud App Security Conditional Access App Control](https://docs.microsoft.com/en-us/cloud-app-security/proxy-intro-aad)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @ShlomoSagir-MS
* Microsoft Alias: **ShlomoSagir-MS**

**Comment by ShlomoSagir-MS** [comment]
@dennisxu2019 Thanks for you question.
To clarify, Conditional Access App Control uses a reverse proxy architecture. The specific actions for each app can be viewed in the "Block custom activities" session policy.
If you require any further assistance, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
