### ISSUE TITLE
How to buy

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#148]
The link above to buy O365 CAS points to page that does not explain how to do this. Please correct the link to point to the correct information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by brucelaing** [comment]
It would be better if it took you to the trial signup - https://aka.ms/mcastrial

**Comment by ShlomoSagir-MS** [comment]
@DeanGross Thanks for your feedback and apologies for the delay in responding. I am investigating the issue.

**Comment by ShlomoSagir-MS** [comment]
@DeanGross Thanks again for your feedback. After investigating, we've discovered that you are correct and we've updated the topic. We are deeply appreciative for your commitment to help us provide better documentation.
