### ISSUE TITLE
Role missing in azure 

### ISSUE THREAD

**Issue by anlucen** [MicrosoftDocs/CloudAppSecurityDocs#152]
Cloud Discovery global admin and Cloud Discovery report admin showed here is not showing on Azure as role. There were any update about the documentation ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* GitHub Login: @ShlomoSagir-MS
* Microsoft Alias: **ShlomoSagir-MS**

**Comment by ShlomoSagir-MS** [comment]
@anlucen Thanks for your feedback; we appreciate it. I have investigated the issue and you're observations are correct. I have initiated the update of this topic to provide clearer information. Again, thanks for reporting the issue.

**Comment by ShlomoSagir-MS** [comment]
@anlucen The topic has been updated to provide clearer information. Once again, thanks for reporting the issue.
