### ISSUE TITLE
Daily Label Limit

### ISSUE THREAD

**Issue by justinmeryment** [MicrosoftDocs/CloudAppSecurityDocs#153]
I'm trying to raise our tenant's daily label limit however when I email 'cascoresupport@microsoft.com' as instructed on this page, I get an immediate bounce back with the error 'The group CSSCASSupp only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Azure Information Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/azip-integration#feedback)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/azip-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @ShlomoSagir-MS
* Microsoft Alias: **shsagir**

**Comment by ShlomoSagir-MS** [comment]
@justinmeryment It looks like you're having an issue with the product itself, rather than an issue with the documentation. Please [submit your issue](https://go.microsoft.com/fwlink/?linkid=2099672) here.
