### ISSUE TITLE
Table missing info for Azure

### ISSUE THREAD

**Issue by eosho** [MicrosoftDocs/CloudAppSecurityDocs#155]
Table is missing information on the abilities of the Azure app connector. I know there are pieces of information from different sources, but this will help how what MCAS can do within Azure compared to AWS.

**Comment by ShlomoSagir-MS** [comment]
@eosho Thanks for your feedback. In order to investigate further, please provide the link to the topic with the table. Thank you.

**Comment by eosho** [comment]
@ShlomoSagir-MS here is the link - https://docs.microsoft.com/en-us/cloud-app-security/enable-instant-visibility-protection-and-governance-actions-for-your-apps#how-it-works

**Comment by ShlomoSagir-MS** [comment]
@eosho Thanks for the additional information. I'll investigate the issue.

**Comment by ShlomoSagir-MS** [comment]
@eosho Thanks again for the feedback. After investigating, I've discovered that you are correct and I've updated the topic. We are deeply appreciative for your commitment to help us provide better documentation.
