### ISSUE TITLE
External Group definition

### ISSUE THREAD

**Issue by AndrisPetris** [MicrosoftDocs/CloudAppSecurityDocs#160]
There is a difference in what the DOcs say and what's written in the app itself, as one say its IP ranges when the second says its domains listed in settings - which suppose to be the right one. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a8be0f-fc22-9fe2-ab62-6f4e24ebd343
* Version Independent ID: b7a7bb70-7fc8-08ef-20de-a48c8d845445
* Content: [Scope your Microsoft Cloud App Security deployment](https://docs.microsoft.com/en-us/cloud-app-security/scoped-deployment#feedback)
* Content Source: [CloudAppSecurityDocs/scoped-deployment.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/scoped-deployment.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ShlomoSagir-MS** [comment]
@AndrisPetris Thanks for your feedback. After investigating, we've discovered that you are correct and we've updated the topic. We are deeply appreciative for your commitment to help us provide better documentation.
