### ISSUE TITLE
minor adjustment to getting started through office admin

### ISSUE THREAD

**Issue by mdresch** [MicrosoftDocs/CloudAppSecurityDocs#161]
To Access the services minor adjustment in new admin poral - All Admin Centres - Security - More Resources - Cloud Security App

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security#feedback)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @ShlomoSagir-MS
* Microsoft Alias: **shsagir**

**Comment by ShlomoSagir-MS** [comment]
@mdresch Thanks for your feedback. I'm investigating the issue.

**Comment by ShlomoSagir-MS** [comment]
@mdresch After investigating I can see that the steps have changed. Therefore, I have updated the article accordingly. Thanks for helping to improve the quality of our docs. We really appreciate your feedback.
