### ISSUE TITLE
Cannot find logs from MCSA 

### ISSUE THREAD

**Issue by JakKAaj** [MicrosoftDocs/CloudAppSecurityDocs#162]
Hi, 
We have successful deploy jar file in our azure server. The status in connected and we can see debugging agent logs with no problem. However, I can not find alert logs from MCSA. Can you please let me know what directory this will be send to ?
Regards,
Michal

**Comment by ShlomoSagir-MS** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
