### ISSUE TITLE
Security Reader should read Security Administrator

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/CloudAppSecurityDocs#163]
In this phrase "To set up Cloud App Security, you must be a Global Administrator, a Compliance Administrator, or a Security Reader in Azure Active Directory or Office 365." it should read "or a Security Administrator"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security#feedback)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @ShlomoSagir-MS
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@andrePKI Thanks for your feedback. After investigating the issue, I have updated the prereqs to reflect the correct roles. Thanks for helping to improve our documentation.
