### ISSUE TITLE
Expand on reverse proxy and log collection integration

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/CloudAppSecurityDocs#165]
The documentation appears to be void on reverse proxy deployment guidance and the mentions of log collection are pretty bare bones.

I'd be happy to write the documentation in exchange for a brief on these capabilities.

**Comment by shsagir** [comment]
@jebalert Thanks for your feedback and kind offer :-) . You can find information about reverse proxy deployment in the [Onboard and deploy Conditional Access App Control for any app](https://go.microsoft.com/fwlink/?linkid=2098707) topic. Regarding log collection, there are several topics under **How-to guide** > **Cloud Discover** > **Set up** describing how to collect logs from different devices. If there is something specific you are looking for, please provide the specific information and I'll investigate.

**Comment by shsagir** [comment]
@jebalert Closing until we get further info.
