### ISSUE TITLE
CAS to SIEM ingestion seems supported. What about SIEM to CAS?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/CloudAppSecurityDocs#166]
Does MCAS support ingesting SIEM events from a SIEM like Splunk? Right now the documentation states:

"The Microsoft Cloud App Security SIEM agent runs on your server and pulls alerts and activities from Microsoft Cloud App Security and streams them into the SIEM server."

What about steaming from SIEM server to CAS?

**Comment by shsagir** [comment]
@jebalert Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. To make sure it gets in front of the right people, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
