### ISSUE TITLE
Microsoft Cloud App Security licensing

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/CloudAppSecurityDocs#168]
Hello,
If we have an Global Tenant account, this account has access to some SharePoint sites and some shared mailboxes already for running backup job, would it be possible to give license only to this one user to setup Cloud App Security?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f1881c-1d0b-7a96-f8c1-3989b3b5e0cd
* Version Independent ID: b50ed5b9-18ab-abde-406e-b3fd1ff61fa2
* Content: [What is Cloud App Security?](https://docs.microsoft.com/en-us/cloud-app-security/what-is-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/what-is-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/what-is-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by lightupdifire** [comment]
Solution I'm looking is for mid-size customer, customer interested to setup Cloud App Security, but just with one account, that already have access to data and then use Cloud App Security only for general files activity overview and automatic labeling and classification. 
So then customer don't order license for many users, but just for 1.
Will it be working?

**Comment by shsagir** [comment]
@lightupdifire Thanks for your questions. I'm investigating and will get back to you.

**Comment by shsagir** [comment]
@lightupdifire Thanks again for your questions. After investigating, I've discovered that you should refer your licensing related questions to your Microsoft account team contact. Please be in contact with them, I'm sure they can assist you.
