### ISSUE TITLE
LAN (internal) IP

### ISSUE THREAD

**Issue by Trundlore** [MicrosoftDocs/CloudAppSecurityDocs#170]
The documentation here references using client LAN adapter address for identification of location. 
From what i have seen this will always show the NAT'd IP of the client through whatever internet connection it is connected to the internet.
Beyond that, identifying a trusted location by internal LAN IP seems completely insane, literally anyone could use that subnet.
Is the documentation wrong or is CAS allowing pointless configuration options opening trust holes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ef412a-b90e-dd0e-4d21-dfdaf87ea155
* Version Independent ID: fb376c81-cd6b-9f13-b2e5-5642f099a364
* Content: [Set IP ranges and tags - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/ip-tags#feedback)
* Content Source: [CloudAppSecurityDocs/ip-tags.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/ip-tags.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by shsagir** [comment]
@Trundlore Thanks for your questions. I'm investigating and will get back to you.

**Comment by shsagir** [comment]
@Trundlore  After investigating, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
