### ISSUE TITLE
More than 1 Azure account

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/CloudAppSecurityDocs#173]
How can we connect more than 1 Azure account; please suggest, is it supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da9a9fad-ff34-4689-c30e-404a774f9bd3
* Version Independent ID: 351b6aa7-da8e-350d-c002-6e0689b350cc
* Content: [Connect Azure to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-azure-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-azure-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-azure-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@shsagir

**Comment by shsagir** [comment]
@tmaheshwar Thanks for your question. It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
