### ISSUE TITLE
The term "sanction" is ambiguous and undefined

### ISSUE THREAD

**Issue by wcneumann219** [MicrosoftDocs/CloudAppSecurityDocs#174]
Since sanction can either mean approved or disapproved it is ridiculous to use that term with regards to allowing or banning applications, particularly when you don't provide any explanation about which meaning is intended!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77ab1f7-e882-65ed-8763-2ca0e7f2d3a6
* Version Independent ID: decde69d-a97a-6eb5-c98a-a7f93fe80793
* Content: [Blocking discovered apps - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/governance-discovery#feedback)
* Content Source: [CloudAppSecurityDocs/governance-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/governance-discovery.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@wcneumann219 Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
