### ISSUE TITLE
Cant add dynamic AzureAD groups in "Scope anomaly detection policies"

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/CloudAppSecurityDocs#175]
Tried adding a dynamic azure ad group on te include/ exclude step. Documentation says nothing  about that being a limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395e085f-93bd-1f3c-fe0d-7711b6d51950
* Version Independent ID: ad86d15d-41a5-9a6e-8d30-18ed9a9975f2
* Content: [Create anomaly detection policies in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/anomaly-detection-policy#scope-anomaly-detection-policies)
* Content Source: [CloudAppSecurityDocs/anomaly-detection-policy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/anomaly-detection-policy.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by o-l-a-v** [comment]
Seems like you can, it only takes some time before they appear in the MCAS User Groups selection. Might add that note to the documentation, that time from creating a Azure AD object until its selectable in MCAS User Groups GUI, is not instant.

**Comment by shsagir** [comment]
Thanks for your feedback; we appreciate it. We'll investigate the issue and get back to you.

**Comment by shsagir** [comment]
Thanks for your feedback. We've submitted a [documentation change](https://docs.microsoft.com/cloud-app-security/user-groups) based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
