### ISSUE TITLE
How to select all users in "Scope anomaly detection policies", but exclude some

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/CloudAppSecurityDocs#176]
The documentation is a little unclear when it comes to exclutions in the "Scope anomaly detection policies" category. I want to include all users in the tenant, but exclude one specific user. How do I do that?

* Do I include all users if "Include" is either deselected, or selected but no users or user groups are selected?
* If no to the question above, how do I easily achieve what I want? Ref issue 175, It's not possible to add dynamic Azure AD groups to MCAS User Groups, so selecting all users otherwise, dynamically, seems cumbersome.

Will this example include all users?
![image](https://user-images.githubusercontent.com/6450056/66920712-244c9b80-f024-11e9-9793-ca78384e5ac7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395e085f-93bd-1f3c-fe0d-7711b6d51950
* Version Independent ID: ad86d15d-41a5-9a6e-8d30-18ed9a9975f2
* Content: [Create anomaly detection policies in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/anomaly-detection-policy#scope-anomaly-detection-policies)
* Content Source: [CloudAppSecurityDocs/anomaly-detection-policy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/anomaly-detection-policy.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

However, the following information I received from support may be helpful to you:
> Clear **Include**, select **Exclude** and specify the user you want to exclude

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by o-l-a-v** [comment]
> Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.
> 
> However, the following information I received from support may be helpful to you:
> 
> > Clear **Include**, select **Exclude** and specify the user you want to exclude
> 
> To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

As I understand it, it's a mix of the product not being intuitive enough for the user to understand how to achieve what this ticket is about, and the documentation not clearly (or at all) stating how to include all users without using Azure AD dynamic groups for instance, but exclude certain users. Now that you've confirmed my assumption I've got an answer to my original question. Please add that to the documentation as well.
Thanks.
