### ISSUE TITLE
Cannot be used with AWS Gov Cloud fails on secret and access key input. 

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/CloudAppSecurityDocs#177]
Tried connecting a govt cloud aws account but the secret and acess keys never ask if you want to change to govt cloud and fail login in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf4839c-f4e3-5808-c608-f2795f7b640d
* Version Independent ID: 3ccbc129-d930-eb79-a034-365b89f88a13
* Content: [Connect Amazon Web Services with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-aws-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-aws-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-aws-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

However, the following information may be helpful to you:

* [Microsoft Cloud App Security for US Government GCC High](https://docs.microsoft.com/cloud-app-security/editions-cloud-app-security-gcc)

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
