### ISSUE TITLE
iboss Missing from note.

### ISSUE THREAD

**Issue by antseggs** [MicrosoftDocs/CloudAppSecurityDocs#178]
iboss also can automatically block unsanctioned apps using the MCAS API
https://docs.microsoft.com/en-us/cloud-app-security/iboss-integration
Can the note be updated to include iboss integration as well as zscaler to give customers visibility of this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77ab1f7-e882-65ed-8763-2ca0e7f2d3a6
* Version Independent ID: decde69d-a97a-6eb5-c98a-a7f93fe80793
* Content: [Blocking discovered apps - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/governance-discovery#feedback)
* Content Source: [CloudAppSecurityDocs/governance-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/governance-discovery.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
