### ISSUE TITLE
Can iboss be added to the notes please

### ISSUE THREAD

**Issue by shanco73** [MicrosoftDocs/CloudAppSecurityDocs#179]
iboss also can automatically block unsanctioned apps using the MCAS API, this can be seen using the link below.

https://docs.microsoft.com/en-us/cloud-app-security/iboss-integration

Could the note please be updated to include the iboss integration as well as zscaler to give customers visibility of this feature? 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77ab1f7-e882-65ed-8763-2ca0e7f2d3a6
* Version Independent ID: decde69d-a97a-6eb5-c98a-a7f93fe80793
* Content: [Blocking discovered apps - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/governance-discovery#feedback)
* Content Source: [CloudAppSecurityDocs/governance-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/governance-discovery.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
Duplicate of issue [178](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/178).
