### ISSUE TITLE
Possible to disable MCAS Role Override

### ISSUE THREAD

**Issue by metallicaf** [MicrosoftDocs/CloudAppSecurityDocs#180]
Is it possible so that Azure AD takes presidency despite assigning MCAS role

**Comment by shsagir** [comment]
Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
