### ISSUE TITLE
Excluding entities

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#181]
The text in this section states that there is an Excluded Machines tab, i'm not seeing this in my portal. Is there some prerequisite I need to get that feature or is this text out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fbda4c0-2222-b67a-615e-261fea7f3f05
* Version Independent ID: 13241ed3-46e9-5821-4760-4bdb9564c69e
* Content: [Working with discovered apps in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/discovered-apps#exclude-entities)
* Content Source: [CloudAppSecurityDocs/discovered-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovered-apps.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
