### ISSUE TITLE
Where are the uninstall directions?

### ISSUE THREAD

**Issue by dpace-cs** [MicrosoftDocs/CloudAppSecurityDocs#183]
There are no directions for uninstalling this container and docker in the event you need to redeploy or just wish to remove the CAS log collector entirely.

**Comment by shsagir** [comment]
Thanks for contacting Microsoft with your suggestion. I will look into the matter and get back to you.

**Comment by shsagir** [comment]
Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
