### ISSUE TITLE
Clarify acronym

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#184]
Please define CSPM in the the Secure IaaS services and custom apps section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e4354-bfb5-1b0a-d6d6-734290a15963
* Version Independent ID: 62d41ec5-f48d-d7fb-406a-2810a4ff4fbc
* Content: [Best practices for protecting your organization - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/best-practices#use-the-audit-trail-of-activities-for-forensic-investigations)
* Content Source: [CloudAppSecurityDocs/best-practices.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/best-practices.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
Thanks for your feedback. CSPM stands for Cloud Security Posture Management and in the context of Microsoft Cloud App Security refers to the security configurations assessments. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
