### ISSUE TITLE
Page title 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#185]
This page title is misleading, it should be MCAS e-books, there is another page for Webinars

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac5c55c-fdb8-cb4e-4371-410267cdce8c
* Version Independent ID: 587c6d3a-f150-015c-4b37-d5a9a15334d0
* Content: [Read our e-books - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/e-books)
* Content Source: [CloudAppSecurityDocs/e-books.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/e-books.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
Thanks for your feedback. Great catch! We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
