### ISSUE TITLE
Sharing Control - Stale externally shared files

### ISSUE THREAD

**Issue by pjcarr3** [MicrosoftDocs/CloudAppSecurityDocs#187]
Update the description to reflect that this does not check if file has been opened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0192fe47-4af3-0a7b-74a1-efbe7ad7536a
* Version Independent ID: 34ff03e6-aadf-638d-1b9f-30b999b19240
* Content: [Policy template reference for Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/policy-template-reference#feedback)
* Content Source: [CloudAppSecurityDocs/policy-template-reference.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/policy-template-reference.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@pjcarr3 Thanks for your feedback. Please can you provide a little more detail on the issue you raised? Which description are you referring to?

**Comment by pjcarr3** [comment]
Sorry I called it out in my title. It is the description for "Stale externally shared files. "

**Comment by shsagir** [comment]
@name Thanks for your the additional information. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
