### ISSUE TITLE
404 error to GCC MCAS page

### ISSUE THREAD

**Issue by cperrin10** [MicrosoftDocs/CloudAppSecurityDocs#188]
Is the documentation / links still in progress? 
They're currently hitting a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ac1d0d-1f97-1bbf-732b-c65bb89170b1
* Version Independent ID: a28b78cc-7b30-b5f2-29a5-dd35111e05a0
* Content: [Microsoft Cloud App Security for US Government GCC High](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-gcc#feedback)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-gcc.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-gcc.md)
* Service: **cloud-app-security**
* Product: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@cperrin10  Thanks for reporting the issue. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
