### ISSUE TITLE
Hey there is fault in the documentation.

### ISSUE THREAD

**Issue by DavySmets** [MicrosoftDocs/CloudAppSecurityDocs#189]
[Enter feedback here]
In the section: Create an Azure AD conditional access policy
it says:
Route users to Microsoft Cloud App Security by selecting the Use Conditional Access App Control enforced restrictions in the Session page.

But the options differ today.
you have 'use app enforced restrictions' and 'use Conditional Acces App control'. 
Do we have to select them both? The Use conditional acces app control has different options. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019ab0de-8c3b-7eba-3506-cc2ab655b4ed
* Version Independent ID: 8f37cbfb-edce-a737-5bc8-17f2ed3d5958
* Content: [Create session policies in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/session-policy-aad)
* Content Source: [CloudAppSecurityDocs/session-policy-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/session-policy-aad.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DavySmets Thanks for contacting Microsoft about your issue. As we understand it, you're describing a question about the product configuration and not with the product documentation. However, I will check with the product team and get back to you.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by shsagir** [comment]
@DavySmets Thanks again for your feedback. I discussed the matter with the product team and the **use app enforced restrictions** option is an unrelated Conditional Access feature and it is not required for Cloud App Security. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
