### ISSUE TITLE
Terminology and Missing information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#190]
MCAS has a Threat Detection policy category but does not have Threat Protection as a category, are these phrases interchangeable? it would be better if they were consistently used.
Also, there is a "Suspicious additions to sensitive groups" in the Threat Detection policy category, that is not described on this page. Where can I find the details about how that policy works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed369c7a-5261-5df9-4858-32522c2d5930
* Version Independent ID: 6ee8f528-54a8-a024-55d4-7e396ffb552b
* Content: [Threat protection policies - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/policies-threat-protection)
* Content Source: [CloudAppSecurityDocs/policies-threat-protection.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/policies-threat-protection.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross  Thanks for your feedback. We're investigating the issue and get back to you.

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
