### ISSUE TITLE
Deleting App Connector

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#191]
I have added a connector to Box and I no longer need it. How can I delete it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82896c8a-1071-33cc-9821-48c3c6a3d7bf
* Version Independent ID: a18117ae-a865-79e8-db21-924894bfe6c0
* Content: [Connect Box to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-box-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-box-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-box-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@name Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

However, the I received information from support may be helpful to you:

> Currently, to you must contact support to remove a Box connector.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by DeanGross** [comment]
Sorry I was not clear, the documentation does not provide any instructions about how to complete this task, I'm assuming that it is possible and I'd like the documentation to be updated to explain how we can do this.
