### ISSUE TITLE
Documentation On When OAuth Apps Access Data

### ISSUE THREAD

**Issue by xcactusx** [MicrosoftDocs/CloudAppSecurityDocs#192]
Is there any documentation on how to see when or what data an authorized oauth app is accessing? Looking at our tenant in Azure or 365, it is unclear.  I can see who authorized the app and in some cases signed into the app.  Activity log in 365 security center turns up blank for any app I check.   This makes it difficult to know if an app is no longer used and can be deleted.  Also, if the access information isn't logged anywhere, how would we know if an app is acting maliciously?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3543307c-9c07-720c-e4fe-3aa6cb43f680
* Version Independent ID: df363f37-c41a-7493-6573-c7a8f4ff1aaf
* Content: [Control which third-party cloud OAuth apps get permissions - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/manage-app-permissions)
* Content Source: [CloudAppSecurityDocs/manage-app-permissions.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-app-permissions.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@xcactusx Thanks for contacting Microsoft about your issue.

The following information may be helpful to you: [Investigate risky OAuth apps](https://docs.microsoft.com/cloud-app-security/investigate-risky-oauth)

To get assistance or support for your issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by xcactusx** [comment]
Thanks,  I had already read through that.  It really doesn't address the issue.  I'm aware of the rating system.  That doesn't help tell me what the app actually accessed or when.  We have something like 100 oauth apps installed and it would appear there is not an easy way to see when they were last used or what they are actually doing.  I'll open a case as you suggest, but it seems like this should already be documented somewhere.
