### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#195]
The Change to SIEM activities and alerts in CEF format announcement shows the url with protal, should that be portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee159bf-1044-a912-9920-288ac4e62050
* Version Independent ID: 5f8063d7-034b-e708-685f-396659fa59d0
* Content: [What's new in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/release-notes?source=docs#feedback)
* Content Source: [CloudAppSecurityDocs/release-notes.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/release-notes.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
