### ISSUE TITLE
Duplicate definitions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#197]
The descriptions for Suspicious cloud use and Suspicious activity alerts are the same. How do these alerts differ? please clarify  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70912b42-016b-d311-86cd-86f2e5e04a51
* Version Independent ID: 1744f30c-af16-cf4a-6a91-043e6f92b330
* Content: [Manage alerts raised in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/managing-alerts)
* Content Source: [CloudAppSecurityDocs/managing-alerts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/managing-alerts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@name Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@DeanGross Thanks again for your feedback. We've submitted a documentation change based on your observation to remove the duplicate, and the updated article should be live by tomorrow.  Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
