### ISSUE TITLE
grammar issue

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/CloudAppSecurityDocs#199]
remove apostrophe in the word "User's"  

A user must be signed in for Docker to collect logs. We recommend advising your Docker user's to disconnect without signing out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@netaneladar Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
