### ISSUE TITLE
I can't find the user enrichment setting

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/CloudAppSecurityDocs#200]
Is it because I am on E3 and not E5? 
The only setting I see in settings:
Score metrics
Snapshot reports
Continuous reports
Automatic log upload
App tags
Exclude entities
Anonymization
Delete data
Azure security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1ddbec-2517-6111-942c-305df8b725f8
* Version Independent ID: 4565cf20-c44b-d79b-73e1-327049687db3
* Content: [Enrich Cloud App Security Discovery data with Azure AD usernames](https://docs.microsoft.com/en-us/cloud-app-security/cloud-discovery-aad-enrichment)
* Content Source: [CloudAppSecurityDocs/cloud-discovery-aad-enrichment.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/cloud-discovery-aad-enrichment.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@netaneladar Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@netaneladar I discussed the issue with support and they need some information specific to your environment to investigate. Therefore, in the interest of protecting your privacy, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) to get further assistance.

**Comment by netaneladar** [comment]
Thank you Shlomo
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Jan 9, 2020 at 7:41 AM -0500, "Shlomo Sagir" <notifications@github.com> wrote:












@netaneladar I discussed the issue with support and they need some information specific to your environment to investigate. Therefore, in the interest of protecting your privacy, please open a support ticket to get further assistance.
