### ISSUE TITLE
Allow Syslog on non-standard port?

### ISSUE THREAD

**Issue by amyers1616** [MicrosoftDocs/CloudAppSecurityDocs#201]
Is there any way to allow a collector to run on a non-standard port?  From the drop-down all that's available is UDP & TCP which all default to port 514.  That means for each device we have I'd need to add a new VM.

**Comment by shsagir** [comment]
@name Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
