### ISSUE TITLE
Missing Identity Security Posture information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#204]
There is a page in the Investigation section for Identity Security Posture recommendations, but there is nothing about this in the documentation. Please update as necessary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bfee6e2-2879-2e43-0a8a-d3167762d6ee
* Version Independent ID: f5f6ae9a-b605-dc4d-7be6-335f47e101d5
* Content: [Investigate cloud app risks & suspicious activity - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/investigate?source=docs)
* Content Source: [CloudAppSecurityDocs/investigate.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/investigate.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@name Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@DeanGross Thanks again for your feedback. The Identity Security Posture feature relates to the native integration of Cloud App Security has with Azure Advanced Threat Protection (ATP). As such, the feature is documented in the [Azure ATP docs](https://docs.microsoft.com/azure-advanced-threat-protection/atp-isp-overview). We may add related information to the docs here as well, but in the meantime I am closing this ticket. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
