### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MukundaMurthy** [MicrosoftDocs/CloudAppSecurityDocs#205]
The link to "Learn more about Gov GCC High" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ac1d0d-1f97-1bbf-732b-c65bb89170b1
* Version Independent ID: a28b78cc-7b30-b5f2-29a5-dd35111e05a0
* Content: [Microsoft Cloud App Security for US Government GCC High](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-gcc)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-gcc.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-gcc.md)
* Service: **cloud-app-security**
* Product: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@MukundaMurthy Thanks for your reporting the issue. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
