### ISSUE TITLE
Maximum group size

### ISSUE THREAD

**Issue by demores** [MicrosoftDocs/CloudAppSecurityDocs#206]
What is the maximum group size that can be imported?

**Comment by shsagir** [comment]
@demores Thanks for contacting Microsoft about your issue. As we understand it, you're describing a question relating to the product itself and not with the product documentation.

However, if you feel this relates to documentation, please can you provide the URL of the topic and a some more details about the context of the query? To follow up on this issue, leave us a comment with an @mention.  

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by demores** [comment]
@shsagir  Thank you for your attention, but I disagree that this is a support ticket.  I opened this ticket here because it appears that the documentation is missing helpful information about the product.

I'm reading this documentation in preparation to importing user groups.  It would be very helpful if it included information like the maximum size of a user group that can be imported.

If there is a limit on the size of a user group that can be imported, and if importing a user group that is larger than the maximum size would cause the import to fail, then I would hope that important  information like that, information that would explain why the product is not working as expected, information that would prevent a bad user experience, and information that could prevent a call to Support, would be made available to customers and added to the product documentation.

This documentation does not contain information about maximum user group size.  Could information about whether or not there is a maximum group size and what that size is be added to the documentation?
