### ISSUE TITLE
User group admin / File page

### ISSUE THREAD

**Issue by martin-rublik** [MicrosoftDocs/CloudAppSecurityDocs#208]
According to documentation User group admin should have no permissions to Files page. Does it mean the User group admin does not see any infomration in the Files page or the User group admin sees all files across the tenant regardless to the ownership of the file (the file is owned by the member of the respective group)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@martin-rublik Thanks for contacting Microsoft with your question. We are looking into your question and will get back to you soon.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by shsagir** [comment]
@martin-rublik  Thanks again for contacting Microsoft about your issue. Having looked into your question, I can confirm that **User group admins** don't have permissions to see any information in the Files page and that the documentation is correct.

Please let us know if there’s anything more we can do for you. To follow up on this issue, leave us a comment with an @mention, or to get further assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
