### ISSUE TITLE
Change from Block to Report

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/CloudAppSecurityDocs#209]
Is supported to change the automatically created rule from Block to Report by Administrator? If changed in MCAS again, will MCAS override this or create new rule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b2133d-85b3-8e2c-c89a-7d83f48e5dd0
* Version Independent ID: 84598ed0-a8ea-5504-2b87-b20df2347e53
* Content: [Integrate Microsoft Defender ATP with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/wdatp-integration)
* Content Source: [CloudAppSecurityDocs/wdatp-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/wdatp-integration.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Kazzan Thanks for contacting Microsoft about your issue. As we understand it, you're asking a question about the product itself and not with the product documentation.

I'm looking into the query and will get back to you, though it may take a little while.

To get assistance or support for your product question, please open a support ticket.

**Comment by Kazzan** [comment]
Thanks @shsagir for challenge product team to obtain the answer. The question itself is about product functions which should be documented there.

**Comment by shsagir** [comment]
@Kazzan After looking into the scenario you described with the product team, I understand you are perhaps asking for a new feature. If this is the case, the best way to request it is using the feedback button in the portal to make the request.

Just to clarify, the integration with Microsoft Defender ATP allows you to view information about the cloud apps and services being accessed from IT-managed Windows 10 machines, and optionally block those apps marked as unsanctioned.

Please let us know if there’s anything more we can do for you. To follow up on this issue, leave us a comment with an @mention, or to get further assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by Kazzan** [comment]
Hi @shsagir I am not asking about new feature (maybe in the end, but not for now). I just want to clarify how the integration working here in article.

Example. In MCAS, you create Sanctioned app. Based on the "Score" of app in MCAS the rule in MDATP is automatically created by MCAS with risk level "High/Medium/Low" with Block Action.

Customer just asking if they can:
- Change the automatically created rule (if it is supported or not)
- What happen if they change the rule in MDATP and someone change the settings in MCAS (will be changed rule overwritten or created another)

These answers should be documented in this integration article or somewhere else in MCAS/MDATP docs I mean. Thanks.
