### ISSUE TITLE
traffic flow and protect macOS users

### ISSUE THREAD

**Issue by kelvinwong927** [MicrosoftDocs/CloudAppSecurityDocs#210]
As mentioned that the Microsoft Cloud Apps Security can integrate with the Zscaler. Does it mean all the traffic from the Zscaler agent installed in laptop/desktop will forward to Microsoft Cloud App Security for deep analysis as well as conditional control? Since most of our users are using MacBook, that's why I am thinking if the Zscaler manages the Macbook traffic and sends it to Microsoft Cloud App Security for conditional control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efc6f96-264f-14ea-3a9a-da5f9d13c6a0
* Version Independent ID: 4c146408-6337-cddb-d79f-ae83e9d327a7
* Content: [Integrate Cloud App Security with Zscaler](https://docs.microsoft.com/en-us/cloud-app-security/zscaler-integration#feedback)
* Content Source: [CloudAppSecurityDocs/zscaler-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/zscaler-integration.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@kelvinwong927  Thanks for contacting Microsoft about your issue. As we understand it, you're asking a question about the product itself and not with the product documentation.

I'm looking into the query and will get back to you, though it may take a little while.

To get assistance or support for your product question, please open a support ticket.

**Comment by shsagir** [comment]
@kelvinwong927 Thanks again for your feedback. After discussing the question with the product team, I can confirm that integration is based on the Zscaler cloud solution as specified in the docs.

For more details about which signals are collected by ZScaler and from which operating systems, please contact with ZScaler.
