### ISSUE TITLE
How does the reverse proxy works when O365 tenant integrated with 3rd party SSO solutions?

### ISSUE THREAD

**Issue by kelvinwong927** [MicrosoftDocs/CloudAppSecurityDocs#211]
Since the existing O365 tenant integrated with 3rd party SSO solutions, see if the reverse proxy can be work with 3rd party SSO instead of Azure AD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect with Microsoft Cloud App Security Conditional Access App Control](https://docs.microsoft.com/en-us/cloud-app-security/proxy-intro-aad)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@kelvinwong927 Thanks for contacting Microsoft about your issue. As we understand it, you're asking a question about the product itself and not with the product documentation.

I'm looking into the query and will get back to you, though it may take a little while.

To get assistance or support for your product question, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by shsagir** [comment]
@kelvinwong927 Thanks again for your question. The following information I received from support may be helpful to you:

The reverse proxy can be placed in front of an existing 3rd party SSO solution. Depending on how O365 is configured to federate between that solution and Azure AD, there may be limitations to the app granularity Cloud App Security can to apply to the policies.

If you require any further assistance with this question, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
