### ISSUE TITLE
Typo on Tutorial: Investigate risky OAuth apps

### ISSUE THREAD

**Issue by derpadoo** [MicrosoftDocs/CloudAppSecurityDocs#212]
Typo on this page: https://docs.microsoft.com/en-us/cloud-app-security/investigate-risky-oauth

![image](https://user-images.githubusercontent.com/27816854/74539362-81d5f380-4f03-11ea-909b-3f0dbcfe1a79.png)

Should be `OAuth`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1104bcc3-c31f-74d3-e01c-a2f08f3eabab
* Version Independent ID: 4742aaa0-9258-b791-2687-2287d157812a
* Content: [Investigate risky OAuth apps - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/investigate-risky-oauth)
* Content Source: [CloudAppSecurityDocs/investigate-risky-oauth.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/investigate-risky-oauth.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@derpadoo Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
