### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#214]
In the Security Configuration section of MCAS, there is a tab for Regulatory Compliance but there is no documentation for this tab like there is for Azure and AWS. Please provide instructions for that pages usage. I am not seeing any Compliance Standards, Apps or Subscriptions on the Regulatory Compliance page and I'm guessing that I may have something misconfigured

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fe1b375-0310-8c4e-4c90-6426ab8f59e7
* Version Independent ID: 123a9827-96fb-f39a-dfaa-1df883ccb211
* Content: [Get security configuration recommendations for Azure - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/security-config)
* Content Source: [CloudAppSecurityDocs/security-config.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/security-config.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@name Thanks for your feedback. We've considred your suggestion and a request has been raised to add the missing information. In the meantime, I'm closing this issue.  Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
