### ISSUE TITLE
Automatically apply classification label to PDF (without protection)

### ISSUE THREAD

**Issue by DTGitRepository** [MicrosoftDocs/CloudAppSecurityDocs#215]
Bit confused: https://docs.microsoft.com/en-us/cloud-app-security/session-policy-aad#protect-download does state that protect has to be selected, it also states here https://docs.microsoft.com/en-us/cloud-app-security/azip-integration#prerequisites that PDFs are supported. 
Are they only supported for manual label application?

Testing a conditional access app session policy and it would be great if I could automatically apply a label to PDFs.

**Comment by shsagir** [comment]
@DTGitRepository Thanks for contacting Microsoft with feedback about our product. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@DTGitRepository Thanks again for your question. I clarified with the product team and if you are using unified labels, they are applied automatically. In addition, you can create your own policies to add additional labels.
