### ISSUE TITLE
Whis is Allow missing?

### ISSUE THREAD

**Issue by pchIT** [MicrosoftDocs/CloudAppSecurityDocs#216]
This article describes two options being available under Actions, Allow and Block.  However, when I go to create a Cloud App Security access policy, the two options available are actually Test and Block, there is no Allow option.  Why is there no option to Allow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e0921d-c905-8f46-403d-2e05e9645cb8
* Version Independent ID: af25066d-94c9-923d-0f65-36d834adcbc0
* Content: [Create Cloud App Security access policies to allow and block access](https://docs.microsoft.com/en-us/cloud-app-security/access-policy-aad#feedback)
* Content Source: [CloudAppSecurityDocs/access-policy-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/access-policy-aad.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@pchIT Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@pchIT Thanks for your feedback. We've submitted a documentation change based on your feedback, and the updated article should be live by tomorrow. The Allow option is the replaced by Test, but they are the same thing. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
