### ISSUE TITLE
Product feedback

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/CloudAppSecurityDocs#217]
Product feedback link point to a non-existing page on uservoice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18085b0-ca97-5623-fc42-5395acf55f1f
* Version Independent ID: 942d682c-a471-a8c9-e12f-cc7d4aafbad3
* Content: [Support and troubleshooting information for Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/support-and-ts)
* Content Source: [CloudAppSecurityDocs/support-and-ts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/support-and-ts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@kennethvs Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@kennethvs Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
