### ISSUE TITLE
Can't find  'Block unsanctioned apps' in Cloud App Security

### ISSUE THREAD

**Issue by Matthew-DBschenker** [MicrosoftDocs/CloudAppSecurityDocs#219]
Hi ,
I followed instructions in this article , but can't find 'Settings &gt; Cloud app control, and then select Block unsanctioned apps.' Would you please help me out ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b2133d-85b3-8e2c-c89a-7d83f48e5dd0
* Version Independent ID: 84598ed0-a8ea-5504-2b87-b20df2347e53
* Content: [Integrate Microsoft Defender ATP with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/wdatp-integration#feedback)
* Content Source: [CloudAppSecurityDocs/wdatp-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/wdatp-integration.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Matthew-DBschenker Thanks for your feedback. We've submitted a documentation change based on your issue with updated instructions, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
