### ISSUE TITLE
OAuth app policy

### ISSUE THREAD

**Issue by NicolaiH** [MicrosoftDocs/CloudAppSecurityDocs#222]
Hi. When I create a new policy, the only option I have is 'App discovery policy', I can't find anything about OAuth in Cloud App Security. Is this guide outdated or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 761bb043-6da5-7c36-02af-76be128250b6
* Version Independent ID: 7ebda947-3455-2af3-17ad-b385bac60827
* Content: [Create policies to control OAuth apps in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/app-permission-policy#feedback)
* Content Source: [CloudAppSecurityDocs/app-permission-policy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/app-permission-policy.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@NicolaiH Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@NicolaiH Thanks again for contacting Microsoft about your issue. As we understand it, you're describing a product question relating to your set up and not with the product documentation.

Therefore, we suggest you contact support to get assistance with your product issue, by [opening a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
