### ISSUE TITLE
outline what happens when API issuer is deprovisioned

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/CloudAppSecurityDocs#224]
a user with "security reader" issues a API within MCAS
what happens when that user leave the company / is deprovisioned?
material needs a clear statement on this - does it reside or is it deleted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49f4498-7b65-28f7-f31d-c7a21149025e
* Version Independent ID: d93e55ac-bec8-5aba-5cba-923cee400542
* Content: [API token management in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/api-tokens)
* Content Source: [CloudAppSecurityDocs/api-tokens.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-tokens.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@bakerm00 Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@bakerm00 Thanks again for your feedback. I received the following response from the product team regarding your query:

> Deprovisioned users API tokens are retained but have no use. Any attempt to use them will result in a permission denied response.

We've will be submitting a documentation change based on your query, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
