### ISSUE TITLE
What does the Global variable data include in CAS?

### ISSUE THREAD

**Issue by dreeves14** [MicrosoftDocs/CloudAppSecurityDocs#228]
We've set up the log collector on prem that is currently grabbing information from 2 Meraki MX100's. I can select each firewall individually and see whats been collected. However if I select global, which I assumed combined both the app #'s do not match.
for Example: Meraki A: showed a total 1000 Apps | Meraki B: Showed 200 apps | Global showed 1100 Apps.

So Global is referencing what data set(s)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19faaa3d-f160-361c-406b-b257498224e1
* Version Independent ID: 2c9d8c98-c043-b73b-d54e-98f9cfbd6e4e
* Content: [Anonymize user data in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/cloud-discovery-anonymizer)
* Content Source: [CloudAppSecurityDocs/cloud-discovery-anonymizer.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/cloud-discovery-anonymizer.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@dreeves14 Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

However, I will investigate the issue and get back to you. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by shsagir** [comment]
@dreeves14 Thanks for your feedback. After investigating, I've received the following response from the product team that might be helpful to you: The global variable is a union of data coming from all data sources.

If you require any further assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by dreeves14** [comment]
I appreciate the help!  You mentioned I brought up a problem with the product and not the documentation -- that's false, the documentation doesn't address that data set(s) as far as I can tell, that's why I asked.

The answer from the product team, although appreciated, also doesn't make sense because if it's a union of all data sources than the total # of apps in Global when the length/time spam (7 dsys) is equal (which I set to 7 days across both firewalls, and checked global) did not match. Firewall A + Firewall B's app count. Global was less than A+B, but more than both of them by themself. So unless this is omitting the firewall data and is pulling from other places altogether the answer doesn't work. Again the documentation doesn't reference this Global data sets data source(s), that is what I am curious about.

Appreciate the prompt response! Be safe out there friend!

-DR

Get Outlook for Android<https://aka.ms/ghei36>
    
    
    
    Dalton Reeves    
    Senior Systems Administrator + Technology    
    P (314) 655-5523 | F (314) 309-3103    
    dreeves@anderscpa.com | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS
________________________________
