### ISSUE TITLE
Conditional Access App Control domain list

### ISSUE THREAD

**Issue by abmartinr** [MicrosoftDocs/CloudAppSecurityDocs#230]
Hey there,

> For example, Contoso protects its environment using Conditional Access App Control provided by Cloud App Security. When a Contoso user visits fabrikam.com, the user is automatically redirected to fabrikam.com.<region>.cas.ms. As a result, Fabrikam's phishing team will see a new DNS entry and certificate for fabrikam.com.<region>.cas.ms.
> 
> So even though Fabrikam does not actually use Cloud App Security, they see the DNS entry or certificate because Contoso does.

Does this include all these domains?

- *.admin-rs-mcas.ms
- *.rs-mcas.ms
- *.admin-rs2-mcas.ms
- *.rs2-mcas.ms
- *.admin-mcas.ms
- *.mcas.ms

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e092a97-a2c2-849c-6bd0-6e73a90ffc57
* Version Independent ID: 2eeaa902-7a79-5a32-0031-2290302a378f
* Content: [Troubleshooting - What is cas.ms, mcas.ms, or mcas-gov.us?](https://docs.microsoft.com/en-us/cloud-app-security/troubleshooting-proxy-url)
* Content Source: [CloudAppSecurityDocs/troubleshooting-proxy-url.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/troubleshooting-proxy-url.md)
* Service: **cloud-app-security**
* Product: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@abmartinr Thanks for contacting Microsoft about your issue. As we understand it, you're describing a question about the product itself and not with the product documentation.

I will forward your question to the product team, though it could take from a few business days to a few weeks to look further into your question.

To get assistance or support for your product issues, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by shsagir** [comment]
@abmartinr Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

**Comment by bultaf14** [comment]
@shsagir do you have an update on when the article will be updated? The date still shows 3/18/20. Thanks

**Comment by shsagir** [comment]
@bultaf14 Apologies, there was a delay at my end. The change will be published this week.
