### ISSUE TITLE
Team Chat Messages

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/CloudAppSecurityDocs#232]
We have a problem with Teams chat messages showing as "create item: email" in cloud app security. Is there a way to have team messages show as what they are?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18085b0-ca97-5623-fc42-5395acf55f1f
* Version Independent ID: 942d682c-a471-a8c9-e12f-cc7d4aafbad3
* Content: [Support and troubleshooting information for Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/support-and-ts#feedback)
* Content Source: [CloudAppSecurityDocs/support-and-ts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/support-and-ts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@HarrisburgUSysAdmin Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
