### ISSUE TITLE
More documentation for the Built-in content inspection scan policies

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/CloudAppSecurityDocs#233]
Hi, documentation about the built-in content inspection scan policies would add a lot of value.  I'm working on implementing controls for a customer in MCAS and these are currently hit/miss in their usability because it is not well defined what they are actually looking for, with the exception of the Credit Card numbers.  Full name and DOB, for example, I've been testing and unable to get a policy with that built-in content inspection to fire.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79cda6f-4c82-cd9c-89b0-581f17fde43f
* Version Independent ID: c554bccf-27ed-ed76-38de-7c44e0d11c06
* Content: [How Cloud App Security performs content inspection](https://docs.microsoft.com/en-us/cloud-app-security/content-inspection-built-in#feedback)
* Content Source: [CloudAppSecurityDocs/content-inspection-built-in.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/content-inspection-built-in.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@exactmike Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@exactmike Thanks for contacting Microsoft about your issue. Currently, there are no plans to document the specifics of each inspection. If you require more precise definitions, we recommend using the [DCS](https://docs.microsoft.com/cloud-app-security/dcs-inspection) inspection method that has inspection details documented in [Sensitive information types](https://docs.microsoft.com/microsoft-365/compliance/what-the-sensitive-information-types-look-for).

**Comment by exactmike** [comment]
@shsagir Hi, Sorry, this is not an option for many use cases right now.  I am using the DCS inspection method wherever that is possible, but so far, you have not enabled this capability for an action like inspecting a Teams or Slack chat message.  In that case we are forced to use the built-in content inspection scan policies.  I would urge you to reconsider documenting these built-in content inspection scan policies more thoroughly OR to communicate that you are going to expand the ability to use the DCS inspection method to all scenarios where content inspection is a capability of MCAS.
