### ISSUE TITLE
Wording needs updating

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/CloudAppSecurityDocs#234]
Under 'How to integrate Azure Information Protection with Cloud App Security' item no. 2 the wording should be updated to be 'Automatically scan new files for Azure Information Protection classification labels and content inspection warnings.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Azure Information Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/azip-integration)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/azip-integration.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@challengelogic Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
