### ISSUE TITLE
Clarity needed

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/CloudAppSecurityDocs#235]
This document needs to tell the reader 'where' Governance actions are set - i.e. creating or editing a policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e0b4a0-215a-c25f-b9e9-4bbda8ca5ee7
* Version Independent ID: b39af630-a9cc-f2e1-29a4-5df95a9e6fa3
* Content: [Governance actions to control connected apps - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/governance-actions)
* Content Source: [CloudAppSecurityDocs/governance-actions.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/governance-actions.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@challengelogic Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
