### ISSUE TITLE
Governance log

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/CloudAppSecurityDocs#236]
For section 'Governance log' - where is this found?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e0b4a0-215a-c25f-b9e9-4bbda8ca5ee7
* Version Independent ID: b39af630-a9cc-f2e1-29a4-5df95a9e6fa3
* Content: [Governance actions to control connected apps - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/governance-actions)
* Content Source: [CloudAppSecurityDocs/governance-actions.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/governance-actions.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@challengelogic Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@challengelogic Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
