### ISSUE TITLE
Dont see option

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/CloudAppSecurityDocs#237]
Under section 'Add a new custom cloud app' I don't see the dashboard listed under step 'In the Cloud App Security portal, click on Discover and then Cloud Discovery dashboard.' I am using M365 E5 Trial licence. I only have Cloud App Catalog as a choice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e962f6e7-55b5-f4b3-f7d1-94fda5ccefb8
* Version Independent ID: 81cb6e5d-6015-70af-6096-0d0664212704
* Content: [Add custom apps to Cloud Discovery in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/cloud-discovery-custom-apps)
* Content Source: [CloudAppSecurityDocs/cloud-discovery-custom-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/cloud-discovery-custom-apps.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@challengelogic Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@challengelogic  Our product team tried to reproduce your issue but could not reproduce the issue.

I suggest you contact support describing the process of how you created the tenant. To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
