### ISSUE TITLE
Invite external admins

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/CloudAppSecurityDocs#238]
The section 'Invite external admins' does not describe the process of how external admins can gain access. With 'Manage admin access' from the settings cog in MCAS you can only select users for the tenant domain (i.e. not an external user). How is this performed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@challengelogic Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
