### ISSUE TITLE
Salesforce Authentication - Connected App support

### ISSUE THREAD

**Issue by Clint-Chester** [MicrosoftDocs/CloudAppSecurityDocs#243]
Hey there 😄 reviewing the documentation for authorising the connection between Cloud App Security and Salesforce. I know this talks about using a service account with admin privileges, but it doesn't make a mention of using [Connected Apps](https://help.salesforce.com/articleView?id=connected_app_overview.htm&type=5). 

Looking to find out whether it is possible to make use of a Connected App or whether you will provide authentication via this mechanism? The current approach mentioned isn't the best security practices from a Salesforce perspective.

Any information would be greatly appreciated 😄 thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88294d23-b573-bb18-d6f9-65a06614b0d5
* Version Independent ID: 1a87274f-14b2-393c-f535-b571748817a2
* Content: [Connect Salesforce to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-salesforce-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-salesforce-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-salesforce-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Clint-Chester Thanks for contacting Microsoft about your issue. As we understand it, you're describing a question with the product itself and not with the product documentation.

However, I will check with the product team and get back to you, though it may take a few days or weeks depending on the complexity of the scenario.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

**Comment by Clint-Chester** [comment]
Thanks @shsagir appreciate it. Keen to hear updates on this 😄

**Comment by shsagir** [comment]
@Clint-Chester Here's an update I received from the product team may be helpful to you:

> Currently it's not a planned feature - Admin privileges are essential to provide the protection expected by a CASB.

If you wish to discuss this further, you can [send the Cloud App Security team feedback](mailto:casfeedback@microsoft.com) with details of the feature and why you think it's necessary.

**Comment by Clint-Chester** [comment]
Yeah will do. It's not about the admin privileges but rather how they are provided and requested. Proper security design on the Salesforce end is about controlling and managing the channels that third party apps are accessing the application. More information about the use cases can be found [here](https://help.salesforce.com/articleView?id=connected_app_about.htm&type=5).

Given that CASB helps with detecting unauthorised third party apps into the environment, it's a little on the nose that the CASB connection would use the exact same process of these other apps 😄. I'll send through the feedback on the link you provided too.
