### ISSUE TITLE
More Azure recommendations expected for this page

### ISSUE THREAD

**Issue by davi-cruz** [MicrosoftDocs/CloudAppSecurityDocs#245]
Considering this is an "in Azure" page, I would expect some more information regarding other recommended specs like VM Size (I assume that would be a D2S_v3 based on hardware requirements) as well as if premium disk or network acceleration is recommended for this appliance.
A bonus would be having an ARM template to deployment, so customer would with a few clicks have it created.

Count on me if is there anything I could help on this improvements :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 818cbf6b-c397-8c86-e061-8e940ee94278
* Version Independent ID: 53b66b18-5321-b63e-a57b-44f146ff6944
* Content: [Configure automatic log upload using Docker in Azure](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu-azure#feedback)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@davi-cruz Thanks for contacting Microsoft with feedback about our product documentation. I'll forward your suggestions to the product and depending on the complexity, it could take from a few business days to a few weeks to look further into your suggestions. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@davi-cruz Thanks for your feedback. We've relayed the information to our engineering team who have added it to the list for further analysis. In the meantime, I am closing this issue.

If you are experiencing a specific issue that requires our assistance, please [opening a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
