### ISSUE TITLE
Salesforce Connection - Permission Sets

### ISSUE THREAD

**Issue by Clint-Chester** [MicrosoftDocs/CloudAppSecurityDocs#246]
Hey again 😄 in your instructions here it recommends cloning a profile to setup the security. This isn't the best approach from a Salesforce perspective and is leading people down the wrong path from a Salesforce setup point of view. This will create an overhead on managing the overall Salesforce security model for those people doing this.

You should look at recommending people make use of [Permission Sets](https://help.salesforce.com/articleView?id=perm_sets_overview.htm&type=5). This will allow them to still setup the right access privileges, but also give them the ability to ensure that the service account being used doesn't have additional privileges it shouldn't have.

Any questions on it feel free to ask 😄 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88294d23-b573-bb18-d6f9-65a06614b0d5
* Version Independent ID: 1a87274f-14b2-393c-f535-b571748817a2
* Content: [Connect Salesforce to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-salesforce-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-salesforce-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-salesforce-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Clint-Chester Thanks again :-) for contacting Microsoft about your issue. As we understand it, you're suggesting an improvement to the way the SalesForce connector is configured and not with the product documentation.

I forwarded your suggestion to the product team for their consideration. I appreciate your offer to help and should they request it, I will be in further contact. In the meantime, as this is not a documentation problem, I'm closing this issue.

**Comment by shsagir** [comment]
@Clint-Chester Following up on my previous comment, the product team would be interested in discussing the matter further with you. Please [send a message](mailto:casfeedback@microsoft.com) and include a reference to this ticket and the details of your suggestion. Thank again.

**Comment by Clint-Chester** [comment]
Will do 😄 happy to flick up a PR for it too.
