### ISSUE TITLE
This page should specify that the Data Classification Service integration cannot be used to inspect non-file activities such as sending a chat message.

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/CloudAppSecurityDocs#247]
for inspection/classification of messages such as a slack or Teams message or other type of user submission that is not a file upload, download, or storage, only the built-in classification service can be used.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd9cbfc7-4af8-817d-7757-0b5f648c534c
* Version Independent ID: ab9d3dd7-a10b-dc76-452b-02d087474417
* Content: [Cloud App Security content inspection using Microsoft Data Classification Service](https://docs.microsoft.com/en-us/cloud-app-security/dcs-inspection)
* Content Source: [CloudAppSecurityDocs/dcs-inspection.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/dcs-inspection.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@exactmike Thanks for contacting Microsoft with feedback about our product documentation.

Since the topic discusses file inspection methods, that is the context in which DCS is mentioned. However, I'm interested to know why you think it necessary to state that it doesn't apply to non-file activities. Can you explain the reasoning? Tx

**Comment by exactmike** [comment]
yes, see #233.  The problem is that you are recommending DCS in your response to me in #233, but DCS cannot work in the situation I was describing to you in #233.  So, in my opinion, both this page and the built-in classification page need to clarify the scenarios where they are applicable.  the built-in classification can be used for file or non-file scenarios whereas DCS can only be used for file scenarios.  This is also specifically why additional documentation for the built-in classification types would be useful . . . because DCS cannot be used in some situations (at least not yet).

**Comment by shsagir** [comment]
@exactmike  Following up on my previous comment, the product team would be interested in discussing the matter further with you. I'll close this issue but please [send a message](mailto:casfeedback@microsoft.com) to the team and include a reference to this ticket and the details of your suggestion. Thanks again.
