### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by andresthegarcia** [MicrosoftDocs/CloudAppSecurityDocs#248]
Hi there, does MD-ATP for Mac OS integrate w/ Cloud App Security? I can't find any documentation on this. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b2133d-85b3-8e2c-c89a-7d83f48e5dd0
* Version Independent ID: 84598ed0-a8ea-5504-2b87-b20df2347e53
* Content: [Integrate Microsoft Defender ATP with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/wdatp-integration#feedback)
* Content Source: [CloudAppSecurityDocs/wdatp-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/wdatp-integration.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@andresthegarcia Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@andresthegarcia Thanks for your feedback. After investigating, we've discovered that the issue isn't that Cloud App Security does not integrate with Microsoft Defender ATP for Mac OS. The issue is that the latter does not support traffic logs hence does not send any information to the Cloud Discovery feature.

**Comment by andresthegarcia** [comment]
@shsagir I appreciate the prompt response. I am aware of at least one CASB solution in the market offering traffic steering for Mac OS clients. Is this something that could be considered in future roadmaps?
