### ISSUE TITLE
Dangerous Recommendation for Blob Storage Firewall Exclusions

### ISSUE THREAD

**Issue by phillym** [MicrosoftDocs/CloudAppSecurityDocs#251]
Hi there,
A problem we regularly come across is Microsoft documentation advising all of Azure Blob Storage endpoints to be allowed through firewalls or excluded in proxy/intercept configurations to make a product work.
e.g:
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4942
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3500

Can you please change *.blob.core.windows.net in the recommendations under "Portal Access" on this page, to explicitly define the Azure Blob endpoints we need to allow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96223442-ff3d-c101-214f-2240ac42d53b
* Version Independent ID: 56fead2d-d0ba-ce69-e931-5b91ed43c736
* Content: [Network requirements - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/network-requirements#portal-access)
* Content Source: [CloudAppSecurityDocs/network-requirements.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/network-requirements.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@phillym Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@phillym Just a quick update to let you know that we are still looking into this and will get back to you.
