### ISSUE TITLE
Update Step 1

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/CloudAppSecurityDocs#254]
Hello,

None of the steps under "Step 1. Set instant visibility, protection, and governance actions for your apps" appear to be relevant. There is a cog icon to the top-right of the Office 365 Cloud App Security portal, but nothing else listed in those steps is anywhere to be found. Unsure how to proceed.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@ckssaas Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@ckssaas Please verify that you are using one of the prerequisites licenses mentioned in the [licensing datasheet](https://aka.ms/mcaslicensing). You can also try verifying whether the feature is available in your environment by using the left menu to navigate to **Investigation** > **Connected apps**.

If you are still experiencing the issue, please [open a support ticket].(https://go.microsoft.com/fwlink/?linkid=2099672).
