### ISSUE TITLE
OCAS with EMS E3 license alone is not supporting OCAS URL - proxy replacement.

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/CloudAppSecurityDocs#255]
OCAS with EMS E3 license alone is not supporting OCAS URL - proxy replacement, Either EMS E3 bundled with MCAS or EMS E5 requires for this feature. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a66643-56f5-dc00-5af6-3ee1d9b6f090
* Version Independent ID: c319c4a4-974e-7e3a-d58a-76fd57a9efe9
* Content: [Differences between Cloud App Security and Office 365 Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365#feedback)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-o365.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-o365.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Balamurugan-dot  Correct, this information is available in the [Microsoft Cloud App Security licensing datasheet](https://aka.ms/mcaslicensing) mentioned at the top of the topic. Thanks for your inquiry.
