### ISSUE TITLE
Azure AD Identity Protection section is not present

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/CloudAppSecurityDocs#262]
Hi

It doesn't look like my tenant has this feature. Has this been rolled out everywhere? See image below.

![image](https://user-images.githubusercontent.com/8972968/82235639-e05ba500-992a-11ea-8b59-8b6cdf4d2128.png)

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 552d2bf4-cb6c-81cc-f57f-b835ee7d66ad
* Version Independent ID: 89032a04-56e6-5553-0862-167816733f4f
* Content: [Integrate Azure Active Directory Identity Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/aadip-integration)
* Content Source: [CloudAppSecurityDocs/aadip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/aadip-integration.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@zlDev Please verify that you are using one of the prerequisites licenses mentioned in the [licensing datasheet](https://aka.ms/mcaslicensing).

If you are still experiencing the issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).
