### ISSUE TITLE
What does user status 'N/A' mean?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/CloudAppSecurityDocs#263]
Hello,

in the Cloud App Security panel, there's under `Investigate > Users and Accounts` an user with status `N/A`. What does this status mean? How to fix it? Is this status for accounts common/not an error?

The documentation just mentions possible statuses but not their meaning:

> Status: Filter based on user account status of N/A, staged, active, suspended, or deleted.

Thank you for clarification!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec49198-bda6-5138-159f-f80ef187b9b0
* Version Independent ID: 62bb765d-10f1-f04b-d293-6184be709b02
* Content: [Visibility into cloud app accounts - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/accounts)
* Content Source: [CloudAppSecurityDocs/accounts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/accounts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@GiantCrocodile Thanks for your feedback.

A status of not available (N/A) is normal and may appear, for example, for anonymous accounts. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
