### ISSUE TITLE
Identity Security Posture

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#264]
I cannot find any information about the Identity Security Posture page that is available at https://mycompany.portal.cloudappsecurity.com/#/identity-security-posture. Please update the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee159bf-1044-a912-9920-288ac4e62050
* Version Independent ID: 5f8063d7-034b-e708-685f-396659fa59d0
* Content: [What's new in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/release-notes)
* Content Source: [CloudAppSecurityDocs/release-notes.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/release-notes.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@name Thanks for your feedback.

Identity Security Posture comes from our native integration with Azure Advanced Threat Protection (Azure ATP). The feature is documented in [Azure ATP's identity security posture assessments](https://docs.microsoft.com/azure-advanced-threat-protection/atp-isp-overview) but we'll look into adding links to it from the Cloud App Security docs. This may take a few business days or weeks to complete, so we're closing this ticket.

We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. To follow up on this issue, leave us a comment with an @mention.

**Comment by DeanGross** [comment]
thanks, that should be fine
