### ISSUE TITLE
How long does it take for an activity policy to be active?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/CloudAppSecurityDocs#265]
Hello,

in a service request we had some issue with activity policies. The activity policy was set to monitor on Log On activity in Azure or Office 365 and it took some time until alerts were raised. So how long does it take after creation/saving of the policy to become active, e. g. sending out email notifications?

I also noticed two asterisks (**) in the article. This should be fixed as it's either broken formatting or a missing footnote.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e4554f-32d3-6166-0fb4-f7382d063ef6
* Version Independent ID: de6a662e-0676-3e47-1321-5b6e14a54b14
* Content: [Create policies to control activities in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/user-activity-policies)
* Content Source: [CloudAppSecurityDocs/user-activity-policies.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/user-activity-policies.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@GiantCrocodile  Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks for the feedback regarding the asterisks. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@GiantCrocodile Thanks again for your feedback. After investigating, we've discovered that there isn't a specified time for how long it takes for activities to appear. Having said that, activity policies usually trigger in near real-time (or within a few minutes of an event), when the relevant activities become available to Cloud App Security.

**Comment by GiantCrocodile** [comment]
@shsagir I'm not sure we talk about the same: The policy was created and thus active. New activities were logged. Still, the policy wasn't triggered at that time. We suspect a policy is instantly activated but until it can be triggered, it takes some time (hours).
