### ISSUE TITLE
What does 'Last activity log' mean?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/CloudAppSecurityDocs#266]
Hello,

please add clarification on what the term 'Last activity log' means. This term is shown if you click on a connected app to get more details. E. g. if the date of 'Last activity log' is from yesterday, does it mean there is no new data or does it mean the connection between the app and Cloud App Security is somehow disturbed? This confuses me because

- Status of the connected App is green ('Connected') and
- 'Real-time scan status' is 'Up to date' and
- 'Last health check' is 'an hour ago'.

This looks fine to me but Office 365 and Azure are all time generating some kind of data so it's unlikely there's no new data to process.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cb69cd-d5d4-e058-e20f-d2697cfcd614
* Version Independent ID: bb8fbd63-532a-f8f9-6bc6-85eaf09ca171
* Content: [Connect apps to get visibility and control - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/enable-instant-visibility-protection-and-governance-actions-for-your-apps#feedback)
* Content Source: [CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@GiantCrocodile Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@GiantCrocodile The following information from the product team may help you with your issue:

> The Last Activity field represents the date of the last activity received from the service. You can validate this by going to Office365 audit logs. If there are any gaps in activities for long periods of time we suggest opening a support case.

If you are still experiencing the issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672).

Because the topic documents general information about connecting apps and not specific details, a change is not required and we are closing this issue.

**Comment by GiantCrocodile** [comment]
Is that somewhere else described @shsagir? It might make sense to provide a description for those fields (as you can see with the other issue I did open with reference to other unclear meaning of fields) too.
