### ISSUE TITLE
CAS Activity Log Inaccurately Shows Teams Group Creator Removes Member from Group in hybrid environment

### ISSUE THREAD

**Issue by tlooper-w** [MicrosoftDocs/CloudAppSecurityDocs#267]
My testing with Microsoft has found that the CAS Activity Log will Inaccurately Show a Teams Group Creator as the User who Removed a Team Member from Group in hybrid environment when the member's account is disabled in AD

Steps to reproduce issue (all accounts are synced from on-prem AD to Azure and O365 via AD Connect):
1) Owner A creates new Team called 'Test'
2) Owner A adds user B to 'Test' Team
3) User B's account is terminated, account disabled.
4) Within 1-2 days CAS log will show a "MemberRemoved" activity with the User (who performed it) as Owner A

If multiple owners exist for a Team, only the creator will be named as the person who performed the removal. 

Problem: IT is looking at these logs and coming the conclusion that the CAS Logs are 100% accurate. When a user says they didn't remove a member from a Team, our logs say otherwise. This issue was found by noticing the members who were removed from the Teams were also disabled in AD about a day before the CAS logs entries showing the removal from the Team they were in.

Solution: Please update the CAS activity log to show that a member was removed from a Team due to AD changes.

**Comment by shsagir** [comment]
@name Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).
