### ISSUE TITLE
Add definition of account/user

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/CloudAppSecurityDocs#269]
Hello,

this page talks about accounts and users but it doesn't explain what's the difference. Please provide a definition on what an user is and what an account is and what's the difference. If the difference is described already somewhere else, provide a link to it.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec49198-bda6-5138-159f-f80ef187b9b0
* Version Independent ID: 62bb765d-10f1-f04b-d293-6184be709b02
* Content: [Visibility into cloud app accounts - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/accounts#feedback)
* Content Source: [CloudAppSecurityDocs/accounts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/accounts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@GiantCrocodile Thanks for your feedback. These terms are not specific to Cloud App Security and are shared in common with other Microsoft products. In general, an [account is an identity](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis#terminology) that has data associated with it, where identity can be a user, an application, or other types of accounts.

**Comment by GiantCrocodile** [comment]
Hi @shsagir! Thanks for your reply. According to my understanding/what I read, Cloud App Security is a standalone product thus a customer doesn't need to know about Office 365 or Azure so the customer shouldn't have to know terms of other Microsoft products without a clear mention about it in the docs of the product the customer bought?
