### ISSUE TITLE
Export of admin activities incomplete

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/CloudAppSecurityDocs#270]
Hello,

I did export the admin activities and it just contains activities of category `Log On` and `View`. I see no information about apps connected, alerts created/deleted, queries done, etc.

The docs state:

> Cloud App Security lets you export a log of all admin activities including auditing of an admin investigating a specific user or viewing specific alerts.

So is this a bug in the tenant or is the data which can be exported due to technical limitations quite limited? This must be clarified in the docs.

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@GiantCrocodile Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
