### ISSUE TITLE
List of admin access incomplete

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/CloudAppSecurityDocs#271]
Hello,

it should be stated that not just Office 365 or Azure AD users can have access and that it's possible to override their permissions but it should be also mentioned that the list of users with admin access is NOT containing Azure or Office 365 users. Thus the list is incomplete and not a 100 % reliable way to determine who has access.

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins#feedback)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@GiantCrocodile Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
