### ISSUE TITLE
Alert notification

### ISSUE THREAD

**Issue by jwkincaid** [MicrosoftDocs/CloudAppSecurityDocs#272]
If you set an alert for an action for 10 unsuccessful login attempts in a 2-minute if you have 10 unsuccessful logins in 1 minute do you get the alert after the 10th failed attempt or at the 2 minute mark? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e4554f-32d3-6166-0fb4-f7382d063ef6
* Version Independent ID: de6a662e-0676-3e47-1321-5b6e14a54b14
* Content: [Create policies to control activities in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/user-activity-policies#feedback)
* Content Source: [CloudAppSecurityDocs/user-activity-policies.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/user-activity-policies.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@jwkincaid Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@name Thanks again for taking the time to leave us your comment on our documentation. We received the following information from the product team:

> The alert is triggered as soon as the threshold is crossed. So if you set the threshold to 10 unsuccessful login attempts, the alert is triggered once 10 unsuccessful login attempts occur.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
