### ISSUE TITLE
File Reports not appearing in portal

### ISSUE THREAD

**Issue by pbbergs** [MicrosoftDocs/CloudAppSecurityDocs#274]
Is this still relevant?  These reports no longer appear to be available from this location.
![Missing Elipse](https://user-images.githubusercontent.com/18462615/82910378-308cc580-9f30-11ea-9806-86b28a237645.jpg)

**Comment by shsagir** [comment]
@pbbergs Thanks for your feedback. After investigating, we've discovered the reports menu is there and still relevant. Therefore, there are no fixes required for the documentation. But, thanks again; we always appreciate feedback on our documentation. If you are still cannot see the menu, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).
