### ISSUE TITLE
Broken link - error in redirection

### ISSUE THREAD

**Issue by gesmyrli** [MicrosoftDocs/CloudAppSecurityDocs#275]
In number 4 of the section "Apply labels directly to files" there is a link at the end that says "For more information about how Cloud App Security and Azure Information Protection work together, see [Protect data against user mistakes] (https://docs.microsoft.com/enterprise-mobility-security/solutions/protect-data-user-mistake)."

However, the link does not go to the actual article but to "https://docs.microsoft.com/enterprise-mobility-security"

Can you please correct this or provide with the working link for the link of [Protect data against user mistakes]

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Azure Information Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/azip-integration)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/azip-integration.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@gesmyrli Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
