### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by v-algran** [MicrosoftDocs/CloudAppSecurityDocs#277]
[Hi, If this document gets any type of update how can I be notified]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f1881c-1d0b-7a96-f8c1-3989b3b5e0cd
* Version Independent ID: b50ed5b9-18ab-abde-406e-b3fd1ff61fa2
* Content: [What is Cloud App Security?](https://docs.microsoft.com/en-us/cloud-app-security/what-is-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/what-is-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/what-is-cloud-app-security.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@v-algran Thank you for your question. Unfortunately, there isn't a mechanism for receiving notifications of content updates.
