### ISSUE TITLE
Page Looks Nothing Like Security Portal

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/CloudAppSecurityDocs#278]
My Security and Compliance Page and these instructions do not match what I see in the portal at https://protection.office.com/

Is there an update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by GiantCrocodile** [comment]
I think you followed to the wrong URL. Right URL: https://security.microsoft.com/homepage

**Comment by shsagir** [comment]
@VNJoe Thanks for your feedback. @GiantCrocodile is correct regarding the URL to use. We've added the URL and updated the Microsoft 365 Admin Center image and submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
