### ISSUE TITLE
Cloud App Security Documentation not current

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/CloudAppSecurityDocs#279]
https://docs.microsoft.com/en-us/cloud-app-security/

None of the above document seems applicable any longer.  The Quick Start Guide doesn't match, and neither does Basic Setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47cc4f8f-f7d2-07ce-4fb2-4e87eef26655
* Version Independent ID: 33d5a394-9e8b-2db5-6a8b-ec6219463b30
* Content: [Set up your organization's settings in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/general-setup)
* Content Source: [CloudAppSecurityDocs/general-setup.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/general-setup.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@VNJoe Thanks for your feedback. Please can you provide a little more detail on the issue you raised? Which information do you feel is no longer applicable. Thanks.

**Comment by VNJoe** [comment]
Step 1

    From the settings cog, select App connectors.
    Click the plus sign to add an app and select an app.
    Follow the configuration steps to connect the app.

![image](https://user-images.githubusercontent.com/49563744/83975903-62087800-a8c4-11ea-8946-f971cd1d4e6b.png)

Nope.

**Comment by VNJoe** [comment]
Previously, clicking Security took me to Protection instead of the Security 9 days ago when I opened this issue.  This looks like that piece is resolved, now its just the rest of it.

**Comment by shsagir** [comment]
@VNJoe Thanks for your feedback. After investigating the option in a few tenants, we've discovered the option is still there. Therefore, no change is required to the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.

As we understand it, you're describing a problem with your environment and not with the product documentation. To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).

**Comment by VNJoe** [comment]
What are you talking about? Show me that its there, otherwise keep the ticket open.  You've not shown what it should look like, but I'm showing you that it isn't there.
