### ISSUE TITLE
Discovered app security breach - policy not listed in documentation

### ISSUE THREAD

**Issue by secondsunrise** [MicrosoftDocs/CloudAppSecurityDocs#280]
The policy "**Discovered app security breach**" is not listed in the CAS [Policy template reference ](https://docs.microsoft.com/en-us/cloud-app-security/policy-template-reference) documentation. See example alert screenshot below:

![image](https://user-images.githubusercontent.com/17801234/83580985-c9a47900-a4fa-11ea-948c-2f6f0ad657ac.png)

It also does not appear in the list of policies under **Control** -> **Policies**. See screenshot below:

![image](https://user-images.githubusercontent.com/17801234/83581177-4e8f9280-a4fb-11ea-9ffd-6cdfcb4c2f5e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0192fe47-4af3-0a7b-74a1-efbe7ad7536a
* Version Independent ID: 34ff03e6-aadf-638d-1b9f-30b999b19240
* Content: [Policy template reference for Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/policy-template-reference)
* Content Source: [CloudAppSecurityDocs/policy-template-reference.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/policy-template-reference.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@secondsunrise Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@secondsunrise Thanks for contacting Microsoft about your issue. We received the following information from the product team that you may find useful:

> The **Discovered app security breach** is not a policy template and is not visible in the policies list as it is a built-in, out-of-the-box alert generated when a discovered app with a breach has been detected in the past 90 days. It is based on continuous updates of our app catalog and helps customers to stay aware of breaches for apps used in their org.

Since this detection is not a policy template and not visible in the list of policies, there is no change required to the documentation; hence, we are closing the issue. Thanks again for the feedback.
