### ISSUE TITLE
Unnecessary hyperlinked text 

### ISSUE THREAD

**Issue by secondsunrise** [MicrosoftDocs/CloudAppSecurityDocs#284]
A large swathe of the page starting at [Tag apps as sanctioned or unsanctioned](https://docs.microsoft.com/en-us/cloud-app-security/investigate#tag-apps-as-sanctioned-or-unsanctioned) has unnecessary hyperlinked text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bfee6e2-2879-2e43-0a8a-d3167762d6ee
* Version Independent ID: f5f6ae9a-b605-dc4d-7be6-335f47e101d5
* Content: [Investigate cloud app risks & suspicious activity - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/investigate)
* Content Source: [CloudAppSecurityDocs/investigate.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/investigate.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@secondsunrise Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
