### ISSUE TITLE
Allow additional Roles ability to enroll in notifications

### ISSUE THREAD

**Issue by ab-aayers** [MicrosoftDocs/CloudAppSecurityDocs#285]
Currently - as i understand it - only ADMIN roles are entitled to enrollment into notifications as instructed [here](https://docs.microsoft.com/en-us/cloud-app-security/admin-settings). 
However it would be massively beneficial for "Security Operator" role.  As one with this role would be expected to be made aware and "operate" on the alert/incident.  The only alternative i am aware of would be to change the default settings on 60+ policies that are in place to include a group email.
I would even make the case that security operators should be auto-enrolled.  
[This feedback would be a follow-up to this closed issue.](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/125)
Current behavior when an operator tries to enroll is
![insuff](https://user-images.githubusercontent.com/47149062/83688612-ae4d7280-a5bb-11ea-9bdc-0e154a87005b.png)

**Comment by shsagir** [comment]
@ab-aayers Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).
