### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#286]
[Enter feedback here]

On one page we are told that it important to create a snapshot report before a continuous report and then at the bottom of the https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker page we are told that the next step is to create a snapshot report, this puts us into a loop.
Please clarify the sequential steps  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e0555c-41e5-0ba3-4c4b-f9c386644a72
* Version Independent ID: 876888bc-8046-0a25-a0b7-67f938cc45c1
* Content: [Configure automatic log upload for continuous reports in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker)
* Content Source: [CloudAppSecurityDocs/discovery-docker.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. Please can you provide a little more detail on the issue you raised? Which topic tells you that it is important to create a snapshot report before a continuous report? Thanks

**Comment by DeanGross** [comment]
this is the page i was referring to https://docs.microsoft.com/en-us/cloud-app-security/create-snapshot-cloud-discovery-reports

**Comment by shsagir** [comment]
@DeanGross Thanks for the additional information. We've submitted a documentation change to remove the next step in this article based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
