### ISSUE TITLE
Discovered App tags are not returned via API query

### ISSUE THREAD

**Issue by jgange** [MicrosoftDocs/CloudAppSecurityDocs#287]
[Enter feedback here]
I am attempting to pull down a list of Discovered Apps that have a tag value of None using the API but the results are coming from the Cloud App catalog instead of the Discovered apps. Could someone provide the API URL to use to obtain the Discovered App and their associated tags?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c267437-ac0d-3c6c-6ba0-9fc75bd20311
* Version Independent ID: 04d1f2c0-fe67-59b0-d4c3-97598f76a52a
* Content: [Cloud App Security discovered app filters and queries](https://docs.microsoft.com/en-us/cloud-app-security/discovered-app-queries)
* Content Source: [CloudAppSecurityDocs/discovered-app-queries.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovered-app-queries.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@jgange Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).
