### ISSUE TITLE
Cloud App Security features

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/CloudAppSecurityDocs#289]
I read the licensing guide on this. Thanks, that explains a lot already, but since you are using the word "subset" so often, an overall table  of versions, features and licenses would be great. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a66643-56f5-dc00-5af6-3ee1d9b6f090
* Version Independent ID: c319c4a4-974e-7e3a-d58a-76fd57a9efe9
* Content: [Differences between Cloud App Security and Office 365 Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-o365.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-o365.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@BakkerJan Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
