### ISSUE TITLE
Azure AD Cloud App Discovery deprecated?

### ISSUE THREAD

**Issue by cnadler-MSFT** [MicrosoftDocs/CloudAppSecurityDocs#291]
The following link redirects to MCAS:

https://docs.microsoft.com/en-us/previous-versions/azure/azure-services/mt143581(v=azure.100)?redirectedfrom=MSDN

and when clicking on the Azure AD Cloud App Discovery within this page, it redirects to MCAS documentation.  I tried adding the Azure AD Cloud App Discovery app from the marketplace and receive an error that something went wrong while creating Azure AD Cloud App Discovery even though the tenant is licensed for AAD P2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401b0903-938e-9739-49eb-4c28ef10bcfc
* Version Independent ID: 89fc55de-a5eb-c398-4a53-5786f49349f2
* Content: [Discovery capability differences for Cloud App Security and Azure AD](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-aad)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-aad.md)
* Service: **cloud-app-security**
* Product: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@name Thanks for contacting Microsoft about your issue. Regarding the documentation query, the Azure AD Cloud App Discovery link takes you to the Cloud App Security Cloud Discovery setup page where you can find instructions for the shared setup experience.

However, regarding the app issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).
