### ISSUE TITLE
stunnel

### ISSUE THREAD

**Issue by cnadler-MSFT** [MicrosoftDocs/CloudAppSecurityDocs#292]
I think it's appropriate to remove the phrase "stunnel" from our documentation as SSL itself is deprecated and no longer used.  TLS is the standard and we should avoid using inaccurate terminology.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7311538-fd31-674c-7fb1-430eb07406fe
* Version Independent ID: ab868458-d2b4-57bb-14b6-b44fd6a3f958
* Content: [Cloud App Security external DLP integration over secure ICAP](https://docs.microsoft.com/en-us/cloud-app-security/icap-stunnel)
* Content Source: [CloudAppSecurityDocs/icap-stunnel.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/icap-stunnel.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@cnadler-MSFT Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. Relevant changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
