### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/CloudAppSecurityDocs#294]
In the Malware Detection section and Note box the text reads

Cloud App Security supports malware detection the following apps:

I believe it should read 

Cloud App Security supports malware detection in the following apps:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395e085f-93bd-1f3c-fe0d-7711b6d51950
* Version Independent ID: ad86d15d-41a5-9a6e-8d30-18ed9a9975f2
* Content: [Create anomaly detection policies in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/anomaly-detection-policy#malware-detection)
* Content Source: [CloudAppSecurityDocs/anomaly-detection-policy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/anomaly-detection-policy.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@pjrcdf Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
