### ISSUE TITLE
What are the possible Error codes returned by cloud discovery APIs?

### ISSUE THREAD

**Issue by jigneshpatel2208** [MicrosoftDocs/CloudAppSecurityDocs#295]
Currently, it's not documented the possible error codes returned in different situations by the APIs of cloud discovery (3 APIs: initiate file upload, actual file upload, and final notification after upload).

Can you please provide the details about error codes so that it's easier for developers to handle all the possible errors gracefully?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5890e4d5-9362-7eff-cdce-552cb8e62a0b
* Version Independent ID: cc68c1d6-acc7-365e-63c1-66c9a5203669
* Content: [Cloud App Security Cloud Discovery API](https://docs.microsoft.com/en-us/cloud-app-security/api-discovery)
* Content Source: [CloudAppSecurityDocs/api-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-discovery.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@jigneshpatel2208 Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by shsagir** [comment]
@jigneshpatel2208 Thanks again for your suggestion. I received the following information from the product team which you may find useful:

> Generally speaking, there are a few status codes that apply to all endpoints:
> 200 - OK
> 400 - Bad Request (Client Error)
> 404 - Not Found
> 429 - Too Many Requests
> 500 - Internal Server Error
