### ISSUE TITLE
This is not applicable. 

### ISSUE THREAD

**Issue by leifdavisson** [MicrosoftDocs/CloudAppSecurityDocs#296]
I have a admin account without a license for managing Cloud Security. We are not allow to use a privelgded account as our daily account. Nothing on the Getting started page match what I see in the cloud app security. 
I have a screen shot but I can't attach it to this ticket. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@leifdavisson Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with using the product itself and not with the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).
