### ISSUE TITLE
Juniper SRX logs

### ISSUE THREAD

**Issue by aqyx** [MicrosoftDocs/CloudAppSecurityDocs#297]
Juniper SRX is listed as supported, but is that only for logs based on RT_FLOW_SESSION_CLOSE? We have a client that wants to use both snapshots and continuous reports, but their Juniper SRX logs will not parse, presumably because they log based on RT_FLOW_SESSION_CREATE.

I can provide an anonymised log if required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2005aabb-11c8-3ab9-6e87-94b0ef5164be
* Version Independent ID: 0878ecbe-fcd1-eb38-8ddb-4b4ea685d3c0
* Content: [Deploy Cloud Discovery - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/set-up-cloud-discovery#supported-firewalls-and-proxies)
* Content Source: [CloudAppSecurityDocs/set-up-cloud-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/set-up-cloud-discovery.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@aqyx Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

In general, if your log isn't supported you can define a custom parser that matches your format. For more information, see [Use a custom log parser](https://docs.microsoft.com/cloud-app-security/custom-log-parser).

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).

**Comment by aqyx** [comment]
I was raising an issue with the documentation, as it clearly says that Juniper SRX logs are supported and I have Juniper SRX logs that won't parse, so maybe some clarification in the documentation would be beneficial.
