### ISSUE TITLE
API Authorization using Token is not working as expected

### ISSUE THREAD

**Issue by jigneshpatel2208** [MicrosoftDocs/CloudAppSecurityDocs#298]
I've written a script to upload my traffic log files to MCAS for cloud application discovery. I'm using the authorization mechanism as mentioned in the documentation under "API documentation"  in my tenant and it's working perfectly fine.

The problem is that when I accidentally change my API token to invalid one (by mistake I replaced the first few characters) and still it works perfectly. All the discovery related APIs return 2xx status code and my files are still being uploaded on MCAS.

I haven't seen such behaviors in any other APIs (this assumption can be wrong as MCAS can have a totally different API mechanism). Therefore, is this behavior expected? And if yes, what's the mechanism of authentication?

I've also found another issue in the URL required by these APIs. It can be found here on Microsoft Tech Community: https://techcommunity.microsoft.com/t5/microsoft-cloud-app-security/mcas-apis-works-even-without-portal-and-region-name-in-url-s/m-p/1486081 without any responses.

Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14be08b-ad47-f8a4-3368-8bbfaa5723bf
* Version Independent ID: 962f3f55-b16b-4a50-9f93-b09f8219a8be
* Content: [API token management in Cloud App Security](https://docs.microsoft.com/en-gb/cloud-app-security/api-authentication)
* Content Source: [CloudAppSecurityDocs/api-authentication.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-authentication.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@jigneshpatel2208 Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product API and not with the product documentation. We have passed on your feedback to the product team.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
