### ISSUE TITLE
private activities definitions

### ISSUE THREAD

**Issue by StarkCaptain** [MicrosoftDocs/CloudAppSecurityDocs#299]
[Enter feedback here]
Can you provide more details on what private activities are compromised of. A list would be great. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af3206d1-a6f4-3cf6-5172-2e3dbbef6778
* Version Independent ID: bfb6fab6-fbf8-36f5-5d36-742babde0ada
* Content: [Scope your Microsoft Cloud App Security deployment](https://docs.microsoft.com/en-us/cloud-app-security/activity-privacy)
* Content Source: [CloudAppSecurityDocs/activity-privacy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/activity-privacy.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@StarkCaptain Thanks for your question.

The focus of the feature is to allow you to specify groups of users, not specific activities, who's activities you want to keep private to comply with your organization's policies. When viewing the activity logs, activities for these users will not appear by default. To view these activities, for example as part of an investigation, authorized admins have the option to choose to view these private activities, with each instance being audited in the governance log.

Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
