### ISSUE TITLE
MCAS with MSFT Defender ATP - information is not clear.

### ISSUE THREAD

**Issue by ceperezb** [MicrosoftDocs/CloudAppSecurityDocs#300]
In the first paragraph is states, “Microsoft Cloud App Security integrates with Microsoft Defender Advanced Threat Protection (ATP) natively. The integration simplifies roll out of Cloud Discovery, extends Cloud Discovery capabilities **beyond your corporate network**, and enables machine-based investigation.”

But then the 2nd paragraph says, “Cloud App Security uses the traffic information collected by Microsoft Defender ATP about the cloud apps and services being accessed from IT-managed Windows 10 machines. The native integration enables you to run Cloud Discovery on any machine **in the corporate network**, using public Wi-Fi, while roaming, and over remote access. It also enables machine-based investigation.”

In on instance it speaks of integration beyond the corporate network, in the second instance it speaks of integration with machines in the corporate network.  Which is it? If the text, as written, is correct, then please explain or clarify the distinction – as a learner, it is not clear to me.

Thanks,
Cecilia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b2133d-85b3-8e2c-c89a-7d83f48e5dd0
* Version Independent ID: 84598ed0-a8ea-5504-2b87-b20df2347e53
* Content: [Integrate Microsoft Defender ATP with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/wdatp-integration)
* Content Source: [CloudAppSecurityDocs/wdatp-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/wdatp-integration.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@ceperezb Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@ceperezb Thanks again for your feedback. After investigating, we've discovered both are correct. The 2nd paragraph lists all the options, of which **in** the corporate network is one option. The list also includes public Wi-Fi and roaming that are **beyond** the corp network. We hope that clarifies the issue for you.
