### ISSUE TITLE
Missing App Connector menu item

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#301]
[Enter feedback here]

How come a Global Admin at a company with an EM+S E3 license does not see the App Connector menu item on the Settings cog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for contacting Microsoft about your issue. As we understand it, you're describing a problem with the product itself and not with the product documentation.

You may find licensing information on the [licensing datasheet](https://aka.ms/mcaslicensing).

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).

**Comment by DeanGross** [comment]
Sorry, you misunderstand my request. If the menu item is dependent on a license, then the documentation should state this in order to eliminate confusion. There is nothing on this page the identifies any licensing prerequisites.
