### ISSUE TITLE
Getting started with Office 365 CAS

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#302]
[Enter feedback here]

Please provide a similar page for getting started with the O365 CAS license
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by DeanGross** [comment]
Please don't close this until the changes have been implemented
