### ISSUE TITLE
Applies to Information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#303]
[Enter feedback here]
Please update the pages to clearly call out the pages that apply to O365 CAS. Every page states that it applies to MCAS, none of them mention O365 CAS.
This is the only page that discuses the differences and its very easy to read the other documentation and mistakenly think that it can be done with an O365 CAS license

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a66643-56f5-dc00-5af6-3ee1d9b6f090
* Version Independent ID: c319c4a4-974e-7e3a-d58a-76fd57a9efe9
* Content: [Differences between Cloud App Security and Office 365 Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-o365.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-o365.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

You may find the following of interest:

- [What are the differences between Microsoft Cloud App Security and Office 365 Cloud App Security?](https://docs.microsoft.com/cloud-app-security/editions-cloud-app-security-o365)
- [Microsoft Cloud App Security licensing datasheet](https://aka.ms/mcaslicensing)

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by DeanGross** [comment]
Thanks, I am aware of those documents, my point is that at the top of each page is shown, "Applies to" and all of the pages show Microsoft Cloud App Security, and none of them show "Office 365 Cloud App Security" it would be helpful to explicitly identify the pages that apply to both licenses and to identify which pages only apply to the more expensive and comprehensive version
