### ISSUE TITLE
Construction of the PK is not documented properly

### ISSUE THREAD

**Issue by Arsenikr** [MicrosoftDocs/CloudAppSecurityDocs#304]
nowhere in the docs it is stated how to construct the PK.
i needed to guess that you need to take the three unique identifiers, for example `{ "id": "3fa9f28b-eb0e-463a-ba7b-8089fe9991e2", "saas": 11161, "inst": 0 }`, convert it to Base64 and this is the PK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7657b281-d954-0e3e-ce7f-fd34561fe0ec
* Version Independent ID: 0ca147b2-b7c9-0004-550e-0756f9027177
* Content: [Fetch - Entities API](https://docs.microsoft.com/en-us/cloud-app-security/api-entities-fetch)
* Content Source: [CloudAppSecurityDocs/api-entities-fetch.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-entities-fetch.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Arsenikr Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@Arsenikr Thanks again for taking the time to leave us your comment on our documentation. The process you described is correct and an update to the page based on your suggestions will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by Arsenikr** [comment]
@shsagir btw can you connect me to someone from the technical side? I have some questions about the API
