### ISSUE TITLE
MCAS integration with intune and sharepoint

### ISSUE THREAD

**Issue by Afsars12** [MicrosoftDocs/CloudAppSecurityDocs#306]
Hello All,

Kindly advice the steps to integrate MCAS with sharepoint and intune.

**Comment by shsagir** [comment]
@Afsars12 Thanks for contacting Microsoft about your issue. As we understand it, you're looking for assistance with the product itself and not with the product documentation.

You may find the following information useful:

- To integrate SharePoint: [Connect Office 365 to Microsoft Cloud App Security](https://docs.microsoft.com/cloud-app-security/connect-office-365-to-microsoft-cloud-app-security)
- Integration with Microsoft Intune: This is automatic and does not require any specific Cloud App Security configuration, but og course you do need to configure Intune itself :-)

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).

**Comment by Afsars12** [comment]
Thanks for the reply Shlomo.

I am clear about SharePoint now, However, you have mentioned we need configure intune itself for the integration. Please provide some reference Microsoft links. Thank you again

**Comment by Afsars12** [comment]
Hi Shlomo,

For Intune, You have mentioned it is automatic, can I get some reference links which talks about the same.
