### ISSUE TITLE
Needs Updating

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/CloudAppSecurityDocs#307]
Based on my current tenant the following policy templates no longer exist

- General anomaly detection
- User log on from a non-categorized IP address

And the following templates exist but arent listed

- Block upload of potential malware (based on Microsoft Threat Intelligence)
- Block download of potential malware (based on Microsoft Threat Intelligence)
- Block download based on real-time content inspection
- Block upload based on real-time content inspection
- Block cut/copy and paste based on real-time content inspection
- Access level change (Teams)
- Log on from an outdated browser
- Monitor all activities
- Activities from suspicious user agents
- External user added (Teams)
- Mass deletion (Teams)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0192fe47-4af3-0a7b-74a1-efbe7ad7536a
* Version Independent ID: 34ff03e6-aadf-638d-1b9f-30b999b19240
* Content: [Policy template reference for Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/policy-template-reference)
* Content Source: [CloudAppSecurityDocs/policy-template-reference.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/policy-template-reference.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@pjrcdf Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
