### ISSUE TITLE
CAS Integration with Workday vs using App Based Conditional Acces

### ISSUE THREAD

**Issue by jenujose** [MicrosoftDocs/CloudAppSecurityDocs#310]
What's not clear from the documentation is what additional visibility do you get if you configure CAS integration with workday vs using Conditional Access App Control.

In the documentation, the workday - CASB integration provides user activity monitoring. Can't you get the same thing if Workday is configured using Conditional Access App Control and you proxy all user logins to Workday?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff54b0ff-3248-d548-0f50-27add7282c3d
* Version Independent ID: 738b65bc-66df-0c37-88a8-9ec592c1ac21
* Content: [Connect Workday to Cloud App Security (Preview)](https://docs.microsoft.com/en-us/cloud-app-security/connect-workday-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-workday-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-workday-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@jenujose  Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@jenujose In general, API connectors give you visibility into all your users and their activities. You can use this information to follow up on suspicious activities to take appropriate action such as notifying the user or suspending them.

In contrast, you can use Conditional Access App Control to monitor/block activities in real time.

To follow up on this issue, leave us a comment with an @mention.
