### ISSUE TITLE
Clarity needed on  Office 365 E5 license requirement

### ISSUE THREAD

**Issue by turnma** [MicrosoftDocs/CloudAppSecurityDocs#312]
There's mention that using the features 365 apps requires an Office 365 E5 license. Since MCAS is also part of Microsoft 365 E5 Compliance it would be useful if this article could clarify if this other licence also meets this requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect with Microsoft Cloud App Security Conditional Access App Control](https://docs.microsoft.com/en-us/cloud-app-security/proxy-intro-aad)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@turnma Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@turnma Thanks for your feedback. Licensing information is available using the link to the licensing datasheet on the [Overview page](https://docs.microsoft.com/cloud-app-security/what-is-cloud-app-security).

**Comment by turnma** [comment]
Sorry, but I think the point has been missed here.  The page specifically mentions that an **Office** 365 E5 licence is needed:
"To use these apps with Cloud App Security, you must have an Office 365 E5 license"
The solution given here is that licensing is covered in another document, but if that's the case then you shouldn't mention the 365 E5 licence EITHER.  As it is, the page is **incorrect**.  It says that an Office 365 E5 licence is **needed**, but a Microsoft 365 E5 would also cover it, and quite possibly a Microsoft 365 E5 Compliance licence etc.  The page either needs to have an accurate and current reflection of licence requirements OR it should leave licensing in its entirety to the separate document.
