### ISSUE TITLE
Updated ServiceNow version support

### ISSUE THREAD

**Issue by cybermegan** [MicrosoftDocs/CloudAppSecurityDocs#314]
This page hasn't been updated for a while - does CAS support connecting to Orlando, the latest version of ServiceNow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148367a2-1d5d-a348-e34a-ee5c9e8157dd
* Version Independent ID: 3dee7652-6b47-4523-a530-9b69257950fc
* Content: [Connect ServiceNow to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-servicenow-to-microsoft-cloud-app-security#feedback)
* Content Source: [CloudAppSecurityDocs/connect-servicenow-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-servicenow-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@cybermegan Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@cybermegan  Thanks again for your feedback. The product team has advised that Orlando is not currently supported but that it is in the request queue should be available in the coming months.

To get assistance further assistance on this issue, please open a support ticket or Send feedback.
