### ISSUE TITLE
Request body not honored

### ISSUE THREAD

**Issue by safari137** [MicrosoftDocs/CloudAppSecurityDocs#318]
Whether I use curl or Postman the API does not seem to honor anything I put in the body.  It does not filter or limit the results returned.  Is this expected behavior?  Or am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e8cef3-b884-a61b-2784-e7cbffc262a6
* Version Independent ID: 380b9051-bb14-69b2-95bc-7100071359aa
* Content: [List - Activities API](https://docs.microsoft.com/en-us/cloud-app-security/api-activities-list)
* Content Source: [CloudAppSecurityDocs/api-activities-list.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-activities-list.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by safari137** [comment]
I've tried this with many different properties in the body, but here's the simplest.  It still returns 100 results.

POST: https://{instance}.us.portal.cloudappsecurity.com/api/v1/activities
(content-type: application/json)
```
{
    "limit": 1    
}
```

**Comment by ms-smithch** [comment]
@safari137 close the URI path ... /activities/

**Comment by safari137** [comment]
@ms-smithch  that works as I expect, thank you!

**Comment by shsagir** [comment]
@ms-smithch Thanks for taking the time to assist @safari137 with their question.
