### ISSUE TITLE
Include JSON formatted doc for ease of access

### ISSUE THREAD

**Issue by ms-smithch** [MicrosoftDocs/CloudAppSecurityDocs#319]
Network administrators need something readily accessible and able to be easily retrieved to update their ACLs/Whitelists/Firewalls. A Json document containing service information by service type and datacenter would satisfy this requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96223442-ff3d-c101-214f-2240ac42d53b
* Version Independent ID: 56fead2d-d0ba-ce69-e931-5b91ed43c736
* Content: [Network requirements - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/network-requirements)
* Content Source: [CloudAppSecurityDocs/network-requirements.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/network-requirements.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@ms-smithch Thanks so much for taking the time to leave us your comment on our documentation. We're looking into adding this feature though it may take a while. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
