### ISSUE TITLE
Poor Documentation

### ISSUE THREAD

**Issue by jitheshr** [MicrosoftDocs/CloudAppSecurityDocs#320]
The docuementation on connecting a 3rd party IDP is really poor. There are no examples of even connecting ADFS ( Microsoft IDP ) samples. Once you select ADFS and connect, it is grayed out and cannot be used again. This blocks other apps that are connected to ADFS.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18085b0-ca97-5623-fc42-5395acf55f1f
* Version Independent ID: 942d682c-a471-a8c9-e12f-cc7d4aafbad3
* Content: [Support and troubleshooting information for Cloud App Security](https://docs.microsoft.com/en-gb/cloud-app-security/support-and-ts#feedback)
* Content Source: [CloudAppSecurityDocs/support-and-ts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/support-and-ts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@jitheshr Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@jitheshr  Thanks again for taking the time to leave us your comment on our documentation. We're are already in the process of researching examples to add the page will be updated in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
