### ISSUE TITLE
G Suite - step 12 does not match current G Suite UI

### ISSUE THREAD

**Issue by cronq** [MicrosoftDocs/CloudAppSecurityDocs#321]
Please G Suite integration documentation to match the current google UIs:

- Steps 12 c-f do not match the current UI in admin.google.com
- Step 18 - the UI has changed on this as well. Looks like everything is under 'Store Listing' now.

**Comment by shsagir** [comment]
@cronq  Thanks so much for taking the time to leave us your comment on our documentation. We're already researching this issue to update the page. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
