### ISSUE TITLE
Include status commands for docker containers

### ISSUE THREAD

**Issue by ms-smithch** [MicrosoftDocs/CloudAppSecurityDocs#323]
Common troubleshooting task for log collectors is to use the collector_status -p  command to view the current status of the collector. Currently this is not documented within the documentation for any of the container documents.

CloudAppSecurityDocs/discovery-docker-ubuntu.md
CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md
CloudAppSecurityDocs/discovery-docker-windows.md

**Comment by shsagir** [comment]
@ms-smithch  Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by shsagir** [comment]
@ms-smithch Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
