### ISSUE TITLE
Reference to AWS in the Google Cloud Platform Guide

### ISSUE THREAD

**Issue by NigelColtellaIT** [MicrosoftDocs/CloudAppSecurityDocs#325]
Incorrect reference to AWS here: "Follow these steps to connect AWS Security auditing to Cloud App Security."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c93906-0f8a-a2d6-c542-d80ee38f9c75
* Version Independent ID: 1e647883-2470-ee9a-2f6b-c2172f7f190d
* Content: [Connect Google Cloud Platform to Cloud App Security](https://docs.microsoft.com/en-gb/cloud-app-security/connect-google-gcp-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-google-gcp-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-google-gcp-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@NigelColtellaIT Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
