### ISSUE TITLE
182 Release Notes Missing

### ISSUE THREAD

**Issue by brettaweston** [MicrosoftDocs/CloudAppSecurityDocs#326]
Our deployment shows version 182 but no release notes have been posted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee159bf-1044-a912-9920-288ac4e62050
* Version Independent ID: 5f8063d7-034b-e708-685f-396659fa59d0
* Content: [What's new in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/release-notes)
* Content Source: [CloudAppSecurityDocs/release-notes.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/release-notes.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@brettaweston Thanks for your feedback. Occasionally, multiple releases are consolidated in the release notes. On this occasion, 182 release notes will be consolidated with 183. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
