### ISSUE TITLE
Office 365 Cloud App Security link

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/CloudAppSecurityDocs#327]
There is a Note at the top of this page that claims to take you to more info about Office 365 Cloud App Security, but it just redirects to the following page, which doesn't mention Office at all and just has a couple of references to M365.
https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security

The same issue occurs with the very first link at the top of the page below ("For information about Office 365 Cloud App Security, see Get started with Office 365 Cloud App Security.").
https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365

If there has been a rename and the original links are gone, please reconsider how this is called out in the current docs. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f1881c-1d0b-7a96-f8c1-3989b3b5e0cd
* Version Independent ID: b50ed5b9-18ab-abde-406e-b3fd1ff61fa2
* Content: [What is Cloud App Security?](https://docs.microsoft.com/en-us/cloud-app-security/what-is-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/what-is-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/what-is-cloud-app-security.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@dcbrown16  Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.
