### ISSUE TITLE
cloud add discovery - log ingestion. charges 

### ISSUE THREAD

**Issue by eSnlalan** [MicrosoftDocs/CloudAppSecurityDocs#328]
Please add a section if the customer is uploading TB of logs for cloud app discovery, are you offering it free or charging them ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465291ec-a6ff-9446-1a30-89cfc05d2e74
* Version Independent ID: 28256a68-04c7-81d4-054d-711264c9e5e1
* Content: [Control cloud app usage by creating policies - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/control-cloud-apps-with-policies)
* Content Source: [CloudAppSecurityDocs/control-cloud-apps-with-policies.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/control-cloud-apps-with-policies.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@eSnlalan Thanks for contacting Microsoft about your issue. As we understand it, you're describing a question about costings and not about the product documentation.

To get assistance or support for your product issue, please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com).
