### ISSUE TITLE
Client certificates are prompting at every login

### ISSUE THREAD

**Issue by ngraebe** [MicrosoftDocs/CloudAppSecurityDocs#331]
Hi all,

In the documentation under Client certificates are prompting at every login a wrong way is described. The setting must be made in the Internet zone settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786477c5-9588-bef4-d273-f53446b151c7
* Version Independent ID: 73f6ee70-27a3-d972-f14c-1bd30e59c17c
* Content: [Troubleshooting access and session controls](https://docs.microsoft.com/en-us/cloud-app-security/troubleshooting-proxy#client-certificates-are-prompting-at-every-login)
* Content Source: [CloudAppSecurityDocs/troubleshooting-proxy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/troubleshooting-proxy.md)
* Service: **cloud-app-security**
* Product: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@ngraebe Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by shsagir** [comment]
@ngraebe Thanks again for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
