### ISSUE TITLE
Please explain Outdated operating system and browser

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/CloudAppSecurityDocs#332]
I cannot find any documentation on this. Can you explain when an os or browser is marked as outdated?

**Comment by shsagir** [comment]
@BakkerJan Thanks for your feedback. Please can you provide a little more detail on the issue you raised? Which documentation page are you referring to? Thx

**Comment by shsagir** [comment]
@BakkerJan Thanks again for your enquiry. I received the following information from the product team:

> Outdated browsers include Apple Safari version 9.1 or lower and IE 11 or lower.

Since there is no documentation change, I am closing this issue. If you determine another possible update to our documentation, please don’t hesitate to reach out again.
