### ISSUE TITLE
Clarity around Administrator roles

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/CloudAppSecurityDocs#336]
Reading the article, it's not clear whether the roles under the Manage Admin Access page affect permissions outside of MCAS. There's a note stating "Office 365 and Azure AD roles do are not listed in the Manage admin access page" but then the article also states "Additionally, the following Cloud App Security specific admin roles can be configured in the Cloud App Security portal:" which makes it sound like only those four roles are Cloud App Security specific, and the other roles are not specific to Cloud App Security. 

For example, does granting a user Compliance Administrator in the Cloud App Security portal make them a Compliance Administrator outside of the MCAS portal, or does that give a user Compliance-Administrator-like permissions only in the MCAS portal? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@terrogin Thanks for your question.

The first group of roles lists **actual** Office 365 and Azure AD roles that have **access** to Cloud App Security. So they certainly have permissions outside Cloud App Security as defined by those products.

- Global administrator and Security administrator
- Compliance administrator
- Compliance data administrator
- Security operator
- Security reader
- Global reader

The second group of roles lists roles **defined by** Cloud App Security specific roles and **do not** have permissions outside Cloud App Security.

- App/instance admin
- User group admin
- Cloud Discovery global admin
- Cloud Discovery report admin

We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. 
Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
