### ISSUE TITLE
The caption of this page is misleading 

### ISSUE THREAD

**Issue by Alrudin** [MicrosoftDocs/CloudAppSecurityDocs#337]
Caption is misleading there is no actual configuration information on the page. This information is in the equally misleading Docker on Windows section. If the captions was "On prem Log Collector" and "Windows Docker Log Collector" respectively he documentation would be MUCH improved and information easier to get at when using the documentation.

Brgds
Johan Møller

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e0555c-41e5-0ba3-4c4b-f9c386644a72
* Version Independent ID: 876888bc-8046-0a25-a0b7-67f938cc45c1
* Content: [Configure automatic log upload for continuous reports in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker)
* Content Source: [CloudAppSecurityDocs/discovery-docker.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@Alrudin Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
