### ISSUE TITLE
Outdated document: Integration of Azure ATP not provided 

### ISSUE THREAD

**Issue by kumarM6** [MicrosoftDocs/CloudAppSecurityDocs#338]
The document is outdated as settings page is not upto date. I am looking for integration of Azure ATP with Cloud app security.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18085b0-ca97-5623-fc42-5395acf55f1f
* Version Independent ID: 942d682c-a471-a8c9-e12f-cc7d4aafbad3
* Content: [Support and troubleshooting information for Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/support-and-ts#feedback)
* Content Source: [CloudAppSecurityDocs/support-and-ts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/support-and-ts.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@kumarM6 Thanks so much for taking the time to leave us your comment on our documentation. We're currently in the process of rebranding as indicated at the top of the article. For Azure ATP, the new name is Microsoft Defender for Identity. The topics will be updated in the near future.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
