### ISSUE TITLE
Global reports only for CONTINUOS reports

### ISSUE THREAD

**Issue by t3chn1ck** [MicrosoftDocs/CloudAppSecurityDocs#339]
This information "The Global report consolidates all the information in the portal from all the data sources you included in your logs. The global report doesn't include data from Microsoft Defender ATP."

Should read "The Global report consolidates all the information in the portal from all the **continuous report** data sources you included in your logs. The global report doesn't include data from Microsoft Defender ATP."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fbda4c0-2222-b67a-615e-261fea7f3f05
* Version Independent ID: 13241ed3-46e9-5821-4760-4bdb9564c69e
* Content: [Working with discovered apps in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/discovered-apps)
* Content Source: [CloudAppSecurityDocs/discovered-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovered-apps.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@t3chn1ck Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
