### ISSUE TITLE
Donel Adams /Donadamassociates

### ISSUE THREAD

**Issue by donadam2015** [MicrosoftDocs/CloudAppSecurityDocs#342]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912d7335-dd1f-5b78-47ab-d685fe2d4805
* Version Independent ID: 4846530a-355a-4180-bf05-a504dc5d5a23
* Content: [How Cloud App Security helps protect your GitHub Enterprise environment](https://docs.microsoft.com/en-us/cloud-app-security/protect-github)
* Content Source: [CloudAppSecurityDocs/protect-github.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/protect-github.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@donadam2015 Thanks for your feedback. Please can you provide a little more detail on the issue you raised?

**Comment by shsagir** [comment]
@donadam2015 Thanks for your feedback. Since we haven't heard back from you, we are closing this issue. To follow up on this issue, leave us a comment with an @mention.
