### ISSUE TITLE
Activity Filters link should link to a different page.

### ISSUE THREAD

**Issue by lilianna-ashe** [MicrosoftDocs/CloudAppSecurityDocs#343]
The Activity Filters link on this page should link to https://docs.microsoft.com/en-us/cloud-app-security/api-alerts, not https://docs.microsoft.com/en-us/cloud-app-security/activity-filters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 858cd568-ed42-41a5-77fd-678f234b35e5
* Version Independent ID: c3dd41f4-c022-e482-433f-b272a0d3d55e
* Content: [Investigate activities using the API - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/investigate-activities-api)
* Content Source: [CloudAppSecurityDocs/investigate-activities-api.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/investigate-activities-api.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@lilianna-ashe Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
