### ISSUE TITLE
Too Long- last updated

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#347]
It would be helpful if the old content on this page could be moved to an archive page. Also, the top of the page shows a last update that is older than the most recent set of new announcements, this doesn't make any sense and should be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee159bf-1044-a912-9920-288ac4e62050
* Version Independent ID: 5f8063d7-034b-e708-685f-396659fa59d0
* Content: [What's new in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/release-notes)
* Content Source: [CloudAppSecurityDocs/release-notes.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/release-notes.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
