### ISSUE TITLE
Request for additional information - affect of overrides

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#349]
I'm not quite sure what exactly happens when the override checkboxes are selected. How does this affect policies and other features. Could you please provides some additional context and examples. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ef412a-b90e-dd0e-4d21-dfdaf87ea155
* Version Independent ID: fb376c81-cd6b-9f13-b2e5-5642f099a364
* Content: [Set IP ranges and tags](https://docs.microsoft.com/en-us/cloud-app-security/ip-tags)
* Content Source: [CloudAppSecurityDocs/ip-tags.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/ip-tags.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@DeanGross Thanks for your feedback. Please can you provide a little more detail on the issue you raised?
In step5, the example describes overriding the Location for a range. What would make it clearer for you?

**Comment by DeanGross** [comment]
When we create policies, we can add filters that include a Location attribute. I'd like to know how the override checkbox could affect any policies that contain a location filter

**Comment by shsagir** [comment]
@DeanGross Thanks again for contacting Microsoft about your issue. Your request requires more information. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2099672) or [Send feedback](mailto:casfeedback@microsoft.com) so that we can investigate and the support team will advise us if any doc changes are required.
