### ISSUE TITLE
Page Updates

### ISSUE THREAD

**Issue by tmguinn** [MicrosoftDocs/CloudAppSecurityDocs#35]
Could we get a RSS feed or twitter account update for when new content is posted? (Or is there and I can't find it?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee159bf-1044-a912-9920-288ac4e62050
* Version Independent ID: 5f8063d7-034b-e708-685f-396659fa59d0
* Content: [What's new with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/release-notes)
* Content Source: [CloudAppSecurityDocs/release-notes.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/release-notes.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @tmguinn 
Thanks so much for your feedback. Those options aren't currently available in Docs, but I'll be sure to pass along your interest to the right people.
#docs-experience

**Comment by ladybonner** [comment]
I am lost reading the list. One thing I can not do is code..I have been saying that. Thank God for those that can. I haven't used Microsoft in a long while. It's on my daughter's computer. We can't even log onto it. I took it to my brother's, so he could look at it.. He said that he couldn't access it either. It's just been sitting here. My husband said we need to take it back to office max and let them look at it. I think it's still under warranty.
