### ISSUE TITLE
Dynamics 365

### ISSUE THREAD

**Issue by PeterSchmidtPerth** [MicrosoftDocs/CloudAppSecurityDocs#352]
Can we list Dynamics 365 at the top level rather than burying it under Office 365. At first glance it looks like CSA protects our competitor, SalesForce, but not our own CRM tool Dynamics!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae7d409-a4f0-8c66-9a4d-ef6d7d5219ef
* Version Independent ID: 7894f069-c9a0-f356-b559-cd49f1cdbd9b
* Content: [Protect apps in your environment using cloud service provider APIs](https://docs.microsoft.com/en-us/cloud-app-security/protect-connected-apps)
* Content Source: [CloudAppSecurityDocs/protect-connected-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/protect-connected-apps.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@PeterSchmidtPerth Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
