### ISSUE TITLE
Need information about creating SIEM agent's token

### ISSUE THREAD

**Issue by rynatori** [MicrosoftDocs/CloudAppSecurityDocs#355]
This page doesn't include which role has permission for creating and/or modifying SIEM agent token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@rynatori Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@rynatori Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
