### ISSUE TITLE
Abilities per cloud app table isn't easy to read

### ISSUE THREAD

**Issue by oscargsune** [MicrosoftDocs/CloudAppSecurityDocs#360]
[Enter feedback here]
Team, the table listing the abilities per cloud app is hard to read, horizontal-scroll bar is at the bottom of the table and there is not vertical-scroll bar. Moreover, the headers are not fixed. This makes it hard to tell what capabilities are available for each app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cb69cd-d5d4-e058-e20f-d2697cfcd614
* Version Independent ID: bb8fbd63-532a-f8f9-6bc6-85eaf09ca171
* Content: [Connect apps to get visibility and control](https://docs.microsoft.com/en-us/cloud-app-security/enable-instant-visibility-protection-and-governance-actions-for-your-apps)
* Content Source: [CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@oscargsune Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
