### ISSUE TITLE
What is the point of CloudAppSecurityPolicy?

### ISSUE THREAD

**Issue by EhloWorldIO** [MicrosoftDocs/CloudAppSecurityDocs#362]
Step 7 in Configure Amazon Web Services auditing seems pointless. The CloudAppSecurityPolicy was created in step 7, but is never used or talked about in the rest of the document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf4839c-f4e3-5808-c608-f2795f7b640d
* Version Independent ID: 3ccbc129-d930-eb79-a034-365b89f88a13
* Content: [Connect Amazon Web Services with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-aws-to-microsoft-cloud-app-security?source=docs)
* Content Source: [CloudAppSecurityDocs/connect-aws-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-aws-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@EhloWorldIO Thanks for your question. It's step 2 of the AWS wizard for adding a user which requires the creation of a policy.
