### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by thynds** [MicrosoftDocs/CloudAppSecurityDocs#363]
On the MCAS Microsoft Docs here

https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu-azure?tabs=red-hat

Under "Docker on Linux in Azure" and "3. Add Docker repository:"

The following code "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum makecache" returns an error in PowerShell

"Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://download.docker.com/linux/centos/8.2/x86_64/stable/repodata/repomd.xml (IP: 13.227.173.73)
Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried"

It appears as if the directory at the above URL needs updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 818cbf6b-c397-8c86-e061-8e940ee94278
* Version Independent ID: 53b66b18-5321-b63e-a57b-44f146ff6944
* Content: [Configure automatic log upload using Docker in Azure](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu-azure?tabs=red-hat)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@thynds Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by shsagir** [comment]
@thynds Thanks so much for taking the time to leave us your comment on our documentation. We're researching your issue to update the page based on your suggestions. If relevant, changes will be made in the next possible publish.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.

**Comment by shsagir** [comment]
@thynds Thanks for your feedback. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.
