### ISSUE TITLE
Lack of documentation for alert records

### ISSUE THREAD

**Issue by MWEJ** [MicrosoftDocs/CloudAppSecurityDocs#366]
Please provide some useful information for the format of the JSON response to expect,
What key/value pairs will be returned and what is their meaning?
I'm specifically interested in what the difference is between the key is_open and statusValue and what their values means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e284473-920a-cbaa-221c-d8c15f70458b
* Version Independent ID: 93015542-06d8-d8ae-c079-9c99d9906055
* Content: [Fetch - Alerts API](https://docs.microsoft.com/en-us/cloud-app-security/api-alerts-fetch)
* Content Source: [CloudAppSecurityDocs/api-alerts-fetch.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-alerts-fetch.md)
* Service: **cloud-app-security**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by shsagir** [comment]
@MWEJ Thanks so much for taking the time to leave us your comment on our documentation. We're are in the process of updating our API docs including the response objects. For example, we started updating the [Data Enrichment](https://docs.microsoft.com/en-us/cloud-app-security/api-data-enrichment-list) APIs. This an ongoing project and may take a little while. The API you refer to will also be updated a part of the project.

We're closing this as an open issue for now, but feel free to continue to comment here as necessary. We appreciate your contribution to our community.
