### ISSUE TITLE
Support for Ubuntu 20.04?

### ISSUE THREAD

**Issue by TheSwede86** [MicrosoftDocs/CloudAppSecurityDocs#367]
Hello,

The page below lists the latest supported Ubuntu version as 18.04, I wonder if 20.04 is supported and if not any ETA?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 818cbf6b-c397-8c86-e061-8e940ee94278
* Version Independent ID: 53b66b18-5321-b63e-a57b-44f146ff6944
* Content: [Configure automatic log upload using Docker in Azure](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu-azure?tabs=centos)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@TheSwede86  - Thanks for your question. We'll investigate and get back to you as soon as we have an answer.

**Comment by dcurwin** [comment]
@TheSwede86  - It is not yet supported. We will update the documentation when support is available.

#please-close
