### ISSUE TITLE
RBAC page could be clearer

### ISSUE THREAD

**Issue by phaugras** [MicrosoftDocs/CloudAppSecurityDocs#368]
Hello,

the content of the page is a bit misleading I think. The roles you mention as "Office 365 and Azure AD roles with access to Cloud App Security" are - mostly - also listed in the drop down list "Select the type of role for this admin:" when you add admin access. For instance, the "global admin" role from this list does not relate to Azure AD Global Admin role but, so it seems, to an MCAS Global Admin Role.
Could you make this clearer please ?

Regards,

P. Augras

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@phaugras  - Thank you for your comment. We will investigate the issue and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your suggestion. We've updated the document to make it more clear.
