### ISSUE TITLE
What Project number (App ID) really is?

### ISSUE THREAD

**Issue by ken5scal** [MicrosoftDocs/CloudAppSecurityDocs#369]
Configure Cloud App Security 3.b says "Enter the Project number (App ID) that you copied earlier", but there are no such thing the docs instructed us to copy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f41e1e-2541-8773-efc2-eeb83a403a15
* Version Independent ID: 2f2d0316-9e75-44d6-0ab6-a56b1352a1e2
* Content: [Connect Google Workspace to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-google-workspace-to-microsoft-cloud-app-security?redirectedfrom=MSDN)
* Content Source: [CloudAppSecurityDocs/connect-google-workspace-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-google-workspace-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We are investigating and will get back to you.

**Comment by dcurwin** [comment]
@ken5scal - Thank you for your feedback. The page has been updated.
