### ISSUE TITLE
Access controls for Mobile and desktop need User agent tag AND Client app 

### ISSUE THREAD

**Issue by AlexFilipin** [MicrosoftDocs/CloudAppSecurityDocs#370]
Access policies for Mobile and desktop need  User agent tag AND Client app specified, otherwise they do not trigger. Just Client app does not seem to be enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect with Microsoft Cloud App Security Conditional Access App Control](https://docs.microsoft.com/en-us/cloud-app-security/proxy-intro-aad#access-controls)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by AlexFilipin** [comment]
Feel free to reach out, I also started an e-mail thread with casfeedback@microsoft.com

**Comment by dcurwin** [comment]
@AlexFilipin  - Thanks for your comment. We'll investigate the issue and get back to you.

**Comment by dcurwin** [comment]
@AlexFilipin  - Was casfeedback@microsoft.com able to resolve your issue? This doesn't appear to be a documentation issue, so resolving it through Support would seem to be the best approach.

**Comment by AlexFilipin** [comment]
@dcurwin No feedback from casfeedback - However I have confirmed in several test and customer tenants that the product requires client app and user agent tag being specified. Is it a product bug? Not sure. Will the current documentation work? No

**Comment by dcurwin** [comment]
@AlexFilipin  - Thanks for the quick response. We'll continue to investigate.

**Comment by dcurwin** [comment]
@AlexFilipin  - I've been told that there is no reason the user tag needs to be used. Therefore, to determine what's happening in your particular scenario, please open a support ticket:

https://docs.microsoft.com/en-us/cloud-app-security/support-and-ts
