### ISSUE TITLE
Optionally Validating the Signature

### ISSUE THREAD

**Issue by mikeycrawford** [MicrosoftDocs/CloudAppSecurityDocs#371]
When optionally validating the signature of the powershell script LogCollectorInstaller.ps1, the name of signer is "Microsoft Azure Code Sign" rather than "Microsoft Corportation" and the Digital Signature Information records that "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider".  The countersignatures Name of Signer is "Microsoft Time-Stamp Service"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows#validate-signature)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@mikeycrawford  - Thank you for your comment. We will investigate the issue and get back to you.

**Comment by dcurwin** [comment]
Thank you again for your contribution. The issue is being addressed by the engineering team.
