### ISSUE TITLE
Wrong digital signer name

### ISSUE THREAD

**Issue by Damra123** [MicrosoftDocs/CloudAppSecurityDocs#373]
When setting up Docker on Windows, and downloading the "LogCollectorInstaller.ps1", the name of the signer is showing as "Microsoft Azure code sign" while in the documentation, it mentions that the Name of signer should be Microsoft Corporation

**Comment by dcurwin** [comment]
Thank you for your comment. We will investigate the issue and get back to you.

**Comment by dcurwin** [comment]
Thank you again for your contribution. The issue is being addressed by the engineering team.
