### ISSUE TITLE
Comparison of Integration Capabilities

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#374]
Does Office 365 CAS provide integration with Defender for Endpoint? Please provide more details in the comparison table about how the two versions compare. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a66643-56f5-dc00-5af6-3ee1d9b6f090
* Version Independent ID: c319c4a4-974e-7e3a-d58a-76fd57a9efe9
* Content: [Differences between Cloud App Security and Office 365 Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-o365.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-o365.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@DeanGross  - We've updated the document. Thanks for your feedback!

**Comment by DeanGross** [comment]
Thanks, but I don't see any changes and the page shows that it has not been updated since February. Did something fail in the publishing process?

**Comment by dcurwin** [comment]
We made changes to the second row here (Deployment for discovery analysis)

https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365#feature-support
