### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by kevin2l** [MicrosoftDocs/CloudAppSecurityDocs#375]
The screens used here no longer exist in the product.  Please update to show the new query functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec49198-bda6-5138-159f-f80ef187b9b0
* Version Independent ID: 62bb765d-10f1-f04b-d293-6184be709b02
* Content: [Visibility into cloud app accounts](https://docs.microsoft.com/en-us/cloud-app-security/accounts)
* Content Source: [CloudAppSecurityDocs/accounts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/accounts.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your suggestion. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your suggestion. We've updated the images.
