### ISSUE TITLE
Release 197

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#376]
It's great to see that the service health info will be consolidated into the M365 Admin center service health page. Could you please do the same thing with What's New messages, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee159bf-1044-a912-9920-288ac4e62050
* Version Independent ID: 5f8063d7-034b-e708-685f-396659fa59d0
* Content: [What's new in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/release-notes)
* Content Source: [CloudAppSecurityDocs/release-notes.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/release-notes.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@DeanGross - Could you elaborate further on what you mean by "do the same thing with What's New messages"?  When you say the "what's new messages" do you mean the release notes? And where would you like to see them?

**Comment by DeanGross** [comment]
Yes, release notes from MCAS. I would like to see them in the O365 Message center,

**Comment by dcurwin** [comment]
@DeanGross  - Since this isn't a documentation request, I'm going to close this issue. However, the development team will discuss your request and determine the best way to move forward.
