### ISSUE TITLE
We need more details in the "Block malware on upload" paragraph

### ISSUE THREAD

**Issue by donnyatmsft** [MicrosoftDocs/CloudAppSecurityDocs#377]
Can you please add licensing requirements (if any apart AAD Premium P1) in the paragraph "Block malware on upload" when protecting upload/download of malware to/from Microsoft first party saas app (i.e. OneDrive for Business) vs third party saas apps (i.e. Dropbox)? It's not clear if we need Defender for O365 Plan 1.
Can you also provide more details on how those checks done by MCAS works (i.e. detonation vs threat intellingence)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019ab0de-8c3b-7eba-3506-cc2ab655b4ed
* Version Independent ID: 8f37cbfb-edce-a737-5bc8-17f2ed3d5958
* Content: [Create session policies in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/session-policy-aad)
* Content Source: [CloudAppSecurityDocs/session-policy-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/session-policy-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.
