### ISSUE TITLE
Why not just link to the CAS portal?

### ISSUE THREAD

**Issue by danabrash** [MicrosoftDocs/CloudAppSecurityDocs#378]
So many opportunities, please just put the link.  One of my least favorite aspects of many MS articles is they assume we remember all the URLs of all the products, features, admin centers, etc. that are out there.  Please just link what you're talking about, it's so easy, and would be quite courteous.  thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for the comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@danabrash  - Could you let us know which URLs you'd like to see in this article? Thanks!

**Comment by dcurwin** [comment]
@danabrash  - Still waiting for your response. Is this still an issue?

**Comment by danabrash** [comment]
Thanks, sorry I missed the previous responses.

Having links to the CAS portal readily available would help people new to CAS to more quickly get oriented.  I think there could be a link in the second sentence.  e.g.

> This article provides instructions for setting access to the [Cloud App Security portal](https://portal.cloudappsecurity.com/) for your admins. 

similar to [This Article](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security#to-access-the-portal)

Having it right at the top would help set context immediately

I see that there is similar in [the access-for mssps](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins#access-for-mssps-to-the-mssp-customer-cloud-app-security-portal) section

I don't remember that being there before but perhaps I missed it.  The URLs in that section should be links.

**Comment by dcurwin** [comment]
Thanks for your response. I added a link to the portal on that page.
