### ISSUE TITLE
Deployment Steps

### ISSUE THREAD

**Issue by derpmcgerp1080p** [MicrosoftDocs/CloudAppSecurityDocs#380]
[Enter feedback here]
Would recommend reviewing the order or steps for deployment. Suggest Cloud Discovery as first steps and others to follow that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your feedback. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for providing feedback. 

Different customers choose to start the process in different ways. We've found that many of them prefer to connect and configure their own apps before starting the process of discovering all the apps in their network (shadow IT). But if a customer prefers to reverse that order, there's no reason not to.
