### ISSUE TITLE
update screenshot in Step 1

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/CloudAppSecurityDocs#381]
Screenshot in Step 1 needs to be updated.  The "+" menu is now in different place (on the left)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c7ec0b-8a9e-1aec-f8a6-97864b401aef
* Version Independent ID: dc977df5-36a8-0371-c7fa-8f745df452ba
* Content: [Connect Office 365 to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-office-365-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-office-365-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-office-365-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for the comment. We've replaced the images.
