### ISSUE TITLE
Useless article without links

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/CloudAppSecurityDocs#382]
[Enter feedback here]
This article is useless without links, especially for beginners like me. I want to learn by reading the online documentation and all I get is frustration. For example. when you say: "**Go to Control > Policies > Shadow IT**", from which of the infinite dispersive Microsoft websites I should open this? Is it admin.microsoft.com or security.microsoft.com or endpoint.microsoft.com or portal,azure.com or.... did you get my point? Not to mention that some paths or screenshots are obsolete! For a beginner like me who is trying to learn, you make my life like hell and I'd just abandon the system. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eacc3bb2-913e-365a-a49d-e50a03d200fc
* Version Independent ID: dced7104-668a-c061-648e-14c0c490ea59
* Content: [Create Cloud Discovery anomaly detection policy in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/cloud-discovery-anomaly-detection-policy)
* Content Source: [CloudAppSecurityDocs/cloud-discovery-anomaly-detection-policy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/cloud-discovery-anomaly-detection-policy.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate the issue and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your feedback. We've added links, screenshots and more up to date explanations to the article.
