### ISSUE TITLE
These instructions use old SF interface

### ISSUE THREAD

**Issue by phillym** [MicrosoftDocs/CloudAppSecurityDocs#383]
Hi there,

These instructions use the old Salesforce interface. Can you please update them to use the new Lightning interface?

Thanks!

Phil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88294d23-b573-bb18-d6f9-65a06614b0d5
* Version Independent ID: 1a87274f-14b2-393c-f535-b571748817a2
* Content: [Connect Salesforce to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-salesforce-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-salesforce-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-salesforce-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for the comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your comment. We've updated the screenshots and instructions.
