### ISSUE TITLE
License Requirement Conflict

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/CloudAppSecurityDocs#387]
The opening statement of this page says the following:

"Your organization must have a license to use Cloud App Security. For pricing details see the Cloud App Security licensing datasheet.", but then proceeds to say "Cloud App Security does not require any Office 365 licenses".

Could this be clarified for licensing requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Deploy Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/getting-started-with-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/getting-started-with-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your comment. We've updated the licensing requirements on that page to make it more clear.
