### ISSUE TITLE
Are these steps applicable for ADFS 2012 R2?

### ISSUE THREAD

**Issue by gesmyrli** [MicrosoftDocs/CloudAppSecurityDocs#388]
Are these steps applicable for ADFS 2012 R2? Because there is no mention of it at all inside this documentation. The only prerequisite that is mentioned is to have a pre-configured AD FS environment.

Thank you,
George
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af0d3bde-c333-70fa-1dff-2f83874781dd
* Version Independent ID: 8ee6c270-c9e0-eb7a-effb-52ec4c90f05b
* Content: [Deploy Cloud App Security Conditional Access App Control for any web app using AD FS](https://docs.microsoft.com/en-us/cloud-app-security/proxy-idp-adfs)
* Content Source: [CloudAppSecurityDocs/proxy-idp-adfs.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/proxy-idp-adfs.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your comment. We've updated the document to say: "The steps here apply to all versions of AD FS that run on supported version of Windows Server." That includes ADFS 2012 R2.
