### ISSUE TITLE
Update on which Windows OS are supported to match Docker Doc

### ISSUE THREAD

**Issue by pacarval** [MicrosoftDocs/CloudAppSecurityDocs#389]
Per Docker link:

https://docs.devolutions.net/wayk/bastion/docker-installation.html

"Wayk Bastion is a product composed of multiple services shipped as Docker containers for Windows and Linux, which is why you need a working Docker environment to get started. We recommend choosing one of the two following combinations:
	• Windows Server 2019 + Windows Containers
	• Ubuntu Linux 18.04 LTS + Linux Containers
Other versions of Windows may work, but we do not support them officially. We recommend Ubuntu Linux because it is was we use, but other Linux distributions such as Red Hat Enterprise Linux (RHEL) should work the same.
Windows
When in Rome, do as the Romans do: use Windows containers on Windows. Real Windows containers are best supported in Windows Server 2019, which is why we make it a requirement for Windows. Other versions of Windows have Important Docker limitations and are therefore not officially supported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comments. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@pacarval - Thank you again for your comment. Can you clarify your request? Do you have a question you'd like answered? Is there something you'd like us to update in the documentation?

**Comment by dcurwin** [comment]
@pacarval  - We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
