### ISSUE TITLE
There is no microsoft/caslogcollector image on Docker Hub

### ISSUE THREAD

**Issue by OrdinaryGuy** [MicrosoftDocs/CloudAppSecurityDocs#39]
Guys, this makes the whole idea of Docker deployment impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e21ac1e4-295d-74f4-8217-087203c54bb7
* Version Independent ID: 229ddf62-fd89-8e05-a55a-6a894a57c13a
* Content: [Configure automatic log upload for continuous reports](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by OrdinaryGuy** [comment]
I have found some these lines from MCASInstallDocker.sh:
`docker login -u caslogcollector -p C0llector3nthusiast > /dev/null 2>&1 || exit_on_error "Login to hub failed"
docker pull microsoft/caslogcollector 2>/dev/null || exit_on_error "Failed pulling latest collector image"`

I assume that image either should be made public or at least the article should get some explanation.

**Comment by rkarlin** [comment]
Hi @OrdinaryGuy, please open a support ticket so that we can help you with this. Thanks!

**Comment by TLinnepe** [comment]
@OrdinaryGuy I had issue loading the files for an Ubuntu 16.04

**Comment by ClaudioRifo** [comment]
Any chance to get more details on this?

**Comment by rkarlin** [comment]
Hi,
thanks for your feedback. This is a great place to provide feedback on the documentation for Cloud App Security. For issues using the Docker, please open a support ticket.
thanks for reaching out!

**Comment by mmendozaf** [comment]
Hello, 

Could this docker image run on windows server 2012 r2 with docker engine installed or Windows server 2016?

Regards

**Comment by rkarlin** [comment]
Hi @mmendozaf 
Please contact the product team at casfeedback@microsoft.com
thanks,
Rachel
