### ISSUE TITLE
update second screenshot

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/CloudAppSecurityDocs#391]
The second screenshot should be updated, as it looks slightly different now in the MCAS portal.
Namely, instead of "**Block access**" it now says "**Enforce app access**",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a2e9aa-d864-f888-e08e-1d61db4ad75b
* Version Independent ID: 53fbf893-3bee-6320-2112-43818ce778c7
* Content: [Integrate Microsoft Defender for Endpoint with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/mde-integration#how-to-integrate-microsoft-defender-for-endpoint-with-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/mde-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your comment. We replaced the screenshot.
