### ISSUE TITLE
Is there an Azure Active Directory Cloud App Discovery?

### ISSUE THREAD

**Issue by wcneumann219** [MicrosoftDocs/CloudAppSecurityDocs#392]
This article and others imply there is an Azure AD Cloud App Discovery capability, but the links provided do not indicate there is any such service at this time. All links contain details on how to do Cloud App Discovery from the Microsoft Cloud App Security Portal, which of course requires a license before you can use it--which is contrary to this article that says there is a discovery capability built into the Azure AD P1 licensing.

If this capability no longer exists, please delete the errant references and adjust the text. If the capability does exist please provide links that explain how to deploy it because it is not in the Marketplace and it is not available from the Azure Active Directory blade.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401b0903-938e-9739-49eb-4c28ef10bcfc
* Version Independent ID: 89fc55de-a5eb-c398-4a53-5786f49349f2
* Content: [Discovery capability differences for Cloud App Security and Azure AD](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-aad)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@wcneumann219  - Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@wcneumann219  - We've updated [the document](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-aad) to make it more clear that Azure Active Directory P1 customers receive the Cloud App Discovery feature of MCAS as part of their subscription. 

Is that more clear?

**Comment by wcneumann219** [comment]
Hi David,

Yes, but I’m not sure that you can use that feature with that license because I don’t think you can log onto the MCAS portal without having an MCAS license.

Does the above make sense, i.e., I believe that if you set up a subscription with just Azure AD Premium P1 you are blocked from using the portal to get to the Cloud App Discovery feature. Alternatively, I don’t see a way to use Cloud App Discovery from the Azure AD blade.

The below screenshot shows this subscription has M365 E3 which includes Azure AD P1. The second screenshot shows that I’m not allowed to use the MCAS portal. I may be licensed to use the feature with Azure AD P1, but there doesn’t seem to be a way to actually use it😊.

Am I missing something?

Bill

***@***.***D76BFC.FFFD9B20]

***@***.***D76BFC.FFFD9B20]

Bill Neumann

Note: I will be scheduling new meetings to “start late” by a few minutes to create gaps between back-to-back meetings (per Microsoft research😊)

NOTE: Upcoming Out of Office
6/24-6/25; 7/19-7/23

***@***.******@***.***D76BFC.47992B30]
Principal Solutions Architect - Microsoft Cloud
Microsoft Center of Excellence
***@***.******@***.***>
Phone: 240-565-1650
www.connection.com<http://www.connection.com/>​
***@***.***D76BFC.47992B30]
LINKEDIN<https://www.linkedin.com/company/connection-it/>  l  TWITTER<https://twitter.com/ConnectionIT>  l  FACEBOOK<https://www.facebook.com/Connection4IT/>  l  INSTAGRAM<https://www.instagram.com/ConnectionIT/>  l  YOUTUBE<https://www.youtube.com/c/ConnectionIT>  l  BLOG<https://www.connection.com/social-blog>

**Comment by dcurwin** [comment]
@wcneumann219 - Thanks for your reply, and we'll continue to investigate.

But could you paste your screenshots directly into the GitHub issue? When you reply by email, they don't show up.

**Comment by wcneumann219** [comment]
Here are my screenshots...
![Screenshot 2021-06-28 112340](https://user-images.githubusercontent.com/56602411/123662530-90c0fb80-d803-11eb-9333-36ae399a6953.png)
![Screenshot 2021-06-28 112209](https://user-images.githubusercontent.com/56602411/123662566-97e80980-d803-11eb-8d8a-87aa12c92b32.png)

**Comment by dcurwin** [comment]
@wcneumann219  - Thanks - we'll continue to look into this.

**Comment by dcurwin** [comment]
@wcneumann219  - I spoke to the product team, and this is what they told me:

"It looks like he has a credentials/permissions issue - by definition, he should be able to access the Cloud App Discovery portal (MCAS portal with subset of capabilities).
There is not Azure blade for the experience as we discussed.
He should open a support ticket."

So it doesn't seem to be a documentation issue. If that's the case, I'll close this GitHub issue, and hopefully support will be able to quickly resolve your issue.

**Comment by wcneumann219** [comment]
Hi David,

What they in the “by definition” section is what I would have expected, but the account I was using when I was denied access was a Global Admin.

Unfortunately, the trial license I was using to test this expired today so I can’t test it again. I was able to verify that I did get access to the portal with the same account when I upgraded my license to one that included MCAS versus having one that only had Azure AD P1.

It might be worthwhile testing my scenario. I’m pretty sure that an Azure AD P1 license is not sufficient to access the MCAS portal, i.e., my belief is that the MCAS portal won’t provision without someone having an MCAS license.

I don’t have time to set up another experiment in a new environment to test with more trial subscriptions. Only can invest so much time on one thing.

Bill

Bill Neumann

Note: I will be scheduling new meetings to “start late” by a few minutes to create gaps between back-to-back meetings (per Microsoft research😊)

NOTE: Upcoming Out of Office
6/24-6/25; 7/19-7/23

***@***.******@***.***D76CFE.C18C9D70]
Principal Solutions Architect - Microsoft Cloud
Microsoft Center of Excellence
***@***.******@***.***>
Phone: 240-565-1650
www.connection.com<http://www.connection.com/>​
***@***.***D76CFE.C18C9D70]
LINKEDIN<https://www.linkedin.com/company/connection-it/>  l  TWITTER<https://twitter.com/ConnectionIT>  l  FACEBOOK<https://www.facebook.com/Connection4IT/>  l  INSTAGRAM<https://www.instagram.com/ConnectionIT/>  l  YOUTUBE<https://www.youtube.com/c/ConnectionIT>  l  BLOG<https://www.connection.com/social-blog>

**Comment by dcurwin** [comment]
@wcneumann219  - I'm sorry you had that experience. The GitHub issues are only meant to deal with documentation, but if in the future you do speak to support about your difficulties, and the documentation needs to be updated accordingly, I'll be happy to do so.

I'm closing this issue now, but feel free to return here if there are additional documentation requests regarding this issue.
