### ISSUE TITLE
This article is out of date. Google has changed several of the steps.

### ISSUE THREAD

**Issue by jpozzoli** [MicrosoftDocs/CloudAppSecurityDocs#393]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f41e1e-2541-8773-efc2-eeb83a403a15
* Version Independent ID: 2f2d0316-9e75-44d6-0ab6-a56b1352a1e2
* Content: [Connect Google Workspace to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-google-workspace-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-google-workspace-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-google-workspace-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by i-am-ari** [comment]
Hi, 

The article is out-of-date and I am having the same issue.

**Comment by comparis-development** [comment]
It's impossible to follow - several steps are now undoable.

@dcurwin by when do you plan to update the documentation?

**Comment by dcurwin** [comment]
@jpozzoli @i-am-ari @comparis-development  - Thank you for your feedback. The page has been updated.

**Comment by pl4nty** [comment]
Thanks @dcurwin! and hi @i-am-ari 👋

**Comment by i-am-ari** [comment]
@dcurwin Many thanks for updating this. Legend!

@pl4nty hey there! 👋

**Comment by comparis-development** [comment]
@dcurwin Thanks a lot for taking the time to update the documentation.

I was able to connect Google Workspace to Defender.
