### ISSUE TITLE
Lack of Reference link

### ISSUE THREAD

**Issue by SabrinaKay** [MicrosoftDocs/CloudAppSecurityDocs#394]
[Enter feedback here]
It could be improve by adding the API reference link into this document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ef412a-b90e-dd0e-4d21-dfdaf87ea155
* Version Independent ID: fb376c81-cd6b-9f13-b2e5-5642f099a364
* Content: [Set IP ranges and tags](https://docs.microsoft.com/en-us/cloud-app-security/ip-tags)
* Content Source: [CloudAppSecurityDocs/ip-tags.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/ip-tags.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your suggestion. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you again for your contribution. We've added links to the document.
