### ISSUE TITLE
Inappropriate information in the article

### ISSUE THREAD

**Issue by ficzagergo** [MicrosoftDocs/CloudAppSecurityDocs#397]
Hi!

In section "Investigate app usage in Defender for Endpoint with advanced hunting" I found the following issues:
1. "In Cloud App Security, under Discovery and then select Discovered." Missing apps from the end of the sentence: "Discovered apps.".
2. "In Microsoft 365 Defender, under Devices, select Advanced hunting." I think, it should be Hunting\Advanced hunting, not Devices\Advanced hunting.
3. I think, you should note, that you can use wildcard in the <DOMAIN_LIST>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a2e9aa-d864-f888-e08e-1d61db4ad75b
* Version Independent ID: 53fbf893-3bee-6320-2112-43818ce778c7
* Content: [Integrate Microsoft Defender for Endpoint with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/mde-integration)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/mde-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
I've updated the doc to reflect your first two suggestions. I'll look into the third, and let you know.

**Comment by ficzagergo** [comment]
Sorry, a correction about my previous suggestion.
Can't use wildcard the right expression in "I think, you should note, that you can't use wildcard in the <DOMAIN_LIST>." instead of "can use". I think, it can be misleading, if you check the domains of the discovered app, because in a lot of cases (if not in all), it is mentiones domains with wildcard (e.g. *.microsoft.com)
Thank you!

**Comment by dcurwin** [comment]
Thanks for the update.

**Comment by dcurwin** [comment]
And after checking, I've now updated the third point as well. Thanks for your contribution!
