### ISSUE TITLE
Create Log Collector

### ISSUE THREAD

**Issue by matttitcombe** [MicrosoftDocs/CloudAppSecurityDocs#399]
The create log collector is for Hot IP or FQDN is not clear this has to be the public-facing IP address the logs are coming from:
![image](https://user-images.githubusercontent.com/87026348/124619948-4d374480-de36-11eb-87d3-9f4a57e7c48d.png)

Please clarify this in the install guides.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e0555c-41e5-0ba3-4c4b-f9c386644a72
* Version Independent ID: 876888bc-8046-0a25-a0b7-67f938cc45c1
* Content: [Configure automatic log upload for continuous reports in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker)
* Content Source: [CloudAppSecurityDocs/discovery-docker.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you again for your feedback. The host IP address should be the private IP address of the server. I've updated the documents to reflect that as well.
