### ISSUE TITLE
how should one pass a date argument?

### ISSUE THREAD

**Issue by yaakovi** [MicrosoftDocs/CloudAppSecurityDocs#402]
[Enter feedback here]
an example of a date argument is missing.
tried the following formats, nothing worked:
* yyyy-mm-dd
* yyyy-mm-ddTHH:MM:SS
* yyyy-mm-ddTHH:MM:SS.ffffff
* yyyy-mm-ddTHH:MM:SSZ
* yyyy-mm-ddTHH:MM:SS+00:00
* yyyy-mm-ddTHH:MM:SS+0000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7176c15a-025f-f67a-502c-5353eced167f
* Version Independent ID: ec00e101-7d22-d7b6-f6a7-1fc2208eb69a
* Content: [Cloud App Security REST API](https://docs.microsoft.com/en-us/cloud-app-security/api-introduction#filters)
* Content Source: [CloudAppSecurityDocs/api-introduction.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-introduction.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your feedback. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@yaakovi  - Thanks again for your question. The dates are in the timestamp format. We've added this section to clarify it:

https://docs.microsoft.com/en-us/cloud-app-security/api-introduction#timestamps
