### ISSUE TITLE
ARM64 Docker Image?

### ISSUE THREAD

**Issue by deltasierra-ufc** [MicrosoftDocs/CloudAppSecurityDocs#403]
Does an image compiled for the ARM64 architecture, e.g. "linux/arm64/v8" exist?  I have Docker-CE setup right to the last step of pulling the image.  I get the following:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

If not, could someone work toward this, even if it must go officially unsupported for now?

Thanks much!!

**Comment by dcurwin** [comment]
Thanks for your feedback. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@deltasierra-ufc - Do you have a question about the documentation? If so, could you please let me know which page you are referring to? If it's not a documentation issue, I recommend you open a support ticket.

**Comment by deltasierra-ufc** [comment]
@dcurwin Oops, my mistake on that; I see this repo is focused on the documentation side.  I'll need to submit a support ticket then, but nevertheless, perhaps more clarity on a few items in the docs for 'Docker for Linux on-premise' log collector could specify CPU architectures (x86-64 only or that and ARM64?).  If/when ARM64 support comes about, there would need to be tabs or something to select that to bring up the correct configuration scripts for bash.

Lastly, I've ran log collectors successfully in Ubuntu 20.04 on x86-64 machines -- is this still unofficially supported?  The pre-req's only list up to 18.04, although 20.04 was released over a year ago.

**Comment by dcurwin** [comment]
What pages are you asking about?

**Comment by deltasierra-ufc** [comment]
CloudAppSecurityDocs/discovery-docker-ubuntu.md

**Comment by dcurwin** [comment]
Thanks, I'll investigate and get back to you.

**Comment by dcurwin** [comment]
@deltasierra-ufc Thank you again for your contribution. 

We've updated the documentation to indicate that only Intel x64 and AMD 64 CPU architectures are supported.

ARM64 is not supported. Ubuntu 20.04 is also not yet supported. If and when either of those change, we'll update the documentation accordingly.
