### ISSUE TITLE
Odd NS record found under MCAS domains

### ISSUE THREAD

**Issue by botmania** [MicrosoftDocs/CloudAppSecurityDocs#405]
There is an odd NS record found under an MCAS domain

cas.ms --> ns-751.awsdns-29.net
ns-1797.awsdns-32.co.uk
ns-1495.awsdns-58.org
ns-136.awsdns-17.com

Is this expected or is unusual?

**Comment by dcurwin** [comment]
Thanks for your feedback. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@botmania  - This does not appear to be a documentation issue. The best way to get help is to open a support ticket.
