### ISSUE TITLE
Docker URL incorrect

### ISSUE THREAD

**Issue by custa19** [MicrosoftDocs/CloudAppSecurityDocs#407]
The Docker Download URL on line 62 in the Powershell Script is wrong giving an error, the new URL for dowloading Docker I believe should be: https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe

LogCollectorInstaller.ps1:62

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-gb/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your feedback. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@custa19  - This is not a documentation issue, so it can't be addressed here, but I will pass it on to the product team and recommend they take a look at the issue.
