### ISSUE TITLE
Is this list of domains up-to-date and accurate? 

### ISSUE THREAD

**Issue by agfoster** [MicrosoftDocs/CloudAppSecurityDocs#408]
Is the list of domains listed in this article up-to-date and accurate? I've found some similar looking domains that appear to be legitimate and match the pattern, but aren't listed on this site. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e092a97-a2c2-849c-6bd0-6e73a90ffc57
* Version Independent ID: 2eeaa902-7a79-5a32-0031-2290302a378f
* Content: [Troubleshooting - What is cas.ms, mcas.ms, or mcas-gov.us?](https://docs.microsoft.com/en-us/cloud-app-security/troubleshooting-proxy-url)
* Content Source: [CloudAppSecurityDocs/troubleshooting-proxy-url.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/troubleshooting-proxy-url.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@agfoster  - I checked with the product team and they confirmed that the list is up-to-date. 

Thanks for reaching out.
