### ISSUE TITLE
Cloud App Security Administrator permissions

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/CloudAppSecurityDocs#409]
We see a difference w.r.t. "Manage admins and activity privacy" (from the top right hand corner cog wheel menu "Manage admin access"). `Security Administrator` is able to do that, but `Cloud App Security Administrator` is not (the menu entry is not present)
This is contradictory to what is written:

> **Cloud App Security administrator**: Allows full access and permissions in Cloud App Security. Similar to Global administrator or Security administrator but scoped solely to Cloud App Security.

Strange, because the role permissions are a.o. `microsoft.directory/cloudAppSecurity/allProperties/allTasks`
Or is it a bug in the presentation of the cog wheel menu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200a667a-64bf-422d-e110-4798f509fcd0
* Version Independent ID: 3966732b-93fc-629b-b138-c096cb77a3cf
* Content: [Manage admin access to the Cloud App Security portal](https://docs.microsoft.com/en-us/cloud-app-security/manage-admins)
* Content Source: [CloudAppSecurityDocs/manage-admins.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-admins.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for your contribution. We've updated the documentation to indicate that "This role does not grant the ability to manage admins in Cloud App Security, unlike **Global administrator** or **Security administrator**."

I'm closing the issue now, but if you have any additional questions, please feel free to ask.

**Comment by t-bennyr** [comment]
@andrePKI Cloud App Security admins should have the ability to manage admins in MCAS - can you see the 'manage admin access' tab?

**Comment by dcurwin** [comment]
@andrePKI  - We did make the change to the document, but it seems a technical problem caused it to revert to the previous version. I've now corrected it: 

https://docs.microsoft.com/en-us/cloud-app-security/manage-admins

Is there something else regarding the documentation that you think still needs clarification?

**Comment by t-bennyr** [comment]
@andrePKI 
the MCAS global admin role differs from the AAD global admin role, and the ability to access 'manage admin access' is one of the differences. As MCAS contains sensitive information, the access to it should be granted by people with privileged roles (in this case - AAD global admin).
The Cloud App Security admin is a middle ground between these two roles - it would have the same privileges as AAD global admin in the MCAS portal, with the ability to manage it fully (including the ability to add new admins), but it would have access solely to MCAS, like the MCAS global admin. This allows security teams to assign an MCAS role in AAD (thus leveraging PIM and other features) but scoping it to MCAS only - instead of having cross-suite privileges like the rest of the roles in AAD.

We're aware of the fact that the naming is confusing, and are working on a solution.

**Comment by dcurwin** [comment]
@andrePKI - We've updated the document again for further clarity.

**Comment by andrePKI** [comment]
@t-bennyr Thank you for your explanation. With MCAS (and also for other solutions like Defender for Endpoint) we would like to fully delegate management away from Central IT (who holds AAD global admin) to IT Security (who should be able MCAS completely by itself without dependency on Central IT). Hence why I was under the impression MCAS global admin would be able to manage admin access. Now we need to give AAD Security Admin or Global Admin to IT Sec.
And that is a more general issue we encountered - the separation of Ops versus Sec/SecOps is not always possible as AAD roles have also implicit permissions in the security solutions which cannot be withdrawn. In our organisation this leads to people having too many permissions as we cannot fully separate the roles technically. To clarify, we have teams that each manage their private or public cloud and there is one security team managing the security of all.
But that is not a documentation issue.
