### ISSUE TITLE
Attempting to upload Cisco ASA logs failed

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/CloudAppSecurityDocs#41]
Hi, While I appreciate we can get demo logs of what the Cisco ASA *should* look like to be ingested correctly - *IT* would be really useful to turn this problem around from the other point and help explain *HOW* the process works at a Cisco ASA level to get the logs output in that same format,

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a419aaf2-b6b9-902a-e186-c5718b9ffd1f
* Version Independent ID: 2a9c599e-306e-490e-2e6d-7642fa71d63c
* Content: [Create snapshot reports of Cloud Discovery cloud app use](https://docs.microsoft.com/en-us/cloud-app-security/create-snapshot-cloud-discovery-reports)
* Content Source: [CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @dcaddick ! Thanks for reaching out. I understand our product team has already been in touch with you in the Yammer group. Thanks!
