### ISSUE TITLE
Docker Download Link Dead - Windows Install

### ISSUE THREAD

**Issue by deFRAGerNZ** [MicrosoftDocs/CloudAppSecurityDocs#410]
Docker download link in the LogCollectorInstaller.ps1 is dead. Suggest updating to https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff287a41-44c8-e587-842e-5a90e859d218
* Version Independent ID: 0ca69462-3626-fe6e-e59d-3d622caaae39
* Content: [Advanced log collector management](https://docs.microsoft.com/en-us/cloud-app-security/log-collector-advanced-management)
* Content Source: [CloudAppSecurityDocs/log-collector-advanced-management.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/log-collector-advanced-management.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@deFRAGerNZ  - This is not a documentation issue, so it can't be addressed here, but I will pass it on to the product team and recommend they take a look at the issue.
