### ISSUE TITLE
Clarity on GCP and Google Workspace connections

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/CloudAppSecurityDocs#413]
Reading through the instructions on how to connect Google Workspace and Google Cloud Platform, I'm unclear on a few items.

In the first paragraph of this document it says "if your GCP instance is part of a Google Workspace instance already connected to Cloud App Security, we recommend following the **For a GCP instance that is part of a connected Google Workspace organization** steps when you add the GCP connection details." There is no link to this section and nothing with that title. Is this referring to the "For an existing connector" subsection? This article states "Since you can add either or both of the connections, the steps in this article are written as independent instructions. If you have already added one of the connections, where relevant edit the existing configurations." Does this als oapply to linking both GCP and Google Workspaces as far as sharing service accounts and projects?

- Is it recommended we use two separate projects and service accounts if we are connecting both Google Workspaces and GCP apps to MCAS or is the recommendation to use a single account and project to use for MCAS? (I understand we shouldn't use a non-MCAS related project). Does adding the Cloud Logging and Pub/Sub API's to the service account for the Google Workspace account pose additional risk over two separate accounts?
- In MCAS, I can click on my existing Google Workspace app and I see a "Connect Existing Google Cloud Platform Instance" link. Is that the same as, and should I start there, to connect GCP to an existing connector? If so, are there any steps in the previous sections that would change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c93906-0f8a-a2d6-c542-d80ee38f9c75
* Version Independent ID: 1e647883-2470-ee9a-2f6b-c2172f7f190d
* Content: [Connect Google Cloud Platform to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-google-gcp-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-google-gcp-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-google-gcp-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your questions. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@cchambers-cap Thank you for your patience regarding this issue. The product team has provided me with the following answer:

There is no need to follow a different process if a customer has Google workspace connector configured. We have updated the article to reflect the same.
