### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/CloudAppSecurityDocs#425]
The sensitivity slider allows you to impact the algorithm and define how strict the detection logic is. The higher the sensitivity level, the lower the suppression that is applied as part of the detection logic.

The above lines are super confusing.  Maybe add in some examples.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395e085f-93bd-1f3c-fe0d-7711b6d51950
* Version Independent ID: ad86d15d-41a5-9a6e-8d30-18ed9a9975f2
* Content: [Create anomaly detection policies in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/anomaly-detection-policy)
* Content Source: [CloudAppSecurityDocs/anomaly-detection-policy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/anomaly-detection-policy.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@SquirrelAssassin - Thanks again for your comment. I've updated the sentence you mentioned with a link to examples, and I've rephrased the sentence for clarity.

**Comment by SquirrelAssassin** [comment]
If all tickets are starting to be auto closed ... your defeating the whole purpose of this system.  Nothing will get done, no one will follow up.  Please don't close tickets before completing the task.

**Comment by dcurwin** [comment]
I'm sorry you experienced it that way. I wrote above that in response to your comment, I rephrased the sentence and provided links to examples. It wasn't autoclosed - I closed it after performing your requests.

What is incomplete?

**Comment by SquirrelAssassin** [comment]
Its not done until its 100% done.  Closing a item defers responsibility.

**Comment by dcurwin** [comment]
Ok, I'm sorry I closed the issue too quickly. I've reopened it.

Please let me know what questions you have on the modified document.
