### ISSUE TITLE
Error in header? 

### ISSUE THREAD

**Issue by fswgm** [MicrosoftDocs/CloudAppSecurityDocs#428]
The header of this page as viewed on my Mac is "Microsoft Cloud App Security for title: Microsoft Cloud App Security for US Government offerings" - I assume it should just be "Microsoft Cloud App Security for US Government offerings"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ac1d0d-1f97-1bbf-732b-c65bb89170b1
* Version Independent ID: a28b78cc-7b30-b5f2-29a5-dd35111e05a0
* Content: [Microsoft Cloud App Security for US Government offerings](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-gcc)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-gcc.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-gcc.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. I've removed the words in error.
