### ISSUE TITLE
Uploading log files without usernames - what for?

### ISSUE THREAD

**Issue by SongsForTheDEV** [MicrosoftDocs/CloudAppSecurityDocs#430]
MS listed al lot of different firewall types with different properties which are important for MCAS. I wonder how a firewall can be supported, which is not able to provide the usernames. What can I do with this logfiles in MCAS? In my case our customer is utilizing a Fortigate, where all logfile uploads fail after a long time, because of an internal parsing error.

**Comment by dcurwin** [comment]
Thank you for your question. We'll investigate and get back to you.

**Comment by Tzoref12** [comment]
Hi,

Could you please clarify your question(s)?
Is it about parsing failure?
Firewall that doesn't support usernames?
Both?

**Comment by dcurwin** [comment]
@SongsForTheDEV - We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
