### ISSUE TITLE
MCAS - inconsistent information

### ISSUE THREAD

**Issue by maharumman** [MicrosoftDocs/CloudAppSecurityDocs#432]
In the comparison tables between MCAS, CAS and OCAS. there is inconsistent information in regards to number of apps supported in cloud app discovery. 
in the comparison table here we list 20K+  -- https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-aad
in the comparison table here we list 16K+ -- https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a66643-56f5-dc00-5af6-3ee1d9b6f090
* Version Independent ID: c319c4a4-974e-7e3a-d58a-76fd57a9efe9
* Content: [Differences between Cloud App Security and Office 365 Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365#feedback)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-o365.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-o365.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@maharumman  - Thanks for your comment! We've updated the docs appropriately.
