### ISSUE TITLE
PowerShell Example

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#433]
Could you please provide an example using PowerShell, this is the scripting language that is used by systems administrators for all of the other Microsoft products.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf430fa-621b-d643-ea58-e1752a57c0bf
* Version Independent ID: 851a9803-18ad-da89-ffb5-7e0702e94d39
* Content: [Manage IP address ranges using the API](https://docs.microsoft.com/en-us/cloud-app-security/api-data-enrichment-manage-script)
* Content Source: [CloudAppSecurityDocs/api-data-enrichment-manage-script.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-data-enrichment-manage-script.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by ms-smithch** [comment]
@DeanGross the Powershell API for Defender for Cloud Apps (MCAS) can be found here: https://github.com/Microsoft/MCAS note that this is an unofficial implementation but the examples found therein should satisfy your requirement

**Comment by dcurwin** [comment]
@DeanGross - As @ms-smithch mentioned, there is a PowerShell module that is not currently supported and is not official. It can be used as a sample, effectively that's what it is.

When/if in the future an official PowerShell module is developed, we will certainly let everyone know in the documentation.
