### ISSUE TITLE
Please add why customers get either - By Licence X

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/CloudAppSecurityDocs#438]
Please add to the table when customers get MCAS over O365 CAS - By licence X

Even the Licensing Datasheet doesn't have a table. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a66643-56f5-dc00-5af6-3ee1d9b6f090
* Version Independent ID: c319c4a4-974e-7e3a-d58a-76fd57a9efe9
* Content: [Differences between Cloud App Security and Office 365 Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-o365.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/editions-cloud-app-security-o365.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@DavidTaig  - Hi - could you clarify your question? I'm interested in helping with the documentation, but I don't understand your request. Thanks.

**Comment by dcurwin** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
