### ISSUE TITLE
Syslog log collector connected but no data

### ISSUE THREAD

**Issue by memsim1010** [MicrosoftDocs/CloudAppSecurityDocs#44]
[In the Cloud App Security portal I have followed the Instructions provided in this Microsoft Doc to configure continuous logs to be sent from my SonicWALL (syslog) to my Log Collector.  The log collector shows 'Connected' but is not receiving data. (See attached screenshot)

I have triple checked my settings in the SonicWALL and my Ubuntu server. 

I can confirm logs are flowing from the SonicWALL to the Ubuntu server but, how can I check if they are reaching the Cloud App Security portal?  

 I did notice that the log collector configuration script had a line in that caught my eye: "SYSLOG=false" Should this be changed to "true"?
![logcollector](https://user-images.githubusercontent.com/33670957/43859390-795167f2-9b1e-11e8-96ca-01f0f42493b9.png)

**Note: we do not block outbound traffic**]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e21ac1e4-295d-74f4-8217-087203c54bb7
* Version Independent ID: 229ddf62-fd89-8e05-a55a-6a894a57c13a
* Content: [Configure automatic log upload for continuous reports](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by joshie45** [comment]
@memsim1010,
Setting SYSLOG=true has not worked for me. I was wondering whether or not we need to add "-p 514-600:514-600" to the docker run command as well?

@rkarlin does this seem right to you?

**Comment by philkloose** [comment]
I too am dealing with what seems to be this exact issue.  I had a fully functional environment up until a few weeks ago and now I can't get anything to work.  I'm not entirely convinced that Dell's recent SonicWALL update isn't playing a role in this either.

@joshie45 I have tried your suggested fix on the Docker command `-p 514-515:514-515/UDP` in my case and it did not make a difference.  I have two sources of data that are supposed to be collected by my caslogcollector (Meraki WAPs on UDP 514 and SonicWall on UDP 515).  In regards to the Meraki WAPs, I see the traffic being passed to the caslogcollector when I look at Azure logs, but it doesn't seem to be doing anything with it.  In regards to the SonicWall traffic, I don't believe it's even attempting (tried to verify using the following method [here](https://www.sonicwall.com/en-us/support/knowledge-base/170502760959816)) to send it to the caslogcollector anymore.  I did see it sending them to another log analyzer that has nothing to do with this.  We're running SonicOS Enhanced 6.5.1.2-52n on our firewall.

Sorry, there's tons of info in here and possibly multiple issues.  Happy to check on anything that you have questions about.  In short, I think there is an issue with the configuration of the docker log collector AND I think there is an issue with the latest version of SonicOS.

**Comment by philkloose** [comment]
@rkarlin I made the `-e "SYSLOG=true"` change in conjunction with the `-p 514-515:514-515/UDP` addition and it's working.  I'm not sure whether or not my change was necessary, but I'm too afraid to redo it an find out.  Thanks.

**Comment by joshie45** [comment]
@philkloose I forgot the /UDP at the end of the ports, so I will try that again and advise. Hopefully it helps new people in the process :)

**Comment by joshie45** [comment]
Making the following changes worked for me also; `-e "SYSLOG=true"` in conjunction with `-p 514-515:514-515/UDP` now gives me "Data is being successfully uploaded from all linked data sources." in Cloud App Security. Thanks for your help @philkloose

**Comment by memsim1010** [comment]
Unfortunately, making those changes did not work for me.

--

Meg Simmons

Sr. IT Manager
msimmons@fusemarketing.com<mailto:msimmons@fusemarketing.com>
Send me a Chat<sip:msimmons@fusemarketing.com>
P: 802-383-1405
M: 802-598-9272

Fuse | Young Adult | Strategy | Events | PR | Design | Digital | Social Media
Web<http://fusemarketing.com/> |LinkedIn<http://linkedin.com/company/fuse>| Facebook<http://facebook.com/FuseLLC> | Twitter<http://twitter.com/fuse_marketing>

**Comment by memsim1010** [comment]
I just went into the Governance Log to see if anything was happening and I can now, for the first time, see that the Log Collector has submitted logs for parsing.  They are all failing but, at least it’s sending logs.   The error I am receiving in the Governance Log is: “Log format does not match the expected format for SONICWALL_SYSLOG”

Any Ideas?
--

Meg Simmons

Sr. IT Manager
msimmons@fusemarketing.com<mailto:msimmons@fusemarketing.com>
Send me a Chat<sip:msimmons@fusemarketing.com>
P: 802-383-1405
M: 802-598-9272

Fuse | Young Adult | Strategy | Events | PR | Design | Digital | Social Media
Web<http://fusemarketing.com/> |LinkedIn<http://linkedin.com/company/fuse>| Facebook<http://facebook.com/FuseLLC> | Twitter<http://twitter.com/fuse_marketing>




From: Meg Simmons <msimmons@fusemarketing.com>
Date: Wednesday, September 12, 2018 at 9:18 AM
To: MicrosoftDocs/CloudAppSecurityDocs <reply@reply.github.com>, MicrosoftDocs/CloudAppSecurityDocs <CloudAppSecurityDocs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/CloudAppSecurityDocs] Syslog log collector connected but no data (#44)

Unfortunately, making those changes did not work for me.

--

Meg Simmons

Sr. IT Manager
msimmons@fusemarketing.com<mailto:msimmons@fusemarketing.com>
Send me a Chat<sip:msimmons@fusemarketing.com>
P: 802-383-1405
M: 802-598-9272

Fuse | Young Adult | Strategy | Events | PR | Design | Digital | Social Media
Web<http://fusemarketing.com/> |LinkedIn<http://linkedin.com/company/fuse>| Facebook<http://facebook.com/FuseLLC> | Twitter<http://twitter.com/fuse_marketing>

**Comment by philkloose** [comment]
@TLinnepe The IP address is asking for is the one that your log collector will be collecting syslogs from other network devices on.  In my case, they come over a VPN so it's a private IP address.  In your case it sounds like it would be the "IP of the Ubuntu Docker machine where the LogCollector" is.  It needs to know this so that it can tailor the auto-generated CAS log collector commands to your environment.

@memsim1010 A couple of thoughts --

On the Sonicwall device
- verify that you've selected the **Enhanced Syslog** format
- verify that you've selected everything in the _Enhanced Syslog Fields Settings_ section

In the CAS Portal
- verify that you're sending to the correct port if you have multiple data sources configured.  For example, I have two and I have to make sure that my Meraki WAPs send to 514 and the Sonicwall goes to a non-standard 515.  If you get those crossed, it won't have any idea how to interpret the data.

I've had _a lot_ of issues with CAS lately.  Even after setting it up successfully, it seems to stop ingesting data for no particular reason after a few hours.  Rerunning the auto-generated docker commands will bring it back to life, but I'm not sure there isn't something else going on.  I have an Azure support case open because their NSG logging seems to be incomplete and it's making troubleshooting very difficult.  My NSG flow logs show no evidence of traffic being sent to my caslogcollector VM even though the CAS portal happily reports that it's receiving logs from time to time.  It's a mess.

**Comment by memsim1010** [comment]
@philkloose<mailto:notifications@github.com>, thank you!

I do have it set to Enhanced Syslog, though I did try every other format as well, and all the boxes are checked in the Enhanced Syslog settings.  Does the Syslog Facility make a difference?  It’s on Local Use 0 but I can’t imagine that would be the cause of the issue.

Alas, though it’s sending logs and CAS is receiving them, it still says “Log format does not match the expected format for SONICWALL_SYSLOG”


--

Meg Simmons

Sr. IT Manager
msimmons@fusemarketing.com<mailto:msimmons@fusemarketing.com>
Send me a Chat<sip:msimmons@fusemarketing.com>
P: 802-383-1405
M: 802-598-9272

Fuse | Young Adult | Strategy | Events | PR | Design | Digital | Social Media
Web<http://fusemarketing.com/> |LinkedIn<http://linkedin.com/company/fuse>| Facebook<http://facebook.com/FuseLLC> | Twitter<http://twitter.com/fuse_marketing>

**Comment by philkloose** [comment]
@memsim1010 Mine is also set to Local Use 0, but like you I'm not sure how important that is.  I'm assuming that "SONICWALL_SYSLOG" is the friendly name of the data source.  If that's the case, make sure that you also set the source type to _Dell SonicWall_ when you create the source.  I'm fairly certain you did this but I can't tell from your initial screenshot and it's worth checking.

Are you also sending your Sonicwall logs to another server unrelated to CAS?  I'm not convinced the Sonicwall device is doing exactly what it claims to be doing and in my case I'm wondering it it's due in part to the fact that I'm sending my syslogs to multiple destinations.  For whatever it's worth, I feel your pain.  This whole process is very brittle.  I'm afraid to breathe on it whenever I get it working.

**Comment by rkarlin** [comment]
Hi! Great discussion. Please feel free to reach out to our CAS team directly so our developers and product team can help provide insight. casfeedback@microsoft.com

**Comment by TLinnepe** [comment]
@rkarlin Thank you very much. I would like to contact the team about some details. 

The sonicwall's enhanced syslog format with all fields check worked for me.

In addition I got it to work last weekend by updating the sonicwalls to Firmware Version 6.5.1.2-52n. I also rebooted the Ubuntu Docker machine but I don't think that this has an affect to the Log uploading.

In the Portal page of the Logcollector generation I now have entered the IP Address from which the firewall is sending the syslog messages. So the internal IP address (in our environment with multiple internal VLANs it is the IP address of the specific vlan.

I will set up a blog site with a detailed guide how to set it up this week because there currently is very few content about CAS on the web.

Best regards,
Thomas

**Comment by memsim1010** [comment]
Hello there!
Just an update in case anyone else is struggling with this.  I went into our SonicWall and the only difference I noticed in our logs and the sample was the UTC timestamp.  After checking the box in the SonicWall to use UTC timestamps in logs, we now have successful log parsing!

**Comment by ClaudioRifo** [comment]
I was also with problems related to Log format.

I can confirm successful parse on Governance Log with firmware 6.5.1.3-11n.
I used the configuration provided by Cloud App Portal for the Docker. I used the Firewall IP on the configuration (The LAN IP of the sonicwall that was on the same network as the collector).

I Changed to Enhanced format with all options On.
And finally i activated the UTC option and things started to work.

**Comment by mekkimuyeeb** [comment]
HI, I'm having a connected with no data issues also. I'm getting this error : No transactions to recognized cloud apps were found while parsing 73 KB from PALO_ALTO_SYSLOG. 200+ logs have been uploaded but i dont see any data in my discovery reports

**Comment by rkarlin** [comment]
Hi, Thanks for getting in touch. I recommend that you contact support with your issues. This forum is a great place to let me know if there are issues with inaccurate documentation or typos, but if there are problems with the log collector itself, you really should contact your support representative directly.
thanks!
