### ISSUE TITLE
API based calls for entities does not include the mentioned filters

### ISSUE THREAD

**Issue by ahmed-emam** [MicrosoftDocs/CloudAppSecurityDocs#440]
The documentation for entities mentions "lastSeen" as part of the filters list provided. However when I requested filtering using "lastSeen" I got the following error message:

```
{
    "detail": "filter validation error: No filter name 'lastSeen' found in metadata entities"
}
```
The call was made using Postman.

URL: https://<CASB endpoint>/api/v1/entities/
Body: { "filters": {"lastSeen":{"range":[{"start": 1632117600000, "end": 1632117900000}]}}}

Did the schema for entities change?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d615c53e-4b32-7436-1e96-ebb37c58b381
* Version Independent ID: 2aee4389-712a-c1e0-b803-f65bfcaabc24
* Content: [Cloud App Security Entities API](https://docs.microsoft.com/en-us/cloud-app-security/api-entities)
* Content Source: [CloudAppSecurityDocs/api-entities.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-entities.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@ahmed-emam - Thank you again for your question. The page has been updated to remove that filter.
