### ISSUE TITLE
Confusing statement about data retention.

### ISSUE THREAD

**Issue by astaykov** [MicrosoftDocs/CloudAppSecurityDocs#441]
The section `Deleting personal data` states:

> After data is deleted from a connected cloud application, Cloud App Security will automatically delete the copy of the data **within 2 years**.

While `Data retention` says:

> Cloud App Security retains data as follows:
> 
>  * Activity log: 180 days
>  * Discovery data: 90 days
>  * Alerts: 180 days
>  * Governance log: 120 days

So, we see two completely different statements about data retention (from maximum of 180 days - the latter, to two years - the former). It will be very helpful this can be fixed, so it is crystal clear for how long does MCAS store data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589a07ee-5de7-7176-aa1d-f37d97fbf841
* Version Independent ID: 2c687672-01cc-78c9-04b9-ced4c94ac76a
* Content: [Cloud App Security compliance, data security, privacy, trust](https://docs.microsoft.com/en-us/cloud-app-security/cas-compliance-trust#deleting-personal-data)
* Content Source: [CloudAppSecurityDocs/cas-compliance-trust.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/cas-compliance-trust.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@astaykov  - We've updated the document to make it more clear. The sentence now reads:

> After a user’s account is deleted from a connected cloud application, Cloud App Security will automatically delete the copy of the data within 2 years.

Thanks for your contribution!
