### ISSUE TITLE
OAuth consent request link is invalid

### ISSUE THREAD

**Issue by stuartharbr** [MicrosoftDocs/CloudAppSecurityDocs#442]
In step 3g, the link that is created for consenting on the Google side is invalid.  Error: "The requested URL was not found on this server"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f41e1e-2541-8773-efc2-eeb83a403a15
* Version Independent ID: 2f2d0316-9e75-44d6-0ab6-a56b1352a1e2
* Content: [Connect Google Workspace to Cloud App Security](https://docs.microsoft.com/en-gb/cloud-app-security/connect-google-workspace-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-google-workspace-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-google-workspace-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@stuartharbr  - Thanks for your feedback. The page has been updated.
