### ISSUE TITLE
Request to correct the description in "Azure Information Protection integration"

### ISSUE THREAD

**Issue by Yuki-Nishio** [MicrosoftDocs/CloudAppSecurityDocs#450]
I believe the following description is not correct because I confirmed labels which attached outside of MCAS were not able to be overridden with MCAS. I tried to override a label manually and automatically from MCAS, the results were the same in both cases.

- Description
  Labels with protection outside of Cloud App Security can be overridden by Cloud App Security, but can't be removed.

Could you please make sure the above investigation is correct and update that description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Azure Information Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/azip-integration#how-it-works%E4%BB%A5%E5%89%8D%E3%81%AF%E5%89%8A%E9%99%A4%E3%82%82%E4%B8%8A%E6%9B%B8%E3%81%8D%E3%82%82NG%E3%81%A7%E3%81%82%E3%81%A3%E3%81%9F%E8%A8%98%E6%86%B6%E3%81%8C%E3%81%82%E3%82%8B%E3%81%AE%E3%81%A7%E3%81%99%E3%81%8C%E3%80%81%E7%8F%BE%E7%8A%B6%E3%81%AF%E6%94%B9%E5%96%84%E3%81%95%E3%82%8C%E3%81%A6%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%81%8C%E4%BB%98%E4%B8%8E%E3%81%97%E3%81%9F%E3%83%A9%E3%83%99%E3%83%AB%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6MCAS%E3%81%A7%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC%E3%81%AB%E5%90%88%E8%87%B4%E3%81%97%E3%81%9F%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AF%E4%B8%8A%E6%9B%B8%E3%81%8D%E3%81%8C%E3%81%A7%E3%81%8D%E3%82%8B)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/azip-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@Yuki-Nishio - We've checked and the documentation is correct. This capability was added about 8 months ago. 

If you have additional problems with the functionality, we recommend opening a support case.
