### ISSUE TITLE
Suggestion - add note about OAuth apps tab not appearing by default

### ISSUE THREAD

**Issue by turnma** [MicrosoftDocs/CloudAppSecurityDocs#454]
In the "Working with the OAuth apps page", it's worth adding a note to explain that the "OAuth apps" menu does not appear by default.  It only shows once an app has been connected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3543307c-9c07-720c-e4fe-3aa6cb43f680
* Version Independent ID: df363f37-c41a-7493-6573-c7a8f4ff1aaf
* Content: [Control which third-party cloud OAuth apps get permissions](https://docs.microsoft.com/en-us/cloud-app-security/manage-app-permissions#feedback)
* Content Source: [CloudAppSecurityDocs/manage-app-permissions.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/manage-app-permissions.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@turnma  - Thanks again for your comment. We've added a bullet to the first note with that information.
