### ISSUE TITLE
Incompatability with Windows Server 2022

### ISSUE THREAD

**Issue by JLangthaler** [MicrosoftDocs/CloudAppSecurityDocs#459]
Since support for WSL 2 was [pulled with Windows Server 2002](https://github.com/microsoft/WSL/issues/6301#issuecomment-858816891), this should be specified in the documentation. As of now this is not mentioned anywhere and Docker is simply not starting because it can't enabled WSL2.

**Comment by dcurwin** [comment]
@JLangthaler - Thanks again for your feedback. After consulting further with the product team, it was determined that we won't include all Docker considerations in the Microsoft Cloud App Security document. I have added a bullet to the first note on [this page](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows?source=docs), indicating that further information about Docker for Windows can be found [here](https://docs.docker.com/desktop/windows/install/).

I recommend that if you'd like more details about WSL 2 support, you request that it be added to the Docker page.
