### ISSUE TITLE
Data management reports are not accessible via this method

### ISSUE THREAD

**Issue by CharLind87** [MicrosoftDocs/CloudAppSecurityDocs#470]
Have to reiterate what the previous reported issue stated.
This documentation is completely out of date. The portal has changed a lot, in layout and features it seems.
There Data management reports is not something that can be found.

**Comment by dcurwin** [comment]
@CharLind87  - Thank you for your comment. Could you please let us know which page you are talking about? And if possible, which previous issue?

**Comment by dcurwin** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.

**Comment by CharLind87** [comment]
https://docs.microsoft.com/en-us/cloud-app-security/built-in-reports

**Comment by CharLind87** [comment]
Screen shots in the documentation is of the old portal so the instructions in the documentation doesn't apply anymore.
I see there is a note added that the page will be updated soon now.
But I am not finding this report feature anywhere currently. And I can't see that the article references it. So could the data management report have been removed completely?

**Comment by dcurwin** [comment]
@CharLind87 - After checking with the product group, the best path is for you to open a support ticket. The documentation reflects the way the product is expected to work, but if it's not working for you, please contact support.
