### ISSUE TITLE
Stale externally shared files - better description required

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/CloudAppSecurityDocs#48]
remove them from the drive / sharepoint or  remove the sharing???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0192fe47-4af3-0a7b-74a1-efbe7ad7536a
* Version Independent ID: 34ff03e6-aadf-638d-1b9f-30b999b19240
* Content: [Policy template reference in Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/policy-template-reference)
* Content Source: [CloudAppSecurityDocs/policy-template-reference.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/policy-template-reference.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@bakerm00 Hi, thanks for your feedback. You are right, it doesn't remove the file or the sharing - I have updated the article. You should see the change within the next day.

**Comment by bakerm00** [comment]
just to clarify your response - if it doesn't remove the external sharing - what is the point in the policy?

**Comment by rkarlin** [comment]
@bakerm00 It's a baseline template, you can add the required action based on your organization's policy.

**Comment by pjcarr3** [comment]
I don't believe this policy checks if a file has been opened either.
