### ISSUE TITLE
There are two license types listed.

### ISSUE THREAD

**Issue by Katakahashi0** [MicrosoftDocs/CloudAppSecurityDocs#489]
[Enter feedback here]
In the following URL, the license type for Google Workspace is listed as "Google Workspace Business or Enterprise preferred" and "
Google Workspace Enterprise (minimally)".

I think this is an error, so could you please correct it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f41e1e-2541-8773-efc2-eeb83a403a15
* Version Independent ID: 2f2d0316-9e75-44d6-0ab6-a56b1352a1e2
* Content: [Connect Google Workspace to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-google-workspace-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-google-workspace-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-google-workspace-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@Katakahashi0  - Thanks for your feedback. The page has been updated.
