### ISSUE TITLE
CAS Collector not sending logs

### ISSUE THREAD

**Issue by FFrozTT** [MicrosoftDocs/CloudAppSecurityDocs#49]
My CAS Docker is running. I have uploaded hundreds of logs via FTP to it but the Cloud App Data Source still shows 0 logs uploaded.  There is nothing blocking the CAS from sending logs and I occasionally see an HTTPS packet going to the Microsoft server <company>.us.portal.cloudappsecurity.com.

Instructions are poor.  What does "Configure your network firewalls and proxies to periodically export logs to the dedicated Syslog port of the FTP directory" mean? I'm not using Syslog I'm using FTP and how can anyone send logs to the "Syslog port of the FTP directory?" What does that mean? Syslog, FTP, and Directories are 3 different things which cannot be interconnected in the way described by that sentence.

And the example provided makes no sense either:
BlueCoat_HQ - Destination path: \<<machine_name>>\BlueCoat_HQ\
So am I supposed to FTP to <<machine_name>> then cd in to \BlueCoat_HQ before uploading files?  That directory does not exist and I've even tried creating it and putting logs in there to no avail.

**Comment by rkarlin** [comment]
Hi @FFrozTT 
I'm sorry to hear you're having trouble with the Docker installation. 
It sounds like you weren't successful in connecting the Docker. Please reach out to your customer support representative so our engineers can help you resolve this issue.
thanks,
Rachel
