### ISSUE TITLE
Empty rows?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#491]
How come some of the rows in the Information Protection table are empty? is this an oversight? Please add some explanatory text for the boxes that don't have a check or a comment
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cb69cd-d5d4-e058-e20f-d2697cfcd614
* Version Independent ID: bb8fbd63-532a-f8f9-6bc6-85eaf09ca171
* Content: [Connect apps to get visibility and control](https://docs.microsoft.com/en-us/cloud-app-security/enable-instant-visibility-protection-and-governance-actions-for-your-apps#users-and-activities)
* Content Source: [CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your suggestion. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@DeanGross  - Thanks again for your comment. We've added a note stating: Since not all app connectors support all abilities, some rows may be empty.
