### ISSUE TITLE
Prerequisites - Microsoft Defender for Endpoint license - P1 or P2?

### ISSUE THREAD

**Issue by MarkWGH** [MicrosoftDocs/CloudAppSecurityDocs#492]
The prerequisites state: "Microsoft Defender for Endpoint license". Now that Defender for Endpoint P1 has gone GA, is it possible to clarify if this is available with Defender for Endpoint P1? thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a2e9aa-d864-f888-e08e-1d61db4ad75b
* Version Independent ID: 53fbf893-3bee-6320-2112-43818ce778c7
* Content: [Integrate Microsoft Defender for Endpoint with Defender for Cloud Apps](https://docs.microsoft.com/en-us/cloud-app-security/mde-integration)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/mde-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you,.

**Comment by dcurwin** [comment]
@MarkWGH  - Sorry for the delay in the response. We've clarified with the product teams and a Plan 2 license is required.
