### ISSUE TITLE
Missing step to output token with Roles

### ISSUE THREAD

**Issue by kinstlerm** [MicrosoftDocs/CloudAppSecurityDocs#494]
This PS:
# This script acquires the App Context Token and stores it in the variable $token for later use in the script.
# Paste your Tenant ID, App ID, and App Secret (App key) into the indicated quotes below.

$tenantId = '' ### Paste your tenant ID here
$appId = '' ### Paste your Application ID here
$appSecret = '' ### Paste your Application key here

$resourceAppIdUri = '05a65629-4c1b-48c1-a78b-804c4abdd4af'
$oAuthUri = "https://login.microsoftonline.com/$TenantId/oauth2/token"
$authBody = [Ordered] @{
    resource = "$resourceAppIdUri"
    client_id = "$appId"
    client_secret = "$appSecret"
    grant_type = 'client_credentials'
}
$authResponse = Invoke-RestMethod -Method Post -Uri $oAuthUri -Body $authBody -ErrorAction Stop
$token = $authResponse.access_token

Does not output roles in the https://jwt.ms/. It is missing the roles, so Splunk is having an issue connecting.

**Comment by dcurwin** [comment]
Thanks for your feedback. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@kinstlerm - Thanks for your patience. After checking with the product team, it has been determined that there is not a problem with the code sample in the documentation. We recommend you open a support case if you are still having an issue connecting.
