### ISSUE TITLE
URG: Prerequisites: MDE P1 or MDE P2 ?

### ISSUE THREAD

**Issue by donnyatmsft** [MicrosoftDocs/CloudAppSecurityDocs#496]
Can you please update the article, specifying in the Prerequisites MDE license version?

Microsoft Defender for Endpoint **Plan 1** license

or 

Microsoft Defender for Endpoint **Plan 2** license

thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a2e9aa-d864-f888-e08e-1d61db4ad75b
* Version Independent ID: 53fbf893-3bee-6320-2112-43818ce778c7
* Content: [Integrate Microsoft Defender for Endpoint with Defender for Cloud Apps](https://docs.microsoft.com/en-us/cloud-app-security/mde-integration)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/mde-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@donnyatmsft  - Sorry for the delay in the response. We've clarified with the product teams and a Plan 2 license is required.
