### ISSUE TITLE
IP address tags

### ISSUE THREAD

**Issue by ShawnHag** [MicrosoftDocs/CloudAppSecurityDocs#498]
Hi, 
On this page, it saids that "When an IP address is tagged as **corporate**, it is reflected in the portal, and the IP addresses are excluded from triggering specific detections".

What happens if I apply IP addresses with other tags such as "Administrative","Cloud Provider", or "VPN"?
Will it also be excluded from triggering specidific detections?

Thank you in advance,
Shawn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ef412a-b90e-dd0e-4d21-dfdaf87ea155
* Version Independent ID: fb376c81-cd6b-9f13-b2e5-5642f099a364
* Content: [Set IP ranges and tags](https://docs.microsoft.com/en-us/defender-cloud-apps/ip-tags)
* Content Source: [CloudAppSecurityDocs/ip-tags.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/ip-tags.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for your question. We've updated the documentation to make this more clear.

Tagging an IP address as VPN will exclude it from impossible travel detections. The other tags are for administrative purposes.
