### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by romank0l** [MicrosoftDocs/CloudAppSecurityDocs#499]
"If there are no active file policies, then 35 days after the last file page engagement time Defender for Cloud Apps will begin deleting the data of the stored files."
What does it mean will delete data of the stored files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f258bad7-5c1a-ad1d-ee3b-a0298a49d855
* Version Independent ID: c254079f-f5d9-bac4-2966-bcbb8031f1c9
* Content: [Understanding file data and filters available in Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/file-filters)
* Content Source: [CloudAppSecurityDocs/file-filters.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/file-filters.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.
