### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by FFrozTT** [MicrosoftDocs/CloudAppSecurityDocs#50]
What does "Configure your network firewalls and proxies to periodically export logs to the dedicated Syslog port of the FTP directory" mean? What is the Syslog port of the FTP directory???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e21ac1e4-295d-74f4-8217-087203c54bb7
* Version Independent ID: 229ddf62-fd89-8e05-a55a-6a894a57c13a
* Content: [Configure automatic log upload for continuous reports](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by TLinnepe** [comment]
@FFrozTT This means you have to set up the LogCollector IP Address as Syslog Target in your firewall. The the firewall will continously send syslog messages to the LogCollector. Even though you can do it with FTP, when you don't do syslog.
BR, Thomas

**Comment by FFrozTT** [comment]
This is not the intended use case for us.  In fact our use case is very similar to the example provided by Microsoft.  We want to upload Bluecoat logs.  So I have a log file, what do I do with it? I've tried uploading it via FTP to the collector but nothing happens, I have hundreds or thousands of logs now uploaded to that Docker FTP but it's not doing anything with them.

**Comment by rkarlin** [comment]
Hi, thanks for reaching out to us with your questions. Please contact the Cloud App Security team directly with your support question: casfeedback@microsoft.com 
thanks!
Rachel
