### ISSUE TITLE
OAuth 2.0

### ISSUE THREAD

**Issue by safari137** [MicrosoftDocs/CloudAppSecurityDocs#500]
The documentation states that the API requires OAuth 2.0 authentication, but the samples all use OAuth 1.0.

What scope should be used for this API using 2.0?
https://api.securitycenter.microsoft.com/investigation.read does not appear to work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ea95a6-2c03-6b05-fb14-71fd338828ac
* Version Independent ID: 12ea95a6-2c03-6b05-fb14-71fd338828ac
* Content: [Access Defender for Cloud Apps with user context](https://docs.microsoft.com/en-us/defender-cloud-apps/api-authentication-user)
* Content Source: [CloudAppSecurityDocs/api-authentication-user.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/api-authentication-user.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@safari137 - I've spoken to the product team, and they've informed me that this is not likely a documentation issue. That said, if you're having difficulty with authentication, we recommend you open a support case.

We suggest you provide the following information:

- Where are you seeing OAUTH 1.0? As our examples are all OAUTH 2.0
- Why are you directing your calls to SecurityCenter? It should be to portal.cloudappsecurity.
- Please provide an example of the query you are trying to compile, and we can then assess their intentions of what you are trying to do. Please make sure not to include sensitive data in the example.

**Comment by safari137** [comment]
Sorry -- not sure how or why I got this mixed up.  I meant oauth2 v2.

The documentation does not explain how to do this via scope instead of resource.

What is the scope for this app id/resource?  05a65629-4c1b-48c1-a78b-804c4abdd4af

Or is this only available in oauth2 v1?

**Comment by dcurwin** [comment]
Let me check back with the product team.

**Comment by dcurwin** [comment]
We've updated the code sample on the page to request via scope.
