### ISSUE TITLE
Add note for limit to quarantine actions

### ISSUE THREAD

**Issue by ms-smithch** [MicrosoftDocs/CloudAppSecurityDocs#502]
MDCA admin quarantine actions are limited to 100 actions/day. This limit can be increased with a support case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c5bcbb-0fc8-b147-5268-4f77c6d90527
* Version Independent ID: 3cbf459a-6267-c899-2e19-1df475b1adc0
* Content: [Protect files with Defender for Cloud Apps admin quarantine tutorial](https://docs.microsoft.com/en-us/defender-cloud-apps/use-case-admin-quarantine)
* Content Source: [CloudAppSecurityDocs/use-case-admin-quarantine.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/use-case-admin-quarantine.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your suggestion. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@ms-smithch Thanks for your contribution. We've added the information you mentioned to a note on that page.
