### ISSUE TITLE
security improvement

### ISSUE THREAD

**Issue by Degies** [MicrosoftDocs/CloudAppSecurityDocs#503]
What this page needs is a blurb on how to secure the docker image. The app left open in this state allows for a actor on the network to send it fake syslog entries. There needs to be a way to secure it better. It could be a simple blurb to state how the VM firewall must be configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e21ac1e4-295d-74f4-8217-087203c54bb7
* Version Independent ID: 229ddf62-fd89-8e05-a55a-6a894a57c13a
* Content: [Configure automatic log upload using on-premises Docker](https://docs.microsoft.com/en-us/defender-cloud-apps/discovery-docker-ubuntu?tabs=centos#prerequisites)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your suggestion. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@Degies  - Thanks again for your comment. We've updated the page with the requested content:

https://learn.microsoft.com/en-us/defender-cloud-apps/log-collector-advanced-management#restrict-ip-addresses-sending-syslog-messages-to-the-log-collector-on-linux
