### ISSUE TITLE
Link to Sentinel documentation is incorrect post product rename

### ISSUE THREAD

**Issue by jbrysonMSFT** [MicrosoftDocs/CloudAppSecurityDocs#504]
The link to get to the Sentinel docs to set up the MCAS connector is incorrect post rename.  

Step 4 here:
https://docs.microsoft.com/en-us/defender-cloud-apps/siem-sentinel#how-to-integrate

Links to this: 
https://docs.microsoft.com/en-us/azure/sentinel/data-connectors-reference#microsoft-cloud-app-security-mcas

It should be this link: 
https://docs.microsoft.com/en-us/azure/sentinel/data-connectors-reference#microsoft-defender-for-cloud-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7baccc9-aded-5134-33bf-bdd20ca52637
* Version Independent ID: 2c646a17-0782-0352-ced5-822354a68271
* Content: [Microsoft Sentinel integration with Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/siem-sentinel)
* Content Source: [CloudAppSecurityDocs/siem-sentinel.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/siem-sentinel.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks, we've updated the link.
