### ISSUE TITLE
When will Mac support be available？

### ISSUE THREAD

**Issue by shmatsuy** [MicrosoftDocs/CloudAppSecurityDocs#505]
[Enter feedback here]
At Ignite, it was announced that Mac support for MDE's MCAS integration has been GA'd. When will this be reflected in Docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a2e9aa-d864-f888-e08e-1d61db4ad75b
* Version Independent ID: 53fbf893-3bee-6320-2112-43818ce778c7
* Content: [Integrate Microsoft Defender for Endpoint with Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/mde-integration#feedback)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/mde-integration.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.
