### ISSUE TITLE
Useless information

### ISSUE THREAD

**Issue by crshovrd41** [MicrosoftDocs/CloudAppSecurityDocs#507]
Nowhere in your documentation does it actually tell me the URL or IP where I should send my logs to. How on Earth are people using this service with this junk documentation? Very frustrating. I've been searching for an hour and have come up empty handed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e0555c-41e5-0ba3-4c4b-f9c386644a72
* Version Independent ID: 876888bc-8046-0a25-a0b7-67f938cc45c1
* Content: [Configure automatic log upload for continuous reports in Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/discovery-docker)
* Content Source: [CloudAppSecurityDocs/discovery-docker.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@crshovrd41  - Thanks again for your comment. The answer to your question, is the Docker is configured with the IP the logs will be sent to.
