### ISSUE TITLE
Certificate terminology is unclear

### ISSUE THREAD

**Issue by juhagler** [MicrosoftDocs/CloudAppSecurityDocs#508]
_To install root certificates
Repeat the following steps to install the Current CA and Next CA self-signed root certificates._

Discussed with TA - we should be using the terminology "root" and "intermediate" rather than current and next.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18085b0-ca97-5623-fc42-5395acf55f1f
* Version Independent ID: 942d682c-a471-a8c9-e12f-cc7d4aafbad3
* Content: [Support and troubleshooting information for Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/support-and-ts#feedback)
* Content Source: [CloudAppSecurityDocs/support-and-ts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/support-and-ts.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again - we've updated the terminology on the page.
