### ISSUE TITLE
Supported Ubuntu Versions

### ISSUE THREAD

**Issue by goosvorbook** [MicrosoftDocs/CloudAppSecurityDocs#509]
Hi Microsoft,

It seems that automatic log upload for continuous reports in Defender for Cloud Apps supports to be running on Ubuntu LTS versions (14.04, 16.04 and 18.04) but _not_ on 20.04. I was wondering if this is a mistake in the documentation or if this is really an unsupported scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e21ac1e4-295d-74f4-8217-087203c54bb7
* Version Independent ID: 229ddf62-fd89-8e05-a55a-6a894a57c13a
* Content: [Configure automatic log upload using on-premises Docker](https://docs.microsoft.com/en-us/defender-cloud-apps/discovery-docker-ubuntu?tabs=centos)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/discovery-docker-ubuntu.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@goosvorbook  - I got an answer from the product team, and 20.04 is supported. I've updated the documentation accordingly.

Thank you for your contribution!
