### ISSUE TITLE
Non-existent setting 

### ISSUE THREAD

**Issue by lkchild** [MicrosoftDocs/CloudAppSecurityDocs#510]
The document states "To configure the severity for alerts sent to Microsoft Defender for Endpoint: In Defender for Cloud Apps, select the Settings icon, and then select Microsoft Defender for Endpoint."

There is no settings icon present in Defender for Cloud Apps any more, hence I'm stuck!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a2e9aa-d864-f888-e08e-1d61db4ad75b
* Version Independent ID: 53fbf893-3bee-6320-2112-43818ce778c7
* Content: [Integrate Microsoft Defender for Endpoint with Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/mde-integration)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/mde-integration.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. There was a step missing. After selecting the settings (cog) icon in the top right corner, select **Settings** and then that will take you to the Defender for Endpoint settings. I've updated the documentation.
