### ISSUE TITLE
Listing Alerts

### ISSUE THREAD

**Issue by BENABRAHA** [MicrosoftDocs/CloudAppSecurityDocs#511]
Filter used to return a specific severity alert from MCAS is not properly functioning. For example if I provide "Severity" eq "0" and submit to cloudapps via a powershell rest api calls, it reurns medium alerts as well.

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@BENABRAHA - Is this a documentation issue? If so, can you provide the page where the problematic documentation occurs? 

If this isn't a documentation issue, but rather a problem with the product, we recommend you open a support ticket.

**Comment by dcurwin** [comment]
@BENABRAHA  - Hi, we haven't heard back from you, so I'm going to close the GitHub issue. If you later would like to provide an answer, let me know, and if it is indeed related to documentation, I'll reopen it. 

Thanks.
