### ISSUE TITLE
Not able to setup salesforce connection with CloudAppSecurity

### ISSUE THREAD

**Issue by jamesyip** [MicrosoftDocs/CloudAppSecurityDocs#513]
Steps are not correct. follow the steps cannot successfully setup the connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88294d23-b573-bb18-d6f9-65a06614b0d5
* Version Independent ID: 1a87274f-14b2-393c-f535-b571748817a2
* Content: [Connect Salesforce to Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/connect-salesforce)
* Content Source: [CloudAppSecurityDocs/connect-salesforce.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/connect-salesforce.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

If you can provide more details about what didn't work, that will help us correct the documentation faster.

**Comment by jamesyip** [comment]
I found few issues:
1. The steps only ask us create profile but no mention to assign to any
users
2. No mention cannot use system administrator to do the linkage as one
permission missed which cannot be modified

Thanks,

James

**Comment by dcurwin** [comment]
Thank you for your question, and we appreciate your patience.

The product team has informed me that the connector will be updated to reflect the accurate permissions. When this is completed the documentation will be updated.
