### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by mgowing** [MicrosoftDocs/CloudAppSecurityDocs#514]
Is there anyway the doc can clarify if the licensing is an add-on tenant license, or an add-on user license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1fa045c-9edd-2d50-8c55-25b5be8ec9c8
* Version Independent ID: d1fa045c-9edd-2d50-8c55-25b5be8ec9c8
* Content: [Get Started with app governance](https://docs.microsoft.com/en-us/defender-cloud-apps/app-governance-get-started)
* Content Source: [CloudAppSecurityDocs/app-governance-get-started.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/app-governance-get-started.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@mgowing - I just realized that while we updated the documentation months ago, we didn't inform you here. Sorry for the delay.
