### ISSUE TITLE
Error in "Impossible Travel" regarding 'corporate' IP addresses

### ISSUE THREAD

**Issue by P-Ron** [MicrosoftDocs/CloudAppSecurityDocs#515]
Documentation in Knowledge Base says:

•	When the IP addresses on both sides of the travel are considered safe, the travel is trusted and excluded from triggering the Impossible travel detection. For example, both sides are considered safe if they are tagged as corporate. However, if the IP address of only one side of the travel is considered safe, the detection is triggered as normal.

However, i get numerous impossible travel alerts when both IP addresses are tagged corporate.  The alert itself says:

If any of these IP addresses are used by the organization for VPN connections and do not necessarily represent a physical location, we recommend categorizing them as VPN in the IP Address range page in Microsoft Defender for Cloud Apps portal to avoid false alerts.

So the documentation regarding corporate tagging should say VPN tagging.  

This is problematic: If I go retag my corporate addresses then it could affected other policies that filter using IP category

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3543307c-9c07-720c-e4fe-3aa6cb43f680
* Version Independent ID: df363f37-c41a-7493-6573-c7a8f4ff1aaf
* Content: [Control which third-party cloud OAuth apps get permissions](https://docs.microsoft.com/en-us/defender-cloud-apps/manage-app-permissions)
* Content Source: [CloudAppSecurityDocs/manage-app-permissions.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/manage-app-permissions.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@P-Ron Thank you again for your comment. I checked with the product group, and they said that the documentation is correct, but if you are experiencing this issue, they recommend you open a support ticket, and the support teams will help you.
