### ISSUE TITLE
Screenshots are out of date

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/CloudAppSecurityDocs#517]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 761bb043-6da5-7c36-02af-76be128250b6
* Version Independent ID: 7ebda947-3455-2af3-17ad-b385bac60827
* Content: [Create policies to control OAuth apps in Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/app-permission-policy)
* Content Source: [CloudAppSecurityDocs/app-permission-policy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/app-permission-policy.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We've updated the screenshots.
