### ISSUE TITLE
Missing templates

### ISSUE THREAD

**Issue by lkchild** [MicrosoftDocs/CloudAppSecurityDocs#519]
This page is missing a number of templates, such as all of the session templates (unless there's a different page?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0192fe47-4af3-0a7b-74a1-efbe7ad7536a
* Version Independent ID: 34ff03e6-aadf-638d-1b9f-30b999b19240
* Content: [Policy template reference for Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/policy-template-reference)
* Content Source: [CloudAppSecurityDocs/policy-template-reference.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/policy-template-reference.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.
