### ISSUE TITLE
Instructions incorrect

### ISSUE THREAD

**Issue by ivassallo19** [MicrosoftDocs/CloudAppSecurityDocs#520]
I understand that both M365 interfaces, and Salesforce interfaces, update over time, so just looking to have this updated as of Jan 2022.

First issue:
In this document, these steps are incorrect.:
'Choose the profile you just created to deploy Defender for Cloud Apps and select Edit'
That Edit link (shown in the screenshot) is to edit the View called All Profiles, not to edit the profile.

The correct steps would be to:
1. Click the Name of the new profile
2. Under System, click on System Permissions
3. Click Edit
4. Enable these permissions:
  - API Enabled
  - View All Data
  - Manage Users
5. Click Save
6. Under Apps, click App Permissions
7. Click Edit
8. Enable these permissions:
- Manage Salesforce CRM Content
- Query All Files
9. Click Save

Second issue:
These steps are incorrect.:
g. 'Go to Build -> Customize -> Salesforce Files -> Settings -> Content Deliveries and Public Links.'
h. Select Edit and then select Checked Content Deliveries feature can be enabled for users
i. Select Save.

The correct steps would be:
g. Go to Feature Settings > Salesforce Files > Content Deliveries and Public Links
h. Check 'Content Deliveries feature can be enabled for users'
i. Select Save.

Third issue:
The step '5. In the App connectors page, select the plus button followed by Salesforce.', the screenshot needs updating.
The step '6. In the Salesforce settings page, on the API tab, select Follow this link, depending on which instance you want to install.' not sure where in the Salesforce API page is 'Follow this link', but in the current Defender for Cloud process, once you click Add > Salesforce, it asks for the Salesforce instance name, then click Connect Salesforce, then click either 'For production, follow this link' or 'For sandbox, follow this link'. It then takes you to Salesforce for login, authorization, etc.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88294d23-b573-bb18-d6f9-65a06614b0d5
* Version Independent ID: 1a87274f-14b2-393c-f535-b571748817a2
* Content: [Connect Salesforce to Defender for Cloud Apps](https://docs.microsoft.com/en-gb/defender-cloud-apps/connect-salesforce?redirectedfrom=MSDN)
* Content Source: [CloudAppSecurityDocs/connect-salesforce.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/connect-salesforce.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for your question, and we appreciate your patience. 

The product team has informed me that the connector will be updated to reflect the accurate permissions. When this is completed the documentation will be updated.
