### ISSUE TITLE
Change on-premise

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/CloudAppSecurityDocs#525]
Can we please change "on-premise" to be on-premises so that it is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c63d7347-1a92-e11e-7ddb-17cef8dea730
* Version Independent ID: f9b88d31-9dd1-d0a5-6142-2feaae9f98f1
* Content: [Deploy Conditional Access App Control custom apps with Azure Active Directory](https://docs.microsoft.com/en-us/defender-cloud-apps/proxy-deployment-any-app#configure-integration-with-azure-ad)
* Content Source: [CloudAppSecurityDocs/proxy-deployment-any-app.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/proxy-deployment-any-app.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@r-milne Thanks again for your suggestion. We've corrected the document.
