### ISSUE TITLE
New Docker license model

### ISSUE THREAD

**Issue by CAT-hs** [MicrosoftDocs/CloudAppSecurityDocs#526]
I recently rebooted my collector server and when docker started it prompted to update, then after the update it said a paid license is required under certain circumstances. We aren't doing anything else with this Docker install (would rather not use it at all if that were an option) and I can't tell where I would apply a license to the install if I had one. I'm concerned it will stop working or no longer get critical updates at the end of the "grace period" they are in right now.

**Comment by dcurwin** [comment]
@CAT-hs  -   This isn't a documentation issue, and requires further investigation. The best way to get help is to open a support ticket.

**Comment by CAT-hs** [comment]
That is a fair point, but what users should do about warnings in a third party tool MS required us to install for this functionality should be documented IMO.

**Comment by dcurwin** [comment]
@CAT-hs  - If you can provide me details about the collector server and preferably the warning you received, then I can check if there is anything to update in the documentation.

**Comment by CAT-hs** [comment]
I restarted Docker and it didn't give the pop-up message this time, and I don't see anything about it in the about screen. I believe it is related to this Docker blog post https://www.docker.com/blog/updating-product-subscriptions/ 

What I can screenshot is the Docker tray menu, which under the 'caslogcollector' item now shows "Team Tier" at the top of the submenu, which looks like one of the licensing tiers mentioned in the above blog post.
![image](https://user-images.githubusercontent.com/45440128/154106997-2df40e7e-fdf2-4f2e-a058-31e6d180fe9f.png)

I have also opened a support case.

**Comment by dcurwin** [comment]
@CAT-hs Ok, I'll look into the issue and see if the documentation should be updated.

**Comment by dcurwin** [comment]
@CAT-hs Can you provide the support case number?

**Comment by CAT-hs** [comment]
Support request ID 2202150040006810

**Comment by dcurwin** [comment]
@CAT-hs 
After consulting further with the product team, they've determined that this isn't a documentation issue. The best way to get help is to continue working with support.
