### ISSUE TITLE
Benchmark for AWS

### ISSUE THREAD

**Issue by RoniTabuzo-EY** [MicrosoftDocs/CloudAppSecurityDocs#528]
[Enter feedback here]
What's the CIS version and hardening level for AWS Benchmark? Can we choose a template based on the hardening level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dd9ecf4-386c-9d85-d4ff-13d4404b99a2
* Version Independent ID: d638e37f-15dd-86d3-abbe-79eb7fa0de44
* Content: [How Defender for Cloud Apps helps protect your Amazon Web Services environment](https://docs.microsoft.com/en-us/defender-cloud-apps/protect-aws#feedback)
* Content Source: [CloudAppSecurityDocs/protect-aws.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/protect-aws.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back you.

**Comment by dcurwin** [comment]
The CSPM capabilities of Defender for Cloud Apps are being transitioned to Microsoft Defender for Cloud. Therefore, we won't be updating the documentation at this time. For more information about Defender for Cloud's CSPM features, see https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-cloud-introduction.
