### ISSUE TITLE
Benchmark for GCP

### ISSUE THREAD

**Issue by RoniTabuzo-EY** [MicrosoftDocs/CloudAppSecurityDocs#529]
[Enter feedback here]

What's the CIS version and hardening level for GCPBenchmark? Can we choose a template based on the hardening level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808eab20-96ce-d5c4-41be-ea5475a0c6bf
* Version Independent ID: 1eef009c-a54e-2038-59b6-30c21eb5797a
* Content: [How Defender for Cloud Apps helps protect your Google Cloud Platform environment](https://docs.microsoft.com/en-us/defender-cloud-apps/protect-gcp)
* Content Source: [CloudAppSecurityDocs/protect-gcp.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/protect-gcp.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.
