### ISSUE TITLE
Unclear details on Supported Browser versions for Session Controls

### ISSUE THREAD

**Issue by niolmstead** [MicrosoftDocs/CloudAppSecurityDocs#530]
The verbiage regarding supported browsers for session controls is not clear.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/31769159/155382826-b77088b2-d6ab-4a4c-800a-7819bdc190da.png">

This seems to indicate that the any version other than the latest would not be supported.  In the docs page talking about Activity Filters we see the following:
"Defender for Cloud Apps considers outdated as two major versions older than the current version. For example, if the current version of Edge is 90, then version 88 and earlier are outdated."
 https://docs.microsoft.com/en-us/defender-cloud-apps/activity-filters-queries#activity-filters

It would be helpful to provide more specific details on what is a supported browser version for Session Controls and what the ramifications are for running an older version.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect with Microsoft Defender for Cloud Apps Conditional Access App Control](https://docs.microsoft.com/en-us/defender-cloud-apps/proxy-intro-aad?source=docs)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.
