### ISSUE TITLE
Roadmap for new apps

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/CloudAppSecurityDocs#531]
It would be great if this page described why there are only a limited number of Connected Apps available. Should we expect more apps to appear over time and is there a public roadmap that could be linked to?
In my case, my client is using SaaS from Oracle (HR, Fusion Finance etc) and wanted to connect that MDCA. Is that possible? What should an admin do in the situation when the app they want to connect isn't listed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae7d409-a4f0-8c66-9a4d-ef6d7d5219ef
* Version Independent ID: 7894f069-c9a0-f356-b559-cd49f1cdbd9b
* Content: [Protect apps in your environment using cloud service provider APIs](https://docs.microsoft.com/en-us/defender-cloud-apps/protect-connected-apps)
* Content Source: [CloudAppSecurityDocs/protect-connected-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/protect-connected-apps.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your question. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@thommck - Thanks again for your question. We don't include information about future features and releases in our documentation, but you can view the Microsoft 365 roadmap here:

https://www.microsoft.com/en-us/microsoft-365/roadmap

Additionally, you can suggest a new app on the **Connected Apps** page. Under **Connect an app**, scroll to the bottom and select **Suggest more apps...**.
