### ISSUE TITLE
Typo correction

### ISSUE THREAD

**Issue by Shoehorner** [MicrosoftDocs/CloudAppSecurityDocs#533]
Typo on this page in the following section:

```
Detail: To gain additional visibility into activities from your line-of-business apps, you can onboard custom apps to Defender for Cloud Apps. Once custom apps are configured, you see information about whose using them
```

This line should be fixed to this:
```
Detail: To gain additional visibility into activities from your line-of-business apps, you can onboard custom apps to Defender for Cloud Apps. Once custom apps are configured, you see information about who's using them
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e4354-bfb5-1b0a-d6d6-734290a15963
* Version Independent ID: 62d41ec5-f48d-d7fb-406a-2810a4ff4fbc
* Content: [Best practices for protecting your organization](https://docs.microsoft.com/en-us/defender-cloud-apps/best-practices#detect-cloud-threats-compromised-accounts-malicious-insiders-and-ransomware)
* Content Source: [CloudAppSecurityDocs/best-practices.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/best-practices.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@Shoehorner  - Thank you for your correction. I've updated the document.
