### ISSUE TITLE
Conditional Access App Control - Dynamics 365

### ISSUE THREAD

**Issue by nickselvaggio** [MicrosoftDocs/CloudAppSecurityDocs#534]
In the known limitations section of this article, there's a reference to 'Applications may break' that includes Microsoft Dynamics 365 CRM, but it's also listed as a Pre-onboarded app.

Is it possible to get further information on exactly which functionality may not work when Dynamics 365 CRM is used with Conditional Access App Control, and whether this more broadly applies to Dataverse apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect with Microsoft Defender for Cloud Apps Conditional Access App Control](https://docs.microsoft.com/en-us/defender-cloud-apps/proxy-intro-aad#known-limitations)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks again for your question. We've updated the documentation to be more specific. It now notes that we've encountered scenarios where navigating to a link may result in loss of the full path of the link and typically the user lands on the home page of the app.
