### ISSUE TITLE
Advanced Configuration does not exist for the "infrequent country" policy

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/CloudAppSecurityDocs#535]
Quote from the doc:
"For example, you can customize the infrequent country policy to only alert successful sign-ins from locations that were not recently visited by any user in your organization. You can achieve this by editing the policy and under Advanced configuration, set Analyze sign-in activities to one of the successful sign-in options."

There is no "Advanced Configuration" in the infrequent country, there is no way to tune it. Same for "impossible travel", you can change the sensitivity, but there is no "Advanced Configuration" where you can select "successful sign-ins" or "Failed Logon".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4e03e45-c169-67b4-b0f1-03597040bf0d
* Version Independent ID: 197ab35b-a26a-c186-8949-d1828303ca9f
* Content: [Detect suspicious user activity with behavioral analytics (UEBA) tutorial](https://docs.microsoft.com/en-us/defender-cloud-apps/tutorial-suspicious-activity)
* Content Source: [CloudAppSecurityDocs/tutorial-suspicious-activity.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/tutorial-suspicious-activity.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your comment. We've updated the doc.
