### ISSUE TITLE
Images out of data for adding connectors

### ISSUE THREAD

**Issue by andrew-velez-trusight** [MicrosoftDocs/CloudAppSecurityDocs#536]
The images for the connectors is either out of date, or is not applicable to all users. When I go to the SIEM agents tab, I don't see the add button as you show, I see this. 

![image](https://user-images.githubusercontent.com/60942200/159709071-b8020ee2-2591-4902-99b8-b442af789314.png)

When I click Add SIEM agent, I don't see an option for Sentinel, I see this: 
![image](https://user-images.githubusercontent.com/60942200/159709259-a8df60c2-e70d-42b4-8749-33b69b82ce92.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7baccc9-aded-5134-33bf-bdd20ca52637
* Version Independent ID: 2c646a17-0782-0352-ced5-822354a68271
* Content: [Microsoft Sentinel integration with Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/siem-sentinel)
* Content Source: [CloudAppSecurityDocs/siem-sentinel.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/siem-sentinel.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@andrew-velez-trusight  
After a review, we've determined that this isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.
