### ISSUE TITLE
Google Proxy Steps are not correct 

### ISSUE THREAD

**Issue by jacksondcampbell** [MicrosoftDocs/CloudAppSecurityDocs#537]
[Enter feedback here]
The google proxy steps on this page are incorrect. They need to be adjusted/updated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786477c5-9588-bef4-d273-f53446b151c7
* Version Independent ID: 73f6ee70-27a3-d972-f14c-1bd30e59c17c
* Content: [Troubleshooting access and session controls](https://docs.microsoft.com/en-us/defender-cloud-apps/troubleshooting-proxy)
* Content Source: [CloudAppSecurityDocs/troubleshooting-proxy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/troubleshooting-proxy.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@jacksondcampbell  - The product team has asked for further clarifications. Can you explain in more detail what issues you have with the steps?

**Comment by dcurwin** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
