### ISSUE TITLE
License required?

### ISSUE THREAD

**Issue by derekharkin** [MicrosoftDocs/CloudAppSecurityDocs#54]
Please add information on the specific licensing needed to use this feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect with Microsoft Cloud App Security Conditional Access App Control](https://docs.microsoft.com/en-us/cloud-app-security/proxy-intro-aad)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@derekharkin Thanks for the feedback. I'll add it to the page. Until it goes live, if you didn't know: 
To use Cloud App Security Conditional Access App Control, you need an Azure Active directory P1 license and an active Microsoft Cloud App Security subscription.
thanks!
