### ISSUE TITLE
Customizing the risk score Lists 4 and not 3

### ISSUE THREAD

**Issue by Donovand4** [MicrosoftDocs/CloudAppSecurityDocs#546]
The Customizing the risk score mentions that the score is a calculation of 3 factors but lists 4 factors within the explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c81376b-bf8e-4e45-056e-515732d49e02
* Version Independent ID: ed7148a0-d390-dc0c-68a0-b33724e87da0
* Content: [Working with the risk score](https://docs.microsoft.com/en-us/defender-cloud-apps/risk-score#customizing-the-risk-score)
* Content Source: [CloudAppSecurityDocs/risk-score.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/risk-score.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@Donovand4 - Thanks for the comment. The page has been updated.
