### ISSUE TITLE
Tenant region code is hard to find

### ISSUE THREAD

**Issue by sumityadavs7y** [MicrosoftDocs/CloudAppSecurityDocs#547]
Even after hours of searching i am not able to find tenant region code. i know my app is on 'united states of america' but what is the region code, I dont know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1313c4-061d-5ea3-aaef-adbcd6fd8766
* Version Independent ID: 47bcaec7-6c7c-72d9-fa58-08838e27b039
* Content: [Close benign - Alerts API](https://docs.microsoft.com/en-us/defender-cloud-apps/api-alerts-close-benign)
* Content Source: [CloudAppSecurityDocs/api-alerts-close-benign.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-alerts-close-benign.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
There are instructions on finding your tenant ID on these pages:

https://docs.microsoft.com/en-us/defender-cloud-apps/api-introduction
https://docs.microsoft.com/en-us/defender-cloud-apps/api-authentication-application

If you need additional support, the best way to get help is to open a support ticket.
