### ISSUE TITLE
"both" confusing and not needed

### ISSUE THREAD

**Issue by brucelangston** [MicrosoftDocs/CloudAppSecurityDocs#558]
The line "_File type – Defender for Cloud Apps takes both the MIME type received (see table) from the service and scans the file to determine the true file type._" does not need the word "both." Placing the word "both" after "takes" implies that two things are "taken." In fact, the rest of the sentence specifies one thing that is taken, and that is "MIME type." A better version of the sentence is 

"_Defender for Cloud Apps takes the MIME type received (see table) from the service and scans the file to determine the true file type._"

The word "_takes_" is not really appropriate or needed. An even better version of the sentence is 

"_Defender for Cloud Apps scans the file to determine whether the true file type matches the MIME type received (see table) from the service._"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f258bad7-5c1a-ad1d-ee3b-a0298a49d855
* Version Independent ID: c254079f-f5d9-bac4-2966-bcbb8031f1c9
* Content: [Understanding file data and filters available in Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/file-filters)
* Content Source: [CloudAppSecurityDocs/file-filters.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/file-filters.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for your comment. The page has been updated.
