### ISSUE TITLE
Syslog - TLS

### ISSUE THREAD

**Issue by erikdah** [MicrosoftDocs/CloudAppSecurityDocs#56]
As you note: "Integrating with secure transfer protocols (FTPS and Syslog – TLS) often requires additional settings or your firewall/proxy."
Which is correct, you would in most cases need to trust the certificate presented by the syslog server.
In this case, it is a self signed certificate, and I get this error when I try to import it: "Import of CAS syslog failed. Only self signed CA certificates can have identical subject and issuer fields."
Where is the certificate located, and how do I replace it with a certificate signed by our own CA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 818cbf6b-c397-8c86-e061-8e940ee94278
* Version Independent ID: 53b66b18-5321-b63e-a57b-44f146ff6944
* Content: [Configure automatic log upload for continuous reports](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu-azure)
* Content Source: [CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-ubuntu-azure.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi Eric, thanks for your question. We documented that information here: https://docs.microsoft.com/cloud-app-security/troubleshoot-docker#customize-certificate-files 
Let me know if you don't find what you need.
thanks!

**Comment by maestra-msft** [comment]
Resource Not Found.
The URL listed above https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-ubuntu-azure  is not valid, the Docker image is no longer available there. Could you please provide the right one or even better, update the article accordingly? Thank you.

**Comment by maestra-msft** [comment]
I'm sorry, I meant to say the Docker URL : https://adaprodconsole.blob.core.windows.net/public-files/MCASInstallDocker.sh
