### ISSUE TITLE
Unable to connect GCP in App Connector and Security configurations apps

### ISSUE THREAD

**Issue by varunchandak** [MicrosoftDocs/CloudAppSecurityDocs#561]
Despite following the connector doc for GCP, it seems that some permissions are missing to get it connected

<img width="937" alt="image" src="https://user-images.githubusercontent.com/18713091/173820844-f5a8af04-fdfb-4afa-938d-ad88b6eff322.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/18713091/173821502-772a0164-f194-42cc-9187-e931316036a8.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c93906-0f8a-a2d6-c542-d80ee38f9c75
* Version Independent ID: 1e647883-2470-ee9a-2f6b-c2172f7f190d
* Content: [Connect Google Cloud Platform to Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/connect-google-gcp)
* Content Source: [CloudAppSecurityDocs/connect-google-gcp.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/connect-google-gcp.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.
