### ISSUE TITLE
Access Policy is left out?

### ISSUE THREAD

**Issue by ilirianluta** [MicrosoftDocs/CloudAppSecurityDocs#562]
You mention that two kinds of policies should be created: Access Policy AND Session Policy, yet only the Session policy creation process is explained. What about Access Policy? I'm having a hard time excluding AzureAD-joined devices from being affected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b8ca2a3-a0e8-802a-e79f-737e8f1735ea
* Version Independent ID: a052f0f9-8ca5-3499-9c33-40dd4315ffe8
* Content: [Block downloads from unmanaged devices with Defender for Cloud Apps Conditional Access App Control tutorial](https://docs.microsoft.com/en-us/defender-cloud-apps/use-case-proxy-block-session-aad)
* Content Source: [CloudAppSecurityDocs/use-case-proxy-block-session-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/use-case-proxy-block-session-aad.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you again for your comment. We've added a link here to the article which explains how to create an Access Policy:

https://docs.microsoft.com/en-us/defender-cloud-apps/use-case-proxy-block-session-aad#create-a-block-download-policy-for-unmanaged-devices
