### ISSUE TITLE
Contradiction about blocking apps

### ISSUE THREAD

**Issue by mav147** [MicrosoftDocs/CloudAppSecurityDocs#564]
Part of this document states, unsanctioning an app won't block it, but is useful for monitoring

> You can unsanction a specific risky app by clicking the three dots at the end of the row. Then select Unsanction. Unsanctioning an app doesn't block use, but enables you to more easily monitor its use with the Cloud Discovery filters.

Later it states the opposite, to unsanction an app to block it

> To block an app, do the following steps:
In Defender for Cloud Apps, under Discover, go to the Discovered apps page.
Select the app that should be blocked.
Tag the app as Unsanctioned.
To block all the devices in your organization, select Save. To block specific device groups in your organizations, select Select a profile to include or exclude groups from being blocked. Then choose the profile for which the app will be blocked, and select Save.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77ab1f7-e882-65ed-8763-2ca0e7f2d3a6
* Version Independent ID: decde69d-a97a-6eb5-c98a-a7f93fe80793
* Content: [Blocking discovered apps](https://docs.microsoft.com/en-us/defender-cloud-apps/governance-discovery)
* Content Source: [CloudAppSecurityDocs/governance-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/governance-discovery.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@mav147  - Thanks again for your comment. We've updated the document to provide greater clarity.
