### ISSUE TITLE
Source of risk score

### ISSUE THREAD

**Issue by teavanist** [MicrosoftDocs/CloudAppSecurityDocs#569]
Hi there! 
How does Microsoft get information about compliance standards followed by SaaS apps? For example if a SaaS  app is listed with an ISO 27001 and SOC2 certification:
- is this information acquired via scraping their website or 
- do you have some way of verifying whether they have a valid certificate or 
- do the SaaS app makers inform Microsoft that they have such certifications? 
This is a very useful feature but it would be nice to know how you collect this Information and your process for validating it.

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@teavanist  - Thank you for your patience. I asked the product group your question, and they pointed me to this page which explains how the cloud app catalog is updated:

https://docs.microsoft.com/en-us/defender-cloud-apps/risk-score#the-cloud-app-catalog

In addition, they provided me these answers to your specific questions:

**Is this information acquired via scraping their website or** – Yes, information is manually scraped by our cloud analysts by visiting their websites.
**Do you have some way of verifying whether they have a valid certificate or** – No, except for a few indicators like CSA Star certification and FedRAMP level etc. that can be verified from third party websites.
**do the SaaS app makers inform Microsoft that they have such certifications?** Only in the case of self-attested apps.  We have some apps that are self-attested by the app makers. We have a link to the form in the documentation, that the app vendors can fill in and submit. Once we receive their submission, we review and reach out to the vendor if we have any feedback or follow up questions. Then, once we have clarified all questions, we go ahead and publish the information in the catalog.
