### ISSUE TITLE
Is Cloud Discover available for Cloudflare Gateway? - On Microsoft Defender for Cloud Apps 

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/CloudAppSecurityDocs#570]
Hiya,

Is Cloud Discover available for [Cloudflare Gateway](https://www.cloudflare.com/products/zero-trust/gateway/)? - On Microsoft Defender for Cloud Apps

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2005aabb-11c8-3ab9-6e87-94b0ef5164be
* Version Independent ID: 0878ecbe-fcd1-eb38-8ddb-4b4ea685d3c0
* Content: [Deploy Cloud Discovery](https://docs.microsoft.com/en-us/defender-cloud-apps/set-up-cloud-discovery)
* Content Source: [CloudAppSecurityDocs/set-up-cloud-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/set-up-cloud-discovery.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@haneef95 

We do not have a dedicated parser for Cloudfare Gateway.
Please see all the parsers we support: [Deploy Cloud Discovery | Microsoft Docs](https://docs.microsoft.com/en-us/defender-cloud-apps/set-up-cloud-discovery#supported-firewalls-and-proxies).

You can create a custom parser: [Defender for Cloud Apps custom log parser for logs that aren't supported | Microsoft Docs](https://docs.microsoft.com/en-us/defender-cloud-apps/custom-log-parser).

The product team welcomes your feedback on creating customer parsers.

**Comment by haneef95** [comment]
Thank you.

Would be good if there's an automated option for Cloudflare Gateway too
