### ISSUE TITLE
tune anomaly detection policies - text and table contradiction

### ISSUE THREAD

**Issue by LeonB87** [MicrosoftDocs/CloudAppSecurityDocs#571]
Greetings,

At the **tune anomaly detection policies** section, the text and table seem to contradict each other.

The text states: **_For example, if you set it to low, it will suppress Impossible Travel alerts from a user's common locations_**

the table states that the "Medium" switch already accounts for **user suppressions** and that setting this to low, only adds the **_tenant_** suppression.
 
This might need some clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395e085f-93bd-1f3c-fe0d-7711b6d51950
* Version Independent ID: ad86d15d-41a5-9a6e-8d30-18ed9a9975f2
* Content: [Create anomaly detection policies in Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/anomaly-detection-policy#tune-anomaly-detection-policies)
* Content Source: [CloudAppSecurityDocs/anomaly-detection-policy.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/anomaly-detection-policy.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you again for your comment. We've updated the documentation indicate that changing to both low and medium includes user supression.
