### ISSUE TITLE
"Office 365 Azure AD apps are enabled" is Unclear

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/CloudAppSecurityDocs#572]
In the "Enable Defender for Cloud Apps sync" section, step #2 (Ensure Office 365 Azure AD apps are enabled) is unclear. What exactly is an Office 365 Azure AD app, and how do I ensure they are enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1fa045c-9edd-2d50-8c55-25b5be8ec9c8
* Version Independent ID: d1fa045c-9edd-2d50-8c55-25b5be8ec9c8
* Content: [Get Started with app governance](https://docs.microsoft.com/en-us/defender-cloud-apps/app-governance-get-started)
* Content Source: [CloudAppSecurityDocs/app-governance-get-started.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/app-governance-get-started.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by franklesniak** [comment]
After doing some research, I think that "Ensure Office 365 apps are enabled" means something along the lines of "Ensure there is at least one Azure AD-integrated application enabled that accesses Office 365 data." -- though that may not be actionable without some additional information on what type of Azure AD app is being referenced, how to tell it's accessing Office 365 data, etc.

**Comment by dcurwin** [comment]
@franklesniak  - Thanks again for your comment. We've updated that step to say "Ensure there is at least one OAuth-enabled application that accesses Office 365 data registered in Azure AD."
