### ISSUE TITLE
Need to be explicit about permissions needed to hit this endpoint. 

### ISSUE THREAD

**Issue by joey-mcadams** [MicrosoftDocs/CloudAppSecurityDocs#575]
It's not clear what permissions are needed to hit this endpoint. (Still trying to figure that out...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e8cef3-b884-a61b-2784-e7cbffc262a6
* Version Independent ID: 380b9051-bb14-69b2-95bc-7100071359aa
* Content: [List - Activities API](https://docs.microsoft.com/en-us/defender-cloud-apps/api-activities-list)
* Content Source: [CloudAppSecurityDocs/api-activities-list.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-activities-list.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
This page documents the permissions necessary:

https://docs.microsoft.com/en-us/defender-cloud-apps/manage-admins

Does that answer your question?

**Comment by dcurwin** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
