### ISSUE TITLE
Possible typo/discrepancy in Chart

### ISSUE THREAD

**Issue by aaronsgutierrez** [MicrosoftDocs/CloudAppSecurityDocs#576]
[Enter feedback here]
Possible discrepancy between documentation and chart? 
Could you please review under: Feature Support "*Note: Microsoft Defender for Cloud Apps in GCC High / DoD is paired with Microsoft Sentinel and Microsoft Defender for Cloud in the Azure Government cloud."

However, the chart only lists "Roadmap" under Microsoft Sentinel GCC High/ DoD.

Thank you for your consideration.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ac1d0d-1f97-1bbf-732b-c65bb89170b1
* Version Independent ID: a28b78cc-7b30-b5f2-29a5-dd35111e05a0
* Content: [Microsoft Defender for Cloud Apps for US Government offerings](https://docs.microsoft.com/en-us/defender-cloud-apps/editions-cloud-app-security-gcc)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-gcc.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/editions-cloud-app-security-gcc.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for your comment. There are changes coming regarding Defender for Cloud Apps government offerings. The documentation will be updated in the days to come to reflect those changes, and the discrepancy you found will be addressed as well.
