### ISSUE TITLE
Advanced Hunting query seems to have the wrong operator

### ISSUE THREAD

**Issue by waydaws** [MicrosoftDocs/CloudAppSecurityDocs#577]
The section that says...
Use the following steps to gain more granular visibility on app-related network events in Defender for Endpoint:
  In Defender for Cloud Apps, under Discovery select Discovered apps.
  Select the app you want to investigate to open its drawer.
   Select the app's Domain list and then copy the list of domains.
  In Microsoft 365 Defender, under Devices, select Advanced hunting.

Paste the following query and replace <DOMAIN_LIST> with the list of domains you copied earlier.

DeviceNetworkEvents
| where RemoteUrl in ("<DOMAIN_LIST>")
| order by Timestamp desc

...
If I have a list of domains that I've exported, e.g. ("domain1", "domain2", "domain3") the in operator probably isn't  going to work, since these are domains and not full specific urls.  I'd replace it with has_any operator.   

Also, instead of <"DOMAIN_LIST">, I'd list them in a series like I did, and say, "where domain 1 - domain 3 were exported from the Export Tab in MDCA. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1cc6749-39e9-8a7e-298d-a75acb63c72e
* Version Independent ID: b0388842-cc04-f09e-3ed3-f05d5d1c9164
* Content: [Investigate apps discovered by Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/defender-cloud-apps/mde-investigation)
* Content Source: [CloudAppSecurityDocs/mde-investigation.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/mde-investigation.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for your feedback. We will consider adding the requested functionality in a future product release.
