### ISSUE TITLE
My thoughts on Microsoft Defender for Cloud Apps docs

### ISSUE THREAD

**Issue by sishima2** [MicrosoftDocs/CloudAppSecurityDocs#580]
Regarding "Use policies to assess risk(※)", it is difficult to understand which type of policy is described.
※.https://docs.microsoft.com/en-US/defender-cloud-apps/control#use-policies-to-assess-risk

It is easier to understand if you write a specific example (for example, file policy or malware detection policy) instead of saying "a specific policy".
Also, if the purpose is to understand incidents that match the policy but do not generate an alert, it should be clearly described.
I should add that it took me and a Microsoft Japan support engineer a few weeks to interpret this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456afa4-d70a-c601-343a-8554a9348065
* Version Independent ID: 298ecced-a426-93af-336e-4c280a910206
* Content: [How to use governance actions in Defender for Cloud Apps](https://docs.microsoft.com/en-US/defender-cloud-apps/control#use-policies-to-assess-risk)
* Content Source: [CloudAppSecurityDocs/control.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/control.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your comment. We are planning a review and overhaul of this page, and will include your suggestions in our plans.

**Comment by sishima2** [comment]
Thank you for responding to my comment. I look forward to your work.
