### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by 486DX50** [MicrosoftDocs/CloudAppSecurityDocs#581]
40.83,.194.193 -> 40.83.194.193

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96223442-ff3d-c101-214f-2240ac42d53b
* Version Independent ID: 56fead2d-d0ba-ce69-e931-5b91ed43c736
* Content: [Network requirements](https://docs.microsoft.com/en-us/defender-cloud-apps/network-requirements)
* Content Source: [CloudAppSecurityDocs/network-requirements.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/network-requirements.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@486DX50  - Thanks for your comment. The page has been updated.
