### ISSUE TITLE
Wrong tenantname reference?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/CloudAppSecurityDocs#583]
In the note under Portal Access it says
```
Instead of a wildcard (*) you can open only your specific tenant URL, for example, based on the screenshot above you can open: mod244533.us.portal.cloudappsecurity.com
``` 

But `mod244533` does not appear in any screenshot (only `tenant2.us`)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96223442-ff3d-c101-214f-2240ac42d53b
* Version Independent ID: 56fead2d-d0ba-ce69-e931-5b91ed43c736
* Content: [Network requirements](https://docs.microsoft.com/en-us/defender-cloud-apps/network-requirements)
* Content Source: [CloudAppSecurityDocs/network-requirements.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/network-requirements.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
This is a duplicate of https://github.com/MicrosoftDocs/CloudAppSecurityDocs/issues/582 so I am closing this one.
