### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/CloudAppSecurityDocs#584]
The note says 
`Instead of a wildcard (*) you can open only your specific tenant URL, for example, based on the screenshot above you can open: mod244533.us.portal.cloudappsecurity.com`. Does that also hold for the other wildcards, or only for those for the portal access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96223442-ff3d-c101-214f-2240ac42d53b
* Version Independent ID: 56fead2d-d0ba-ce69-e931-5b91ed43c736
* Content: [Network requirements](https://docs.microsoft.com/en-us/defender-cloud-apps/network-requirements)
* Content Source: [CloudAppSecurityDocs/network-requirements.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/network-requirements.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for your question. It only applies to portal access, and we updated the note to reflect that.
