### ISSUE TITLE
Wrong title in navigation

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/CloudAppSecurityDocs#586]
This page is called "Monitor Apps" in the contents on the left hand side but is actually about monitoring alerts, which matches the page title and URL
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/29751878/187949375-8f1b614c-03e9-4b4c-8b06-2c935af79076.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b04921b-1cc9-3e42-5535-e9274ab43707
* Version Independent ID: b90a8d00-6a35-df29-b156-428214ec79a8
* Content: [Monitor alerts raised in Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/monitor-alerts)
* Content Source: [CloudAppSecurityDocs/monitor-alerts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/monitor-alerts.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for bringing this to our attention. We've updated the page.
