### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/CloudAppSecurityDocs#587]
In section [Review the Cloud Discovery Dashboard](https://docs.microsoft.com/en-us/defender-cloud-apps/discovered-apps#review-the-cloud-discovery-dashboard) in Step 2  it says "Sanction" instead of "Sanctioned"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fbda4c0-2222-b67a-615e-261fea7f3f05
* Version Independent ID: 13241ed3-46e9-5821-4760-4bdb9564c69e
* Content: [Working with discovered apps in Defender for Cloud Apps](https://docs.microsoft.com/en-us/defender-cloud-apps/discovered-apps)
* Content Source: [CloudAppSecurityDocs/discovered-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/discovered-apps.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks, corrected.
