### ISSUE TITLE
Provide more detail on end user experience

### ISSUE THREAD

**Issue by peppermint-choir** [MicrosoftDocs/CloudAppSecurityDocs#589]
After enabling integration with Defender for Endpoint, I was only able to receive the warning for apps that are monitored in Edge and requested access. Firefox and Chrome did not give me access, I only received the errors below:

Firefox: SSL_ERROR_NO_CYPHER_OVERLAP
Chrome: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Additionally, some Microsoft apps appear to be tagged as monitored by default, causing them to be inaccessible from 3rd party browsers after enabling this. For me, the apps were: Bing, Microsoft Online Services, Teams, Microsoft Graph, Azure CDN Edge Nodes. Plus Amazon Cloud Front.

The governing discovered apps section does not mention the monitored tag: https://docs.microsoft.com/en-us/defender-cloud-apps/governance-discovery#BKMK_SanctionApp

It would be useful to reference this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9385053-041b-10db-888d-432c27c68ffb
* Version Independent ID: 2287bacf-3c7f-6271-aa50-77cc015adb96
* Content: [Govern discovered apps using Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/defender-cloud-apps/mde-govern)
* Content Source: [CloudAppSecurityDocs/mde-govern.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/mde-govern.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by peppermint-choir** [comment]
Please disregard the comment on apps monitored by default. This was happening via a popular app policy.

Additional information on the experience in 3rd party browsers (not being able to request access to monitored apps) would still be very useful.

**Comment by dcurwin** [comment]
@peppermint-choir  - Thank you for your patience. After investigating this issue, we've determined that this issue is being investigated by the MDE team and they will update their documentation. For more information, you can follow up with the MDE team via their documentation pages.

@tdoucett-ms  FYI
