### ISSUE TITLE
App Governance not available in Defender for Cloud Apps

### ISSUE THREAD

**Issue by LucioBenzor** [MicrosoftDocs/CloudAppSecurityDocs#591]
Trying to follow the documentation and checked that I have at least one OATH app registered with Azure AD and I'm not able to see app governance in Defender for Cloud Apps, but DO see the ability to start a trial in Security.Microsoft.com under App Governance - Is there something in my tenant that doesn't meet the criteria or is this an expected change from MCAS -> M365 Defender?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1fa045c-9edd-2d50-8c55-25b5be8ec9c8
* Version Independent ID: d1fa045c-9edd-2d50-8c55-25b5be8ec9c8
* Content: [Get Started with app governance](https://docs.microsoft.com/en-us/defender-cloud-apps/app-governance-get-started)
* Content Source: [CloudAppSecurityDocs/app-governance-get-started.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/app-governance-get-started.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.
