### ISSUE TITLE
Clear Differentiation between Defender for Cloud Apps and Azure AD Premium Cloud App Security

### ISSUE THREAD

**Issue by uc-cjdavis** [MicrosoftDocs/CloudAppSecurityDocs#598]
As Microsoft is splitting/consolidating features in Defender for Cloud Apps, there should be a clear distinction between...and documentation for...both cloud app products:  Defender for Cloud Apps and Azure AD Premium Cloud App Security.

Right now, all links on this page for AAD Premium Cloud App Security point to documentation that is applicable for both products, but primarily for Defender for Cloud Apps (Example:  The highlighted 'we've renamed Microsoft Cloud App Security' note at the top of every page).  This creates confusion and frustration when setup/configuration instructions fail because they cannot be implemented in AAD Premium Cloud App Security.

Separate documentation, and links to same, should be created for AAD Premium Cloud App Security.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 401b0903-938e-9739-49eb-4c28ef10bcfc
* Version Independent ID: 89fc55de-a5eb-c398-4a53-5786f49349f2
* Content: [Discovery capability differences for Defender for Cloud Apps and Azure AD](https://learn.microsoft.com/en-us/defender-cloud-apps/editions-cloud-app-security-aad)
* Content Source: [CloudAppSecurityDocs/editions-cloud-app-security-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/editions-cloud-app-security-aad.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks for the feedback. We're going to leave the documentation as it is for now, The product group has responded:

"It is not a separate product. It is a separate license that contains subset of the features of MDA. The table in the page ([Discovery capability differences for Defender for Cloud Apps and Azure AD | Microsoft Learn](https://learn.microsoft.com/en-us/defender-cloud-apps/editions-cloud-app-security-aad#feature-comparison)) describes in a clear way exactly what one gets in this license."

We are planning a revision to our documentation as part of the convergence with Microsoft 365 Defender, and the page will likely be updated as part of that process.

Thanks again!

**Comment by uc-cjdavis** [comment]
> Thanks for the feedback. We're going to leave the documentation as it is for now, The product group has responded:
> 
> "It is not a separate product. It is a separate license that contains subset of the features of MDA. The table in the page ([Discovery capability differences for Defender for Cloud Apps and Azure AD | Microsoft Learn](https://learn.microsoft.com/en-us/defender-cloud-apps/editions-cloud-app-security-aad#feature-comparison)) describes in a clear way exactly what one gets in this license."
> 

The point was made about the documentation _following_ the chart; while the page with the chart is clear,  all of referenced instructions and step-by-step procedures reference Defender for Cloud Apps and do **not** include analogous instructions for the lesser licensed product.

**Comment by dcurwin** [comment]
Thanks again for your feedback. As noted above, "We are planning a revision to our documentation as part of the convergence with Microsoft 365 Defender, and the page will likely be updated as part of that process."
