### ISSUE TITLE
Connect Salesforce to Microsoft Defender for Cloud Apps - API limit

### ISSUE THREAD

**Issue by LucioBenzor** [MicrosoftDocs/CloudAppSecurityDocs#599]
looking at the documentation, am I to understand that DFCA leaves 90% of the available API calls granted by the Salesforce license in a Single 24 hour period?

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@LucioBenzor  - Thanks for your question.

Here's the response from the product group:

This is already clarified in the doc. We leave 10 % of the value and at max consume 90 % of available threshold. 
![image](https://user-images.githubusercontent.com/45630879/197955020-3bcfa9cf-3e0d-4120-9765-d38405f7bbbf.png)
