### ISSUE TITLE
No mention of admin-mcas-gov.ms

### ISSUE THREAD

**Issue by redsolo** [MicrosoftDocs/CloudAppSecurityDocs#600]
Are the page containing all domains? The page is NOT listing `admin-mcas-gov.ms`, but it is listing `*.admin-mcas-gov.us`?

We have seen in the field `ihs.com.admin-mcas-gov.ms` and the apex domain is not listed (except for the `.us`).

Is it a spelling error?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e092a97-a2c2-849c-6bd0-6e73a90ffc57
* Version Independent ID: 2eeaa902-7a79-5a32-0031-2290302a378f
* Content: [Troubleshooting - What is cas.ms, mcas.ms, or mcas-gov.us?](https://learn.microsoft.com/en-us/defender-cloud-apps/troubleshooting-proxy-url#feedback)
* Content Source: [CloudAppSecurityDocs/troubleshooting-proxy-url.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/troubleshooting-proxy-url.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@redsolo  - Thank you again for your comment. The page has been updated (the changes should go live soon.)
