### ISSUE TITLE
DIscovery also works when Defender is in passive/EDR Block mode

### ISSUE THREAD

**Issue by rfellmann** [MicrosoftDocs/CloudAppSecurityDocs#602]
The 'Prerequisites' section suggests that Defender AV must run in Active Mode in order for the integration to work. We must distinguish between Discovery data being sent from MDE to MDA and MDE enforcing the unsanctioning/Monitoring of apps. 

Discovery works even when Defender AV runs in passive or EDR block mode. We don't need Real-time protection enabled, Cloud-delivered protection enabled or Network protection enabled and configured to block mode for this to work. This is only required to enforce the unsanctioning/monitoring of the apps. There might be customers who are running Defender AV in passive/EDR block mode and want to make use of the discovery feature only.

Please update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca5e3ab-ef88-9069-6063-1d4bcd100b3c
* Version Independent ID: 2ca5e3ab-ef88-9069-6063-1d4bcd100b3c
* Content: [Integrate Microsoft Defender for Endpoint with Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/mde-integration)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/mde-integration.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@rfellmann  - Sorry for not writing earlier. The documentation was updated a few weeks ago.
