### ISSUE TITLE
Insufficient role based permissions

### ISSUE THREAD

**Issue by aspnet4you** [MicrosoftDocs/CloudAppSecurityDocs#605]
I am trying to get files using cloudappsecurity API but I am getting "Insufficient role based permissions" error.  I am using Azure AD application and provided all the permissions under Microsoft Cloud App Security. 

![image](https://user-images.githubusercontent.com/33773493/199318906-a95ccb9d-96c5-4090-bb5e-06ccff09e582.png)

I am calling https://aspnet4you2.us3.portal.cloudappsecurity.com/api/v1/files/ and it is giving me Insufficient role based permissions error. 
![image](https://user-images.githubusercontent.com/33773493/199321797-452bfbe7-85fe-4353-8442-a6995b6c4d95.png)

Tried to use https://portal.cloudappsecurity.com/cas/api/v1/files/ and I get same error.
![image](https://user-images.githubusercontent.com/33773493/199322229-17fed0ba-ea66-43e9-bd34-e4ef703a8fb3.png)

Any idea why I am getting permission error when Azure service principal has all the permissions granted with admin consent?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c54c807c-d5d4-27ec-1c46-80af85dd9d45
* Version Independent ID: 4bba6fa0-ca82-d4d9-7022-c69a733c6331
* Content: [List - Files API](https://learn.microsoft.com/en-us/defender-cloud-apps/api-files-list)
* Content Source: [CloudAppSecurityDocs/api-files-list.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-files-list.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.

**Comment by aspnet4you** [comment]
@dcurwin - I understand it may not be the gap in documentation but I am following the documentation- the prerequisites to get token and required permissions. However, I am getting error. I will start a case with Microsoft support team as you have suggested but I wanted to see if other people are having similar issue accessing Microsoft Cloud App Security via API.
