### ISSUE TITLE
The link to log collector reloads the same page.

### ISSUE THREAD

**Issue by theboymango** [MicrosoftDocs/CloudAppSecurityDocs#61]
The link that says "Log collector:" simply reloads the same page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2005aabb-11c8-3ab9-6e87-94b0ef5164be
* Version Independent ID: 0878ecbe-fcd1-eb38-8ddb-4b4ea685d3c0
* Content: [Deploy Cloud Discovery with Microsoft Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/set-up-cloud-discovery)
* Content Source: [CloudAppSecurityDocs/set-up-cloud-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/set-up-cloud-discovery.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi, thanks so much @theboymango ,

I've just fixed it - you should see the change go live in the next couple of days.

Rachel
