### ISSUE TITLE
unclear description of capability. 

### ISSUE THREAD

**Issue by maharumman** [MicrosoftDocs/CloudAppSecurityDocs#611]
in this paragraph, it is unclear if the full scan is only for up to 7 days prior, or if its a full scan of all connected box repositories

_After connecting Box, you'll receive events for 7 days prior to connection.

After connecting Box, Defender for Cloud Apps performs a full scan. Depending on how many files and users you have, completing the full scan can take awhile. To enable near real-time scanning, files on which activities are detected are moved to the beginning of the scan queue. For example, a file that is edited, updated, or shared is scanned right away rather than waiting for the regular scan process. Near real-time scanning doesn't apply to files that aren't inherently modified. For example, files that are viewed, previewed, printed, or exported are scanned as part of the regularly scheduled scan._

thanks , 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82896c8a-1071-33cc-9821-48c3c6a3d7bf
* Version Independent ID: a18117ae-a865-79e8-db21-924894bfe6c0
* Content: [Connect Box to Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/connect-box)
* Content Source: [CloudAppSecurityDocs/connect-box.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/connect-box.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@maharumman  - Thanks for your question. The full scan includes all files. We've updated the documentation to make this more clear.
