### ISSUE TITLE
confusing description of Alert _id field

### ISSUE THREAD

**Issue by snowch** [MicrosoftDocs/CloudAppSecurityDocs#614]
In [properties](https://learn.microsoft.com/en-us/defender-cloud-apps/api-alerts#properties) the following description is provided:

```
_id | int | Alert type identifier
```

This doesn't make sense.  Should this really be called `Alert identifier`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6285dae7-ab18-3b19-9cb2-b6c6eed229f6
* Version Independent ID: b430c7ef-1918-f6c8-7115-a5d76d3e4a58
* Content: [Defender for Cloud Apps Alerts API - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/api-alerts#properties)
* Content Source: [CloudAppSecurityDocs/api-alerts.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-alerts.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thank you for your comment. We are in the process of revising the API documentation and this suggestion will be included.
