### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/CloudAppSecurityDocs#615]
Regarding 

>We've renamed Microsoft Cloud App Security. It's now called [Microsoft Defender for Cloud Apps](https://aka.ms/defender-for-cloud-apps). **In the coming weeks, we'll update the screenshots and instructions here and in related pages**.

It's been over 1 year since Ignite 2021. Can you please advise whether the updates have been made?

I am trying to figure out if this documentation page can be relied upon or if it's out of date. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92f1881c-1d0b-7a96-f8c1-3989b3b5e0cd
* Version Independent ID: b50ed5b9-18ab-abde-406e-b3fd1ff61fa2
* Content: [What is Defender for Cloud Apps? - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/what-is-defender-for-cloud-apps)
* Content Source: [CloudAppSecurityDocs/what-is-defender-for-cloud-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/what-is-defender-for-cloud-apps.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
@VitalyMCT  - Thanks for the comment. The updates have been made, and we've updated the banner as well.
