### ISSUE TITLE
Analysis time interval

### ISSUE THREAD

**Issue by chjone** [MicrosoftDocs/CloudAppSecurityDocs#62]
Regarding the note, 'Continuous report data is analyzed twice a day.'

Is this configurable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2005aabb-11c8-3ab9-6e87-94b0ef5164be
* Version Independent ID: 0878ecbe-fcd1-eb38-8ddb-4b4ea685d3c0
* Content: [Deploy Cloud Discovery with Microsoft Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/set-up-cloud-discovery)
* Content Source: [CloudAppSecurityDocs/set-up-cloud-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/set-up-cloud-discovery.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi! Thanks for reaching out with your question. No, sorry, that's not a configurable setting.
