### ISSUE TITLE
Can the subject in email alerts be more descriptive?

### ISSUE THREAD

**Issue by kbj5** [MicrosoftDocs/CloudAppSecurityDocs#622]
Would like a feature to customise the subject line like put in a prefix so we know the CAS tenancy that sent the alert as well as put in the description the type of alert like Mass download alert or Impossible travel etc.

For example the subject line:  ABC - Mass download alert for single user

Having "Defender for Clous Apps: New policy match detected" takes additional time to manage which adds up when you receive hundreds per week.

Would also like the options without the use of 3rd party for privacy reasons.

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.
