### ISSUE TITLE
Update IP Address ranges to be numerical

### ISSUE THREAD

**Issue by gesmith-Ms** [MicrosoftDocs/CloudAppSecurityDocs#623]
Update IP Address ranges to be numerical - This will help customers determine what IP addresses do and dont change. The "App Connectors" part of the product continues to show multiple IP addresses, all of them scattered. Making these in order will help with changes respectfully. Doing this for all the documentation will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96223442-ff3d-c101-214f-2240ac42d53b
* Version Independent ID: 56fead2d-d0ba-ce69-e931-5b91ed43c736
* Content: [Network requirements - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/network-requirements)
* Content Source: [CloudAppSecurityDocs/network-requirements.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/network-requirements.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for the suggestion. We're working on ways to make the ranges more accessible.
