### ISSUE TITLE
Curl Command incorrect

### ISSUE THREAD

**Issue by Spen789** [MicrosoftDocs/CloudAppSecurityDocs#626]
Curl command incorrect 
curl -XGET -H "Authorization:Token <your_token_key>" "https://<tenant_id>.<tenant_region>.contoso.com/api/discovery_block_scripts/?format=102&type=banned"
should be 

curl -XGET -H "Authorization:Bearer <your_token_key>" "https://<tenant_id>.<tenant_region>.contoso.com/api/discovery_block_scripts/?format=102&type=banned"

also if running command from PowerShell use curl.exe not just curl
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94fd7bc0-d7ff-d8ee-dca7-08ccc4da8688
* Version Independent ID: 98a94d4c-2ca0-0f10-b199-5a4de9f07351
* Content: [Generate block script - Cloud Discovery API - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/api-discovery-script)
* Content Source: [CloudAppSecurityDocs/api-discovery-script.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-discovery-script.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @Spen789,
Our team has confirmed that we support both token and bearer options. 
When you use "Token", you'll need to provide the API token you produced in the portal, in the API Token tab.
When you use "Bearer" you need to provide the token you produced through AAD graph.

Please confirm whether this helps with your issue, and we can clarify this in an upcoming fix. 
Thanks for contributing to docs!
