### ISSUE TITLE
When using the policy filters, Contains searches only for full words - Not working with underscore

### ISSUE THREAD

**Issue by mcclane653** [MicrosoftDocs/CloudAppSecurityDocs#627]
I have done lots of testing this eve, according to the hint separated by commas, dots, spaces, or underscores. Should all work. but in my tenant it does not work with underscore. otherwise the hint is correct. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b0d4ad8-405a-a300-08e8-f0c02ab1feb4
* Version Independent ID: cfa88e4b-a518-9471-a21f-70048655dbb2
* Content: [File policies - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/data-protection-policies)
* Content Source: [CloudAppSecurityDocs/data-protection-policies.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/data-protection-policies.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.
