### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by taffj** [MicrosoftDocs/CloudAppSecurityDocs#632]
Is this even supported anymore? The screenshots don't reflect the current Google UI and the process as outlined simply does not work. I understand that Google delights in moving the goal posts, but given Microsoft's bloviating about Defender for Cloud Apps functioning as a full-featured CASB I don't think it's unrealistic to expect the instructions to be accurate even if the screenshots are a bit outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1f41e1e-2541-8773-efc2-eeb83a403a15
* Version Independent ID: 2f2d0316-9e75-44d6-0ab6-a56b1352a1e2
* Content: [Connect Google Workspace - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/connect-google-workspace)
* Content Source: [CloudAppSecurityDocs/connect-google-workspace.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/connect-google-workspace.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by taffj** [comment]
Appreciate the quick response. I continued to mess with it and change settings and it now works. Unfortunately my notes are pretty sparse so I'm unsure which modification I made (was using suggestions from sites I found on the web) led to the success--otherwise I'd let you know to assist with updating the page. Thanks again.
