### ISSUE TITLE
Export to CSV produces a badly formatted CSV file

### ISSUE THREAD

**Issue by brolifen** [MicrosoftDocs/CloudAppSecurityDocs#633]
When using the Export feature to export as CSV:

![image](https://user-images.githubusercontent.com/20615514/217760981-c97b7a14-90fd-4b90-a7bd-6b34c41937e4.png)

The output produces a CSV file that is badly formatted because some of the data also contains a comma. This is because the export is not using the best practise of quotation marks to preserve the data even if it contains a comma, for example:

"Column 1","Column 2","Column 3"
"Data 11","Data 12","Data 13"
"Data 21","Data 22, with comma","Data 23"

Fix: Add quotation marks around the data being exported for the CSV type.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f02dc24-a495-59e0-1f78-89b6a0b275e2
* Version Independent ID: 3089ccac-a074-7a99-7078-e28c9432050a
* Content: [Activities - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/activity-filters)
* Content Source: [CloudAppSecurityDocs/activity-filters.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/activity-filters.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.
