### ISSUE TITLE
Sentence doesn't make sense

### ISSUE THREAD

**Issue by markburland** [MicrosoftDocs/CloudAppSecurityDocs#635]
Please translate this sentence into English:

If you do not to create session policies to monitor high-risk sessions, you will lose the ability to block and protect downloads in the web client, as well as the ability to monitor low-trust session both in Microsoft and third-party apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4e4354-bfb5-1b0a-d6d6-734290a15963
* Version Independent ID: 62d41ec5-f48d-d7fb-406a-2810a4ff4fbc
* Content: [Best practices for protecting your organization - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/best-practices#block-and-protect-download-of-sensitive-data-to-unmanaged-or-risky-devices)
* Content Source: [CloudAppSecurityDocs/best-practices.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/best-practices.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Fixed.
