### ISSUE TITLE
More info needed on "Contains"

### ISSUE THREAD

**Issue by Torxsmind** [MicrosoftDocs/CloudAppSecurityDocs#636]
You documentation has the following statement "When using the file policy filters, Contains will search only for full words – separated by commas, dots, hyphens or spaces to search." but no examples are given.  "Full words" is not very clear and can be interpreted a few ways.

For example:
I have (3) files in onedrive:

1. Tacos.txt
2. SupremeTacos.txt
3. Tacos_recipe.txt 

 if the filter has CONTAINS = Tacos

What will match the "Full Word"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba61c236-e64a-2835-8fbd-4ff975e78d27
* Version Independent ID: d4394353-4330-05a2-c30b-b2b4bd7b7c2f
* Content: [File filters - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/file-filters)
* Content Source: [CloudAppSecurityDocs/file-filters.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/file-filters.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
The documentation appears to cover these scenarios. If you have further questions, please open a support case.

**Comment by Torxsmind** [comment]
I would disagree with your comments as there are still some room for interpertation.  The examples published are if you are searching for more than one word.  I am asking about a single word and how the filter will react with a concatenated file name.  In my example would SupremeTacos.txt be flagged if my Filter was just Tacos?  

I am not asking for support here, I am telling you that the documentation could be updated for more clarity.  Looking at some of the other closed issues other people are having concerns.
