### ISSUE TITLE
SampleRootCA

### ISSUE THREAD

**Issue by karthicktv** [MicrosoftDocs/CloudAppSecurityDocs#638]
Sample Root CA cert is not in the correct format

When I upload the Root CA cert, I get the following error:

Certificate format is not valid. Certificates use the PEM format 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect apps with Conditional Access App Control - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/proxy-intro-aad)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.
