### ISSUE TITLE
Outdated primary link to portal

### ISSUE THREAD

**Issue by rviersel** [MicrosoftDocs/CloudAppSecurityDocs#639]
Outdated primary link to portal:

https://learn.microsoft.com/en-us/defender-cloud-apps/get-started#to-access-the-portal

https://portal.cloudappsecurity.com =====> https://security.microsoft.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Get started - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/get-started)
* Content Source: [CloudAppSecurityDocs/get-started.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/get-started.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. This will be changed in an upcoming update to the documentation.
