### ISSUE TITLE
iboss missing from data attribute table

### ISSUE THREAD

**Issue by RyanMorash** [MicrosoftDocs/CloudAppSecurityDocs#64]
The iboss Secure Cloud Gateway is missing from the supported data attributes table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a419aaf2-b6b9-902a-e186-c5718b9ffd1f
* Version Independent ID: 2a9c599e-306e-490e-2e6d-7642fa71d63c
* Content: [Create snapshot reports of Cloud Discovery cloud app use](https://docs.microsoft.com/en-us/cloud-app-security/create-snapshot-cloud-discovery-reports)
* Content Source: [CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi Ryan,
thanks for your contribution. We're working on documentation supporting iBoss. We have some open questions with them that relate to certain support items. As soon as we have answers we'll update this page and add an integration guide to make it easier. Sorry for the inconvenience.
Rachel

**Comment by rkarlin** [comment]
@msmbaldwin #please-close
