### ISSUE TITLE
the instructions need to be updated

### ISSUE THREAD

**Issue by NickBazinga** [MicrosoftDocs/CloudAppSecurityDocs#640]
[Enter feedback here]
I believe this option is available now only in the defender portal 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b8ca2a3-a0e8-802a-e79f-737e8f1735ea
* Version Independent ID: a052f0f9-8ca5-3499-9c33-40dd4315ffe8
* Content: [Block download of sensitive information with Conditional Access App Control - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/use-case-proxy-block-session-aad)
* Content Source: [CloudAppSecurityDocs/use-case-proxy-block-session-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/use-case-proxy-block-session-aad.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thanks for your comment. The page is undergoing a revision and will be published in the next few weeks.
