### ISSUE TITLE
Supportability of Salesforce

### ISSUE THREAD

**Issue by rynator1** [MicrosoftDocs/CloudAppSecurityDocs#641]
Based on the "Users and activities" table on this page, it appears that Salesforce is generally supported, and Salesforce Shield is only required for user activity-related purposes. However, I've heard that in reality, subscribing to Salesforce Shield is a prerequisite for connecting Salesforce to MDA.
Indeed, the description on the following page also suggests that Salesforce Shield is required:
https://learn.microsoft.com/en-us/defender-cloud-apps/connect-salesforce#how-to-connect-salesforce-to-defender-for-cloud-apps

To avoid confusion, could you please revise the wording to make it clear and avoid any misunderstandings?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3cb69cd-d5d4-e058-e20f-d2697cfcd614
* Version Independent ID: bb8fbd63-532a-f8f9-6bc6-85eaf09ca171
* Content: [Connect apps to get visibility and control - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/enable-instant-visibility-protection-and-governance-actions-for-your-apps)
* Content Source: [CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by batamig** [comment]
I'm tagging an SME to advise. @NagarajVenkatesh, can you take a look?

**Comment by batamig** [comment]
Hi @rynator1, I'm updating this thread to let you know that we've updated [this page](https://learn.microsoft.com/defender-cloud-apps/connect-salesforce#how-to-connect-salesforce-to-defender-for-cloud-apps) to clarify the issue about Salesforce Shield. Can you take a look to confirm that this is clearer now?
Thanks again for your contribution!

**Comment by batamig** [comment]
Hi, we haven't heard from you and will now close this item. Please be in touch if you have any further comments. 
Thanks again!
#please-close
