### ISSUE TITLE
FTP upload doesn't work/no rights ; clarify Certificate files

### ISSUE THREAD

**Issue by timothyfrank** [MicrosoftDocs/CloudAppSecurityDocs#644]
In section "Customize certificate files" - the ftp account given to the collector does not have rights to upload files to the ssl_updates directory in the procedure.   We had to copy the files into the container from the host.  Tested with multiple containers.

In same section, it would be helpful to clarify the purpose of the CA.pem file:
ca.pem = CA For the Client Certificate
server-key.pem, and server-cert.pem= cert and key for the collector

It was not evident that CA.pem was for the client, and not this server.  We did troubleshooting for several hours over multiple days before figuring our issue was that we misunderstood what ca.pem file was for.

Thanks
Tim Frank

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff287a41-44c8-e587-842e-5a90e859d218
* Version Independent ID: 0ca69462-3626-fe6e-e59d-3d622caaae39
* Content: [Advanced log collector management - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/log-collector-advanced-management)
* Content Source: [CloudAppSecurityDocs/log-collector-advanced-management.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/log-collector-advanced-management.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @timothyfrank, thanks again for sending your feedback to docs.
Our investigation concluded that uploading files to the ssl_update directory using the FTP credentials is indeed supported. Therefore, if you're still having issues with this, please open a support case to understand what else might be blocking the process.

Re clarification about the certificate files, we're working on an update that clarifies the purpose of each file. Please check again tomorrow (June 20th) for the changes and let us know if the changes help.

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
#please-close
