### ISSUE TITLE
Clarify defender for Cloud Apps Discovery licensing for M365 Business Premium

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/CloudAppSecurityDocs#646]
M365 Business Premium includes Defender for Business. Is it possible to use auto discovery integration with Business Premium as valid? or is Defender for Business standalone required

It should be clarified in the docs. I've gotten contradixting answers regarding this from Microsoft Support

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca5e3ab-ef88-9069-6063-1d4bcd100b3c
* Version Independent ID: 2ca5e3ab-ef88-9069-6063-1d4bcd100b3c
* Content: [Integrate Microsoft Defender for Endpoint - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/mde-integration)
* Content Source: [CloudAppSecurityDocs/mde-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/mde-integration.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by JMCA2** [comment]
@batamig Any news regarding this? Is been several months already.
Thanks

**Comment by batamig** [comment]
Hi @JMCA2 - yes, and we just recently updated our docs with the following clarification:

Prerequisites include one of the following:

- Microsoft Defender for Endpoint with Plan 2
- Microsoft Defender for Business with a premium or standalone license

For more information, see [Compare Microsoft endpoint security plans](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2).

Please confirm whether this helps your issue and thanks for contributing to docs!

**Comment by JMCA2** [comment]
Hi @batamig, thanks
Seems clear on this docs page now regarding Defender for Endpoint and Defender for Cloud Apps integration being available for Business Premium.

However, there are other bigger issues with Defender for Cloud Apps exact licensing not being clear at all for Business Premium. I've opened new issue https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/835

**Comment by batamig** [comment]
Thanks @JMCA2! I'll let @pamelaar take the lead on that one as the content owner there, and we can be in touch internally as needed.
I'm going to close this issue for now but want to say thank you again for your feedback. We appreciate your perspective and comments!

#please-close
