### ISSUE TITLE
Cloud apps not listed in the app catalog

### ISSUE THREAD

**Issue by ShawnHag** [MicrosoftDocs/CloudAppSecurityDocs#648]
If a user is using a cloud app that is not registered in the app catalog, will defender for cloud apps be able to detect the app ?
Will Defender for cloud apps detect it and show it in the discovered app section without a risk score, or will it not even show up as a discovered app?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 385f2616-933d-a85d-448a-792f58fd1a09
* Version Independent ID: 12435b3b-f80a-4cba-2a7a-eb6726f11597
* Content: [Discover and manage Shadow IT - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/tutorial-shadow-it)
* Content Source: [CloudAppSecurityDocs/tutorial-shadow-it.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/tutorial-shadow-it.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

@NagarajVenkatesh - can you take a look at this?

**Comment by NagarajVenkatesh** [comment]
+ @Itaicitaic1 to look into this.

**Comment by batamig** [comment]
Hi @ShawnHag, getting back to you about this.
Defender for Cloud Apps doesn't discover apps that aren't in the catalog. You can either request to add an app to the catalog or create a custom app instead.

Does this answer your question?

**Comment by ShawnHag** [comment]
Sorry for my late response,, missed the notification
I see.. So I will only have partial transparancy in discovering what apps users are using since apps thats not listed in the catalog wont be discovered, whichi means that the usage of such apps will stay unknown to admins.

Is there any other solution that can discover all apps?

Requesting or creating a custom app doesnt really help because the point is to check if users are using apps that the security team isnt aware of..

**Comment by Itaicitaic1** [comment]
Hi Shawn,

Correct, the usage of apps which are not part of the catalog (or your custom apps) are not discovered.
Discover "unresolved URLS" is an existing backlog item with no ETA at the moment. Please share your customer details so we can add "evidence" to this feature request in order to potentially prioritize it.
If you prefer, you can also do this through a support ticket.


Best Regards,
Itai Cohen.

Discovery Product Manager.
Microsoft Defender for Cloud Apps.
Modern Protection & SOC.
[abc]

**Comment by batamig** [comment]
Thanks @Itaicitaic1!
@ShawnHag, to follow up, please continue the conversation by either opening a support ticket or providing product feedback via the [Microsoft 365 Defender Community](https://feedbackportal.microsoft.com/feedback/forum/d7dd1275-f65e-ed11-9562-000d3a4e3f39).

I'm going to close this issue for now, but feel free to add more comments if you have additional feedback for the docs.
We appreciate your contributions!
#please-close
