### ISSUE TITLE
There is a step in this documentation that needs a bit more clarity, as it is not "automatic". 

### ISSUE THREAD

**Issue by EllaBeans** [MicrosoftDocs/CloudAppSecurityDocs#650]
1. In the first bullets of the article, the second bullet: "Zscaler's block capabilities are automatically applied on apps you set as unsanctioned in Defender for Cloud Apps" should provide more clarity that there is some Zscaler configuration that needs to happen before the blocking/unsanction can occur with this integration. 

2. In Step 4 it reads: "Any app that you set as unsanctioned in Defender for Cloud Apps will be pinged by Zscaler every two hours, and then automatically blocked by Zscaler. For more information about unsanctioning apps, see [Sanctioning/unsanctioning an app](https://learn.microsoft.com/en-us/defender-cloud-apps/governance-discovery#sanctioningunsanctioning-an-app)." This should include some reference to the configuration needed in Zscaler to be more complete: 

"Any app that you set as unsanctioned in Defender for Cloud Apps will be pinged by Zscaler every two hours, and then automatically blocked by Zscaler **once configuration has been setup, see https://community.zscaler.com/t/guide-integrate-zscaler-with-microsoft-cloud-app-security-mcas/8572#optional-block-or-caution-access-to-unsanctioned-apps-12**. For more information about unsanctioning apps, see [Sanctioning/unsanctioning an app](https://learn.microsoft.com/en-us/defender-cloud-apps/governance-discovery#sanctioningunsanctioning-an-app)."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9efc6f96-264f-14ea-3a9a-da5f9d13c6a0
* Version Independent ID: 4c146408-6337-cddb-d79f-ae83e9d327a7
* Content: [Integrate with Zscaler - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/zscaler-integration)
* Content Source: [CloudAppSecurityDocs/zscaler-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/zscaler-integration.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.
#label:"backlog-item-created"

**Comment by batamig** [comment]
Hi @EllaBeans, we've updated this page to indicate more clearly that apps are blocked according to your Zscaler configuration. Please take a look and see if this helps your issue? Thanks for contributing to docs!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
#please-close
