### ISSUE TITLE
Configure IP address ranges

### ISSUE THREAD

**Issue by harald101010** [MicrosoftDocs/CloudAppSecurityDocs#661]
Hi,
at one of my client we identified some impossible travel etc. We analyzed the used RemoteIP of the user. The issue is: users are using the client user account, but not using a client-managed devices. These devices are managed by third-party, These third-party devices are using SDP (Software defined Parameter like ZScaler, AppGate, what ever). The result is that the user is switching its RemoteIP across country borders some time. In addition using Mobilephone is adding another source of IP addresses with other locations.
We can't get it sorted for the client.
If we use the following Advanced Hunting:
AlertEvidence
| where Title contains "Impossible travel"
| where isnotempty( RemoteIP)
| summarize RemoteIPcount = count() by  RemoteIP
we  get a list of more then 200 IP-addresses per week, which are count only once.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4e03e45-c169-67b4-b0f1-03597040bf0d
* Version Independent ID: 197ab35b-a26a-c186-8949-d1828303ca9f
* Content: [Detect suspicious user activity with UEBA - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/tutorial-suspicious-activity)
* Content Source: [CloudAppSecurityDocs/tutorial-suspicious-activity.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/tutorial-suspicious-activity.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @harald101010, thanks for writing into docs! I'm tagging an SME to help advise.
@assafyatziv, can you take a look?

**Comment by assafyatziv** [comment]
Hi @harald101010 
"Impossible travel activity" detection was switched to a new data type called "behavior", and was disabled by default on the 28th of May. One of the reasons is such cases, where although we do use suppressions such as prevent the alert trigger on common ISP, there are use cases where such alerts won't be suppressed for some reasons.
We recommend stop using this detection as alert, and if you say the outcome valuable, consider creating advanced hunting custom detection rules that trigger alerts only in certain use cases, such as ISP does not equal a closed list of ISPs.
More information about behaviors can be found in the documentation: https://learn.microsoft.com/en-us/defender-cloud-apps/behaviors or in this blog: https://aka.ms/mda/behaviors

**Comment by harald101010** [comment]
Thank you. this is exact the same, what we have planned to do our self at the customer: ignore the alerts but still use the information as additional input for further analyses. Indeed, i can think about use cases too, which requires not to have an impossible travel e.g. for high secure areas.

**Comment by batamig** [comment]
Hi @harald101010 - please let me know if this answers your question and we can close this issue?

**Comment by batamig** [comment]
Hi @harald101010,
I'm going to close this item now as it seems to have been resolved. If that's not the case, please feel free to re-open the issue and/or continue commenting. Thank you for contributing to docs!
#please-close
