### ISSUE TITLE
Issue accessing Defender for Endpoint discovered apps

### ISSUE THREAD

**Issue by icgaff** [MicrosoftDocs/CloudAppSecurityDocs#667]
[Enter feedback here]

The only option when clicking Cloud discovery is to create a report, and the Defender for Endpoint data source is not an option, just a bunch of firewalls mostly. Cannot access the screens shown as it is gate kept behind this forced create report screen. Cannot proceed to view any data we are receiving alerts about.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1cc6749-39e9-8a7e-298d-a75acb63c72e
* Version Independent ID: b0388842-cc04-f09e-3ed3-f05d5d1c9164
* Content: [Investigate apps discovered by Microsoft Defender for Endpoint - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/mde-investigation)
* Content Source: [CloudAppSecurityDocs/mde-investigation.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/mde-investigation.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @icgaff, thanks for writing into docs.
This isn't a documentation issue and requires further investigation. The best way to get help in this case is to open a support ticket. 
Clarifications might indeed be needed in the documentation, in which case support will open an internal request with the updated details. 
I'm going to close this issue for now and encourage you to open a support ticket. For more information, see [Support and troubleshooting information for Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/support-and-ts).

#please-close
