### ISSUE TITLE
Utah, Vancouver version of SN not supported to connect to MDCA?

### ISSUE THREAD

**Issue by ramonabadea** [MicrosoftDocs/CloudAppSecurityDocs#668]
Hi all,

Utah and future Vancouver version of SN not supported to connect to MDCA???
If yes, can someone upgrade the doc?

Thanks in advance for the feedback,
Ramona

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 148367a2-1d5d-a348-e34a-ee5c9e8157dd
* Version Independent ID: 3dee7652-6b47-4523-a530-9b69257950fc
* Content: [Connect ServiceNow - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/connect-servicenow)
* Content Source: [CloudAppSecurityDocs/connect-servicenow.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/connect-servicenow.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @ramonabadea, thanks for writing into docs. @Ronen-Refaeli, can you advise as to whether the doc is currently up to date?
#label:"tagged-sme"

**Comment by ramonabadea** [comment]
Hello,

Any updates? :)

**Comment by batamig** [comment]
Hi there, coming back to update you that we've added Utah to the list of supported versions, but cannot comment on future versions like Vancouver. Thank you for bringing this to our attention - we appreciate your contribution to docs!
I'm going to close this now but please feel free to add more comments if you have additional feedback.
#please-close

**Comment by ramonabadea** [comment]
Hi again,

Sorry to re-open this thread, but is Vancouver supported yet since Aug or not yet? :)

Thanks in advance,
Ramona
