### ISSUE TITLE
ServiceNow account roles

### ISSUE THREAD

**Issue by zaidongy** [MicrosoftDocs/CloudAppSecurityDocs#670]
The page says to use "Your UserID" as the user account in ServiceNow. At our organization this is not allowed, it needs to be a Service Account. Can you please add some details on which tables the scanning tool needs to access so we can provide the service account the proper roles and permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 148367a2-1d5d-a348-e34a-ee5c9e8157dd
* Version Independent ID: 3dee7652-6b47-4523-a530-9b69257950fc
* Content: [Connect ServiceNow - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/connect-servicenow)
* Content Source: [CloudAppSecurityDocs/connect-servicenow.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/connect-servicenow.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @zaidongy, thanks for writing into docs! I'm tagging subject matter experts to advise, but you might also want to open a support ticket for this question.
@NagarajVenkatesh or @Ronen-Refaeli, is there anything we can add to the public docs for this?

**Comment by batamig** [comment]
Hi - closing an old issue. @zaidongy, this question is outside of the scope for doc feedback. If you haven't already, please open a support ticket and they will get back to us about any doc changes needed. 
Thank you for your contributions!
#please-close
