### ISSUE TITLE
NetDocuments missing the Canadian repo URL

### ISSUE THREAD

**Issue by neo2k1ca** [MicrosoftDocs/CloudAppSecurityDocs#672]
NetDocuments has a Canadian repo at https://can.netdocuments.com/ however that isn't working when trying to complete the cloud app connection. Can this please be added? Thanks

**Comment by neo2k1ca** [comment]
CloudAppSecurityDocs/connect-netdocuments-to-microsoft-defender-for-cloud-apps.md

**Comment by batamig** [comment]
Hi @neo2k1ca, if you're having issues completing the connection, you might need a support ticket to understand your specific use case. They can also help you open a new feature request if your use case isn't supported. 

I'm going to close this issue for now, but feel free to continue commenting if you have a question about our docs. 
Thanks!
#please-close
