### ISSUE TITLE
microsoft defender for cloud apps demo environment for trainers

### ISSUE THREAD

**Issue by zaalion** [MicrosoftDocs/CloudAppSecurityDocs#673]
[Enter feedback here]

Hello,

I am a Microsoft Certified Trainer (MCT) and need to create training content for Microsoft Defender for cloud Apps. How can I obtain a trial/free or basic license so that I can access the Cloud Apps dashboard and create my training content? 

Thanks a lot!
Rez

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Get started - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/get-started)
* Content Source: [CloudAppSecurityDocs/get-started.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/get-started.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @zaalion, thanks for writing into docs! 
While Defender for Cloud Apps doesn't have it's own trial, you can use it as part of an E5 trial. 
To contact sales, see [Microsoft Security Get Started | Microsoft Security](https://www.microsoft.com/en-us/security/business/get-started/start-free-trial)

I've opened a backlog item to clarify this in our docs. Feel free to comment here if you have any additional feedback. We appreciate your contribution to docs!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. Thanks for your contribution to docs!
#please-close
