### ISSUE TITLE
List entities and discovered apps don't support request body parameters

### ISSUE THREAD

**Issue by justynalapinska** [MicrosoftDocs/CloudAppSecurityDocs#674]
Request body parameters (filters, limit, skip, etc. - https://learn.microsoft.com/en-gb/defender-cloud-apps/api-entities-list#request-body-parameters) seem not to work for `/entities` and `/discovery/discovered_apps` endpoints, I can only get first page with 100 records. The `/activities` endpoint works fine with request parameters. 
Also, /discovery/discovered_apps endpoint is not documented at all, there are only `/streams` https://learn.microsoft.com/en-gb/defender-cloud-apps/api-discovery-list-streams and `/discovery/discovered_apps/categories` https://learn.microsoft.com/en-gb/defender-cloud-apps/api-discovery-list-categories endpoints documented.

**Comment by batamig** [comment]
Hi @justynalapinska, thanks for writing into docs! 
For the request body parameters that aren't working for you, please open a support ticket to understand your specific use case. 
For the undocumented endpoints, we'll investigate and get back to you.

**Comment by McfakeWP** [comment]
Hey im also keen on learning more about this i see other documented posts about the 100 limit issue but a lack of findings.

**Comment by batamig** [comment]
Hi @McfakeWP, thanks! Please open a support case to understand your specific use case, and support will open a doc request to clarify as needed.

**Comment by batamig** [comment]
Hi, we're closing out this older issue. Thanks for your comments!
#please-close
