### ISSUE TITLE
Send items actvity is not well described

### ISSUE THREAD

**Issue by mtzwn** [MicrosoftDocs/CloudAppSecurityDocs#675]
Send items activity is not well described on documentation, what would be in scope when this activity is in scope for session policy and what behaviour would it touch

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 019ab0de-8c3b-7eba-3506-cc2ab655b4ed
* Version Independent ID: 8f37cbfb-edce-a737-5bc8-17f2ed3d5958
* Content: [Session policies - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/session-policy-aad)
* Content Source: [CloudAppSecurityDocs/session-policy-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/session-policy-aad.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion. Thanks for your contribution to docs!
#please-close

**Comment by mtzwn** [comment]
Thanks for an update, where can I find full list of actions covered by this? An example is just one of these as far as i understand, does sending files also is part of send item?
