### ISSUE TITLE
The actions menu is empty and the tags section does not show

### ISSUE THREAD

**Issue by zaalion** [MicrosoftDocs/CloudAppSecurityDocs#676]
[Enter feedback here]

Hello,

I am trying Defender for Cloud Apps with a 365 E5 trial. The issue is after selecting an app, no tags section shows up, so I can not sanction the selected app. The Actions menu is also empty and the "app connectors" section is also missing. I am a Global Administrator so I am not sure what is going on! ANy help is appreciated.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b77ab1f7-e882-65ed-8763-2ca0e7f2d3a6
* Version Independent ID: decde69d-a97a-6eb5-c98a-a7f93fe80793
* Content: [Govern discovered apps - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/governance-discovery)
* Content Source: [CloudAppSecurityDocs/governance-discovery.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/governance-discovery.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @zaalion, thanks for writing into docs! This question requires a support ticket to understand your exact scenario. Please open a support ticket to solve your issue - the support team will open a doc update request as needed to clarify any missing information.
I'm going to close this issue for now, but feel free to add more comments if you have specific doc feedback. We appreciate your contribution to Microsoft docs.
#please-close
