### ISSUE TITLE
limit raise not available anymore

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/CloudAppSecurityDocs#677]
HI all, regarding the note in https://learn.microsoft.com/en-us/defender-cloud-apps/azip-integration#automatically-label-files we received the feedback from support that the limit increase isnt available anymore:

![image](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/assets/39616319/a4dca840-c301-4ce4-ba5e-929b400cae77)

can you please investigate and update the article?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d87a9a6d-db50-50ca-755b-ce28631c30ac
* Version Independent ID: 8656b0a3-ab7e-76ec-2d89-8c1aa643c9fa
* Content: [Integrate Microsoft Purview Information Protection - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/azip-integration#automatically-label-files)
* Content Source: [CloudAppSecurityDocs/azip-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/azip-integration.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by SRE93** [comment]
support case id 2307241420000540

**Comment by SRE93** [comment]
any update on this? @v-ccolin @shsagir

**Comment by batamig** [comment]
Hi, 
This page is now fixed, and the line about opening support cases is removed. 
I'm closing this issue for now, but feel free to add more comments if you have additional feedback.
Thanks for your contributions!
#please-close
