### ISSUE TITLE
Obsolete menu option

### ISSUE THREAD

**Issue by ianwilliams1** [MicrosoftDocs/CloudAppSecurityDocs#680]
Where the page shows:
**Organization Settings -> Integrations -> Third-party access** 
There is no such option.

The current GitHub menu is:
Settings -> Third-party Access ->OAuth application access policy
![image](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/assets/45702008/2ed9a3cd-8767-4a62-ab34-9a621974ad37)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1609d04d-4fb4-127f-10dd-5f42c9beb7b2
* Version Independent ID: 9646bb6f-054b-dbdc-55ac-6e33ab8ae48e
* Content: [Connect GitHub Enterprise Cloud - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/connect-github-ec)
* Content Source: [CloudAppSecurityDocs/connect-github-ec.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/connect-github-ec.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
I'm tagging @LeorHurwitz on this issue for tracking. Thanks!

**Comment by batamig** [comment]
Hi @ianwilliams1, thanks again for your feedback. After checking this, we decided to simply refer to the GitHub documentation for the most up to date information for where to find this option. 
Please take a look at the updated page and let us know if you have any additional questions. 
We appreciate your contribution to docs!

**Comment by batamig** [comment]
We haven't heard back from you, so we will now close this issue. If this remains an issue, please reply and we will gladly continue the discussion.
