### ISSUE TITLE
clearly state you can only search a 1 week period at a time

### ISSUE THREAD

**Issue by MikeBakerSAV** [MicrosoftDocs/CloudAppSecurityDocs#681]
[Enter feedback here]
clearly state you can only search a 1 week period at a time when searching 6 months back

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9450b1a9-f22b-c5d7-6789-676c9f4afc1f
* Version Independent ID: 8ada75ef-7a51-07dc-f69d-a71451b69cf1
* Content: [Activity filters and queries - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/activity-filters-queries#query-activities-six-months-back)
* Content Source: [CloudAppSecurityDocs/activity-filters-queries.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/activity-filters-queries.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @MikeBakerSAV, thanks again for your feedback. The page has been updated at https://learn.microsoft.com/defender-cloud-apps/activity-filters-queries#query-activities-six-months-back. 

Can you please look to see if you have any additional feedback, or if we can close this issue? We appreciate your contribution!

**Comment by batamig** [comment]
Hi @MikeBakerSAV, it's been a few weeks since we fixed this page and we haven't heard from you. 
I'm going to close this page for now but feel free to tag me again in any further feedback you might have.
Thanks again for writing into docs!

#please-close
