### ISSUE TITLE
Windows 11 support

### ISSUE THREAD

**Issue by ChrisM65** [MicrosoftDocs/CloudAppSecurityDocs#685]
Will this ever support Windows 11?

**Comment by batamig** [comment]
Hi @ChrisM65, thanks for writing into docs! This is a great question for our tech community or support, and unfortunately, we can't answer it in the content team. 
Please see https://techcommunity.microsoft.com/t5/microsoft-365/bd-p/microsoft-365 or open a support ticket. 
I'm closing this issue for now, but feel free to continue commenting if you have feedback on our docs.
#please-close
