### ISSUE TITLE
Prerequisite section is incomplete/inaccurate

### ISSUE THREAD

**Issue by FasttrackOz** [MicrosoftDocs/CloudAppSecurityDocs#689]
The prerequsisite section should include that the supported endpoints need to be onboarded to MDE as well. Currently it only indicates that MDE P2 license is required, which could be misleading for customers as they may assume that they just need to procure the license. onboarding the device to MDE is a crucial step for network logs from clients will be forwarded to MDA cloud discovery
Reference: https://learn.microsoft.com/en-us/defender-cloud-apps/mde-govern#prerequisites

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9385053-041b-10db-888d-432c27c68ffb
* Version Independent ID: 2287bacf-3c7f-6271-aa50-77cc015adb96
* Content: [Govern discovered apps using Microsoft Defender for Endpoint - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/mde-govern)
* Content Source: [CloudAppSecurityDocs/mde-govern.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/mde-govern.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @FasttrackOz, thanks again for your feedback.
The docs are now updated at https://learn.microsoft.com/en-us/defender-cloud-apps/mde-govern#prerequisites

Please take another look and let us know if you have any additional comments, or if we can close this issue. We appreciate your contribution!

**Comment by batamig** [comment]
Hi @FasttrackOz, it's been a few weeks since we fixed this and we haven't heard from you. I'm going to close this issue for now, but feel free to tag me again if you have more feedback. 

Thanks again for your contributions to docs!

**Comment by FasttrackOz** [comment]
Thank you so much and apologies for not responding to you earlier. Yes, this can be closed as resolved. Thanks.

Kind regards,

Shadab Rasheed
FastTrack SME
Microsoft FastTrack Centre
