### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/CloudAppSecurityDocs#694]
Would it be possible to get a copy of this Python script updated with the correct indentation as its challenging to understand the code as a python newb! thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcf430fa-621b-d643-ea58-e1752a57c0bf
* Version Independent ID: 851a9803-18ad-da89-ffb5-7e0702e94d39
* Content: [Manage IP address ranges using the API - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/api-data-enrichment-manage-script)
* Content Source: [CloudAppSecurityDocs/api-data-enrichment-manage-script.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-data-enrichment-manage-script.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @quickclix75, thanks for writing into docs! We've fixed this formatting, can you please check and confirm that this works for you?
We appreciate your contribution - looking forward.

**Comment by batamig** [comment]
Hi @quickclix75, it's been a few weeks since we fixed this and we haven't heard from you. I'm going to close this issue for now, but please feel free tag me again if you have any further feedback on this content.

Thanks again for contributing to docs!
#please-close
