### ISSUE TITLE
Python indentations required

### ISSUE THREAD

**Issue by rfellmann** [MicrosoftDocs/CloudAppSecurityDocs#695]
Please post the python code properly formatted (with indentations) as it will not run otherwise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcf430fa-621b-d643-ea58-e1752a57c0bf
* Version Independent ID: 851a9803-18ad-da89-ffb5-7e0702e94d39
* Content: [Manage IP address ranges using the API - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/api-data-enrichment-manage-script)
* Content Source: [CloudAppSecurityDocs/api-data-enrichment-manage-script.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/api-data-enrichment-manage-script.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by batamig** [comment]
Hi @rfellmann, thanks for writing into docs! We've fixed the indentation now - please see [Response parameters](https://learn.microsoft.com/en-us/defender-cloud-apps/api-data-enrichment-manage-script#response-parameters).

Please confirm that this works for you or send any other feedback you may have. We appreciate your feedback!

**Comment by batamig** [comment]
Hi @rfellmann, it's been a few weeks since we fixed this and we haven't heard from you. I'm going to close this issue for now, but please feel free tag me again if you have any further feedback on this content.

Thanks again for contributing to docs!
#please-close
