### ISSUE TITLE
please add link for co-Auth labeling limitation.

### ISSUE THREAD

**Issue by bellspeal** [MicrosoftDocs/CloudAppSecurityDocs#696]
[Enter feedback here]
please add this link for this explanation.
https://learn.microsoft.com/en-us/purview/sensitivity-labels-coauthoring#if-you-need-to-disable-this-feature
---------------------------------------------------------------
Session controls protect limitation Co-Auth labelling under "protect" action is not supported by Defender for Cloud Apps session controls
---------------------------------------------------------------

at

https://learn.microsoft.com/en-us/defender-cloud-apps/troubleshooting-proxy-end-users#additional-considerations-for-troubleshooting-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4665ec97-3231-51f1-254e-a0e74d17ca1f
* Version Independent ID: 4665ec97-3231-51f1-254e-a0e74d17ca1f
* Content: [Troubleshooting access and session controls for end-users - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/troubleshooting-proxy-end-users)
* Content Source: [CloudAppSecurityDocs/troubleshooting-proxy-end-users.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/troubleshooting-proxy-end-users.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @bellspeal, thanks for writing into docs! I'm adding the link now, so I'm going to close this issue.
Please feel free to continue commenting here and tag me if you have more feedback.
#please-close
