### ISSUE TITLE
Imported groups

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/CloudAppSecurityDocs#71]
Once a group is synced for an app. What is the sync intervals afterwards? How often are group in CAS updated for changes made to the group in AAD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb8d5c18-3f84-f47a-7320-930cbd4ae5a0
* Version Independent ID: aa593032-c7c0-5814-5b18-d360295a260e
* Content: [Import user groups from connected apps](https://docs.microsoft.com/en-us/cloud-app-security/user-groups)
* Content Source: [CloudAppSecurityDocs/user-groups.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/user-groups.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @xNiklasJern , thanks for reaching out. After the initial sync it's updated every hour. I'll add it to the documentation. thanks!

**Comment by rkarlin** [comment]
#please-close
