### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/CloudAppSecurityDocs#72]
I was wondering about the prerequisites of having build 1809 of Windows 10 to integrate MCAS with WDATP.
Is this correct? I believe I have seen this feature being advertised long before 1809 was ever in the making, also it feels a bit odd that this feature is possible until you use a version of windows 10 that hasn't even reached CBB yet.

If it is correct, what is that make need for 1809 for the integration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b2133d-85b3-8e2c-c89a-7d83f48e5dd0
* Version Independent ID: 84598ed0-a8ea-5504-2b87-b20df2347e53
* Content: [Integrate Windows Defender Advanced Threat Protection with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/wdatp-integration)
* Content Source: [CloudAppSecurityDocs/wdatp-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/wdatp-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @xNiklasJern thanks so much for reaching out to us. This build was in preview for a while, so it's possible that it wasn't highlighted well enough. The process that relays network traffic signals from Windows to Cloud App Security was added only starting from this build.
Hope that helps, 
thanks,
Rachel

**Comment by rkarlin** [comment]
#please-close @msmbaldwin
