### ISSUE TITLE
Redundunt expression

### ISSUE THREAD

**Issue by Yasin0ps** [MicrosoftDocs/CloudAppSecurityDocs#728]
May need to remove one of these phrases "Unless otherwise specified" or "unless otherwise noted" in the same sentence. 

Unless otherwise specified, new feature releases, including preview features, documented in [What's new with Microsoft Defender for Cloud Apps], will be available in GCC High and DoD environments within three months of release in the Microsoft Defender for Cloud Apps commercial environment, unless otherwise noted.

**Comment by batamig** [comment]
Thanks for this feedback @Yasin0ps! I've just updated this content and it should be live later today.
I'm going to close this issue for now, but feel free to continue commenting if you have additional feedback. 
We appreciate your contribution!
