### ISSUE TITLE
Question about link in article

### ISSUE THREAD

**Issue by cawiesla** [MicrosoftDocs/CloudAppSecurityDocs#73]
In the bottom of this article, you have a link "Premier customers can also choose Cloud App Security directly from the Premier Portal". What choise do you mean can be done for Cloud App Security in Premier Portal? When clicking on the link, you end up at your start page in the portal. No specific information about CAS. I have got this Question from a Customer, please review it and clarify. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a419aaf2-b6b9-902a-e186-c5718b9ffd1f
* Version Independent ID: 2a9c599e-306e-490e-2e6d-7642fa71d63c
* Content: [Create snapshot reports of Cloud Discovery cloud app use](https://docs.microsoft.com/en-us/cloud-app-security/create-snapshot-cloud-discovery-reports#log-format)
* Content Source: [CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @cawiesla , thanks for reaching out, we appreciate your feedback. You're right - it seems you no longer have to choose a product, you can simply click +New service request to open an issue. I'll update the articles, thanks for letting me know and for contributing to Cloud App Security documentation!

**Comment by cawiesla** [comment]
Thanks! Please also clarify that the link is to be used for creating a incident request.
As of now, is is placed under headline ”next step” and that is confusing as well.

/Catrine

Hämta Outlook för iOS<https://aka.ms/o0ukef>

________________________________
Från: rkarlin <notifications@github.com>
Skickat: söndag, december 9, 2018 12:48 em
Till: MicrosoftDocs/CloudAppSecurityDocs
Kopia: Catrine Wieslander; Mention
Ämne: Re: [MicrosoftDocs/CloudAppSecurityDocs] Question about link in article (#73)


Hi @cawiesla<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcawiesla&data=02%7C01%7CCatrine.Wieslander%40microsoft.com%7C3fe6ef8cbf2b474532bc08d65dcc4539%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636799529248374514&sdata=%2FG5lUTOaKZZPI8LO8hozVGRNPgiBJEt%2FsG9ZnKCdwlA%3D&reserved=0> , thanks for reaching out, we appreciate your feedback. You're right - it seems you no longer have to choose a product, you can simply click +New service request to open an issue. I'll update the articles, thanks for letting me know and for contributing to Cloud App Security documentation!

**Comment by rkarlin** [comment]
@msmbaldwin #please-close
