### ISSUE TITLE
Vancouver version of SN not supported to connect to MDCA?

### ISSUE THREAD

**Issue by ramonabadea** [MicrosoftDocs/CloudAppSecurityDocs#730]
Hi all,

Is Vancouver version of SN not supported to connect to MDCA?

Thanks in advance for the feedback,
Ramona

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 654252bf-01a2-07bc-f326-20bba7ed64ac
* Version Independent ID: ea7b1901-5954-c609-e08e-9d1ce28bd16b
* Content: [Protect your ServiceNow environment - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/protect-servicenow)
* Content Source: [CloudAppSecurityDocs/protect-servicenow.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/protect-servicenow.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @ramonabadea, thanks for writing into docs! I'm tagging an SME to understand more, and we'll update the docs as needed. 
@LeorHurwitz, can you comment on the Vancouver version support?

**Comment by batamig** [comment]
thanks @LeorHurwitz! @ramonabadea, this page is now updated to show Vancouver. I'm going to close this issue for now, but feel free to continue commenting and tag me if you have any further feedback. 

We appreciate your contribution to docs!
#please-close
