### ISSUE TITLE
Call out Windows 11 specifically in the pre-reqs section

### ISSUE THREAD

**Issue by EllaBeans** [MicrosoftDocs/CloudAppSecurityDocs#731]
It may be helpful to call out Windows 11 specifically in the pre-reqs section of this document. 
Something like: Windows: "Windows 10 version 18.09 (RS5), OS Build 1776.3 or later, Windows 11."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9385053-041b-10db-888d-432c27c68ffb
* Version Independent ID: 2287bacf-3c7f-6271-aa50-77cc015adb96
* Content: [Govern discovered apps using Microsoft Defender for Endpoint - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/mde-govern#prerequisites-for-blocking-apps-with-defender-for-endpoint)
* Content Source: [CloudAppSecurityDocs/mde-govern.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/mde-govern.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @EllaBeans, I'm writing to tell you that we specified Windows 11 on this page as requested. I'm going to close this issue for now, but please feel free to tag me if you have additional feedback. 
Thanks for your contribution to docs!
#please-close
