### ISSUE TITLE
 Add "Microsoft Teams" for context loss know limitation

### ISSUE THREAD

**Issue by bellspeal** [MicrosoftDocs/CloudAppSecurityDocs#732]
[Enter feedback here]
Please Add "Microsoft Teams" for this lists.

---------------------------
Context loss
In the following applications, we've encountered scenarios where navigating to a link may result in loss of the full path of the link and typically the user lands on the home page of the app.

ArcGIS
GitHub
Microsoft Power Automate
Microsoft Power Apps
Workplace from Meta
ServiceNow
---------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect apps with Conditional Access App Control - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/proxy-intro-aad#known-limitations)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for your feedback! We're investigating and will get back to you.

**Comment by batamig** [comment]
Hi @bellspeal, I'm writing to let you know that we've updated the docs as requested and you can see this here:
https://learn.microsoft.com/en-us/defender-cloud-apps/proxy-intro-aad#known-limitations

I'm closing this issue for now, but please feel free to tag me if you have additional feedback. Thanks for your contribution to docs!
#please-close
