### ISSUE TITLE
Microsoft Purview E5/A5/F5?

### ISSUE THREAD

**Issue by getazcloud** [MicrosoftDocs/CloudAppSecurityDocs#733]
Hello,
Just to verify, as I cannot find detailed information about: Microsoft Purview E5/A5/F5
Is the license Microsoft Purview E5/A5/F5 correct? Or should it be Microsoft Compliance E5/A5/F5 ?
Thanks for verification.
Lukas

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1fa045c-9edd-2d50-8c55-25b5be8ec9c8
* Version Independent ID: d1fa045c-9edd-2d50-8c55-25b5be8ec9c8
* Content: [Turn on app governance in Microsoft Defender for Cloud Apps - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/app-governance-get-started#licensing)
* Content Source: [CloudAppSecurityDocs/app-governance-get-started.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/app-governance-get-started.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @getazcloud, thanks for your question! We'll investigate this and get back to you.

**Comment by batamig** [comment]
Hi @getazcloud, we're planning to update this text to remove specific license names. App governance is available to any organization with a valid Defender for Cloud Apps license. 
You can find more details about specific licenses on the [Microsoft 365 licensing datasheet](https://aka.ms/M365EnterprisePlans).

If you have additional questions about App governance or Defender for Cloud Apps licensing, we suggest you contact your admin or sales representative. 

I'm going to close this issue for now, but feel free to continue commenting if you have more feedback for docs.

#please-close
