### ISSUE TITLE
There is no unified experience for end users when it comes to 'Setup Microsoft Defender for Cloud Apps'

### ISSUE THREAD

**Issue by Shweta-1405** [MicrosoftDocs/CloudAppSecurityDocs#738]
The documentation gets slightly confusing for our users when it comes to - 'Setup guide for Microsoft defender for cloud Apps' where this information is put in mutilple places in our documentation without proper mention of differences between multiple descriptions and user persona they are trying to cater to.

Multiple links for setup guide - 
1. https://learn.microsoft.com/en-us/defender-cloud-apps/get-started#step-1-set-instant-visibility-protection-and-governance-actions-for-your-apps
2. https://learn.microsoft.com/en-us/defender-cloud-apps/general-setup
3. Detailled explanation mentioned here - https://setup.cloud.microsoft/defender/cloud-apps-setup-guide?redirect=true . Can this be hyperlinked in learn site mentioning the persona this can cater to(for e.g. fasttrack engg. or something along with usecase.)

The idea here is to have unfied eperience i.e. when user searches for setup guide, they get to see all the links clearly telling them what to expect in each case.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3a8799-0915-2446-b772-cf5e3c80a238
* Version Independent ID: 31f10a22-3c95-5ebe-622d-7431c5cb76f1
* Content: [Get started - Microsoft Defender for Cloud Apps](https://learn.microsoft.com/en-us/defender-cloud-apps/get-started)
* Content Source: [CloudAppSecurityDocs/get-started.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/main/CloudAppSecurityDocs/get-started.md)
* Service: **defender-for-cloud-apps**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
thanks! since we're handling this internally already, I'm closing these. #please-close
