### ISSUE TITLE
Importing the collector config doesn't work

### ISSUE THREAD

**Issue by woodwarw** [MicrosoftDocs/CloudAppSecurityDocs#76]
when I try to run the final docker command I get the following:

pull access denied for microsoft/caslogcollector, repository does not exist or may require 'docker login'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @woodwarw 
Thanks for contacting us. Please contact support to get help with this.
thanks,
Rachel

**Comment by rkarlin** [comment]
#please-close @msmbaldwin

**Comment by richie1080** [comment]
If you crack open the LogCollectorInstaller.ps1 script that you've downloaded in PowerShell ISE you can see the docker username and password.

In the version of the script I have its on line 76:
docker login -u caslogcollector -p C0llector3nthusiast

Then do the pull request and it should work:
docker pull microsoft/caslogcollector

And finally save and run the command from when you set up the log collector in the CAS portal:
$dockerRunCommand = Read-Host 'Enter the run command:'
Invoke-Expression $dockerRunCommand
