### ISSUE TITLE
I cant see these settings

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/CloudAppSecurityDocs#79]
despite of me having an admin id.. I am not able to see the settings section as shown in snapshot.. why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1767-daa6-b26a-b151-01f284ddd4c1
* Version Independent ID: 1abac014-c7e2-91cb-8754-e70601cc4102
* Content: [Set email notification preferences - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/mail-settings)
* Content Source: [CloudAppSecurityDocs/mail-settings.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/mail-settings.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @mganeshphani , thanks so much for reaching out. I've added you to an email thread with someone from the product group so you can ask your questions there. Thanks!

**Comment by rkarlin** [comment]
#please-close @msmbaldwin

**Comment by crshovrd41** [comment]
I also do not see these settings. Please help.

**Comment by rkarlin** [comment]
Hi @crshovrd41 
thanks for contacting us. Please contact support. thanks,
Rachel
