### ISSUE TITLE
I cant see this setting

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/CloudAppSecurityDocs#80]
Despite of me having an admin id.. I still cant see these settings.. why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da9a9fad-ff34-4689-c30e-404a774f9bd3
* Version Independent ID: 351b6aa7-da8e-350d-c002-6e0689b350cc
* Content: [Connect Azure to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-azure-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-azure-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-azure-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @mganeshphani 
Thanks so much for reaching out to us about this. I don't think it's a documentation issue so I have sent you an email and included someone from the product team who might be able to solve your problem.
thanks again,
Rachel

**Comment by rkarlin** [comment]
@msmbaldwin #please-close
