### ISSUE TITLE
Data Management Reports removed

### ISSUE THREAD

**Issue by antraett** [MicrosoftDocs/CloudAppSecurityDocs#81]
Hi, please can you confirm where the 3 dots that were available for data management reports have been moved to? The reports are no longer available when I access my demo tenant and they were previously. Thank you. Antonio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba61c236-e64a-2835-8fbd-4ff975e78d27
* Version Independent ID: d4394353-4330-05a2-c30b-b2b4bd7b7c2f
* Content: [Generate reports - Microsoft Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/built-in-reports)
* Content Source: [CloudAppSecurityDocs/built-in-reports.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/built-in-reports.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@antraett Thanks for reaching out to us. Let me know if this answers all the questions you have: https://docs.microsoft.com/cloud-app-security/built-in-report-redirect

**Comment by rkarlin** [comment]
#please-close
@msmbaldwin

**Comment by antraett** [comment]
Hi @rkarlin, all good thank you. My demo Tenant was also throttled for these reports.

**Comment by rkarlin** [comment]
@antraett glad to hear it :) let me know if you have any further questions.
