### ISSUE TITLE
Syslog-TLS?

### ISSUE THREAD

**Issue by richie1080** [MicrosoftDocs/CloudAppSecurityDocs#82]
Hi,
Is there a way to update certificates in the same way as you can on an Ubuntu Docker machine like documented here?
https://docs.microsoft.com/en-us/cloud-app-security/troubleshoot-docker
Rich

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by richie1080** [comment]
*Tumbleweed*

**Comment by rkarlin** [comment]
Hi @richie1080 , sorry it's taking me a while to respond, I'm trying to gather information for you. I haven't forgotten. thanks a lot for reaching out.

**Comment by richie1080** [comment]
Hi rkarlin... I think I've cracked this by following the instructions in the troubleshooting section properly :)

FTPing to inside the docker container and the correct folder structure is there - just as described in the above article.

Rich

**Comment by rkarlin** [comment]
:) I'm glad something I wrote worked. Is there something in that article that you think belongs here?
thanks so much for your feedback!

**Comment by richie1080** [comment]
Most clients I work with are interested in TLS encryption between whatever appliance they have and the CAS log collector - I think its worth making this configuration easier to find - It's a pain it being under the troubleshooting section :)

**Comment by rkarlin** [comment]
Thanks, I'll add a link to it under the deployment instructions. thanks again for your feedback!

**Comment by rkarlin** [comment]
#please-close
