### ISSUE TITLE
Connect Office 365 only or also with SPO and EXO

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/CloudAppSecurityDocs#83]
If you connect Office 365 as one app, should you also connect Exchange Online and SharePoint Online apps separately?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c7ec0b-8a9e-1aec-f8a6-97864b401aef
* Version Independent ID: dc977df5-36a8-0371-c7fa-8f745df452ba
* Content: [Connect Office 365 to Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/connect-office-365-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-office-365-to-microsoft-cloud-app-security.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/connect-office-365-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@Kazzan  Hi Petr, thanks so much for your question. Office 365 connects the whole suite automatically, there is no need to separately connect Exchange / SPO.

**Comment by rkarlin** [comment]
@msmbaldwin #please-close
