### ISSUE TITLE
DNS names missing/incorrect

### ISSUE THREAD

**Issue by mschultz-bcbsne** [MicrosoftDocs/CloudAppSecurityDocs#84]
We recently had the relevant DNS names allowed through our perimeter network security devices, but found that some MCAS proxy services are redirecting through names not listed.  For example, we're seeing lots of redirects through *.us2.cas.ms, but there is no mention of any *.cas.ms DNS names on this page.  Can you update the list as appropriate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96223442-ff3d-c101-214f-2240ac42d53b
* Version Independent ID: 56fead2d-d0ba-ce69-e931-5b91ed43c736
* Content: [Network requirements - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/network-requirements)
* Content Source: [CloudAppSecurityDocs/network-requirements.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/network-requirements.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @mschultz-bcbsne thanks so much for your feedback. I'm sorry it's taking so long to get an answer about this, but I'll update you as soon as I get confirmation and update the page.

**Comment by rkarlin** [comment]
Hi @mschultz-bcbsne The list focuses on the items you need to configure on your firewall to enable connection from Cloud App Security. In the case of this proxy, this is an outgoing connection which usually doesn't require any specific configuration. hope that helps, thanks, Rachel

**Comment by rkarlin** [comment]
#please-close

**Comment by rkarlin** [comment]
@msmbaldwin

**Comment by mschultz-bcbsne** [comment]
Then I guess I need to change my comment.  The intro to the article doesn't specifically say it's for allowing inbound connections: 

> This article provides a list of ports and IP addresses you need to allow and white list to work with Microsoft Cloud App Security.

And the [Portal Access section](https://github.com/MicrosoftDocs/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/network-requirements.md#portal-access) is even specifically about outbound connections.  I understand it focuses on connections to the portal, not applications protected by the MCAS proxy feature, so perhaps that verbiage needs to be updated, or an additional section needs to be added.

I understand the proxy is an outbound connection that _**usually**_ doesn't require any specific configuration, but for many enterprises (mine included) that's not the case.  We did need to make certain configuration changes to HTTPS inspection and other outbound security measures, and it was specifically the *.cas.ms addresses not listed in this article that were the problem.  It is extremely helpful to have the full list of URLs the service may use so that customers don't have to go back and forth with other internal teams.  Lots of "oh, now it looks like it needs these addresses" over the course of tickets and other red tape makes implementation very frustrating.

Please reconsider adding the information before closing this issue.
