### ISSUE TITLE
Where is the "Cloud App Security Portal"?

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/CloudAppSecurityDocs#87]
Please provide a URL for the Cloud App Security portal which is referenced in this document. I have no idea where it is and efforts to Google for it where challenging. I finally found this:
https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-cas-overview

which points me to:  https://protection.office.com

Why not hyperlink the term to the above URL (or at least parenthetically give the URL).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a419aaf2-b6b9-902a-e186-c5718b9ffd1f
* Version Independent ID: 2a9c599e-306e-490e-2e6d-7642fa71d63c
* Content: [Create snapshot reports of Cloud Discovery cloud app use](https://docs.microsoft.com/en-us/cloud-app-security/create-snapshot-cloud-discovery-reports)
* Content Source: [CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/create-snapshot-cloud-discovery-reports.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by lesterw1** [comment]
Actually, there is no "Discover" option in https://protection.microsoft.com/ so that must not be the "Cloud App Security portal" referenced above. If this isn't it, then WHERE IS IT?

**Comment by lesterw1** [comment]
I finally found it!  :)   https://portal.cloudappsecurity.com/

**Comment by rkarlin** [comment]
Hi @lesterw1 thanks for reaching out. I'm not sure what you were trying to do and which product you were trying to use - are you looking for cloud app security as part of Office or the standalone version of Cloud App Security? We have the URL for the standalone version in the getting started page: https://docs.microsoft.com/cloud-app-security/getting-started-with-cloud-app-security

**Comment by lesterw1** [comment]
Yes, I was looking for the stand-alone portal as described on the “getting started” page link which you provided. My frustration is that there was no link to this page or the portal itself on the page: https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-cas-overview. And Searching results in too many hits trying to find the page. So my recommendation is to amend the page and include a link to the page below as well as a link to the portal (for convenience).

**Comment by rkarlin** [comment]
Hi @lesterw1 
I will pass on that feedback to the writers for that page.
thanks,
Rachel

**Comment by rkarlin** [comment]
Hi @lesterw1 I just wanted to let you know that the page was updated with the link per your request. Thanks a lot for your feedback, let me know if there's any further assistance we can provide.

**Comment by rkarlin** [comment]
#please-close 
@msmbaldwin
