### ISSUE TITLE
Table suggestion

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/CloudAppSecurityDocs#94]
In the table above using N/A or footnotes below the table would make it easier to read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cb69cd-d5d4-e058-e20f-d2697cfcd614
* Version Independent ID: bb8fbd63-532a-f8f9-6bc6-85eaf09ca171
* Content: [Connect apps to get visibility and control - Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/enable-instant-visibility-protection-and-governance-actions-for-your-apps)
* Content Source: [CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/enable-instant-visibility-protection-and-governance-actions-for-your-apps.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
#Please-close
