### ISSUE TITLE
Confusion about: "Before the installation completes, you will have to paste in the run command you copied earlier." statement

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/CloudAppSecurityDocs#95]
This statement is not clear to me: “Before the installation completes, you will have to paste in the run command you copied earlier.” I am not sure which run command is meant here. Is it command to restart LogCollectorInstaller.ps1 script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@pawp81 Hi, Thanks for reaching out to us. This refers to the command you copied in step 1.4. thanks.

**Comment by rkarlin** [comment]
#please-close @msmbaldwin
