### ISSUE TITLE
On-premises deployment of your machine, step 7

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/CloudAppSecurityDocs#96]
I guess command to import log collector configuration should be run in elevated command prompt? It would be good to include this information in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ladybonner** [comment]
I am not going to go through all of these emails.
What are you all for then?? I was told to sit right here and wait for
everything!! I have been waiting for several years too!! I still want my
cornbread from Mrs. Kay.. Cornbread with cheese and bacon..the entire pan
is mine!! And one of her son's or daughter in law's must give it to me..I
don't know what Tawanna is supposed to be doing??  Why does her name keep
coming up in my information?? I don't actually know her that well..

Mrs. Heather Rocio Gonzalez Bonner

**Comment by rkarlin** [comment]
Hi @pawp81 , thanks for your comment. In step 2, number 1, we say: Open a PowerShell terminal **as an administrator** on your Windows machine.
Is there some other information you thought you needed? 
thanks

**Comment by rkarlin** [comment]
#please-close
