### ISSUE TITLE
Docker ID required?

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/CloudAppSecurityDocs#97]
Is it required to have Docker ID to deploy log collector? If yes it would be good to include it in documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7c304-9777-e8d6-1e49-e80ea333c072
* Version Independent ID: c659f6d0-9011-fd40-d33e-090a719e82da
* Content: [Roll out continuous reports for Cloud App Security using a Docker on Windows](https://docs.microsoft.com/en-us/cloud-app-security/discovery-docker-windows)
* Content Source: [CloudAppSecurityDocs/discovery-docker-windows.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/discovery-docker-windows.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @pawp81 thanks so much for contacting us. It is not necessary to have a Docker ID.
thanks.

**Comment by rkarlin** [comment]
#please-close
@msmbaldwin
