### ISSUE TITLE
Definition of "sensitive documents"?

### ISSUE THREAD

**Issue by BrianTJackett** [MicrosoftDocs/CloudAppSecurityDocs#98]
Under "How It Works" -&gt; "Block on download" it is mentioned that this functionality can block download of sensitive documents.  What are considered sensitive documents?  Is that all documents, only documents identified by Security and Compliance Center / Cloud App Security, or something else?  Appreciate any clarity you can provide.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87824868-8913-dac8-b8c0-365ccf8110c4
* Version Independent ID: ce8dd4b6-0562-8f42-e30f-e5cb58a68b90
* Content: [Protect with Microsoft Cloud App Security Conditional Access App Control](https://docs.microsoft.com/en-gb/cloud-app-security/proxy-intro-aad#supported-apps-and-clients)
* Content Source: [CloudAppSecurityDocs/proxy-intro-aad.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/proxy-intro-aad.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
Hi @BrianTJackett , thanks for reaching out! The idea is that sensitive can be any files you deem to be sensitive. It could be files labeled in Azure Information Protection or files with specific regex matches, anything you want to set to be blocked on download. Does that help?

**Comment by rkarlin** [comment]
#please-close @msmbaldwin

**Comment by BrianTJackett** [comment]
That helps, thanks.
