### ISSUE TITLE
Can't find the MCAS toggle in Windows Defender ATP

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/CloudAppSecurityDocs#99]
I don't have such toggle within my WDATP console, I can see Intune, O365, but no sign of MCAS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b2133d-85b3-8e2c-c89a-7d83f48e5dd0
* Version Independent ID: 84598ed0-a8ea-5504-2b87-b20df2347e53
* Content: [Integrate Windows Defender ATP with Cloud App Security](https://docs.microsoft.com/en-us/cloud-app-security/wdatp-integration)
* Content Source: [CloudAppSecurityDocs/wdatp-integration.md](https://github.com/Microsoft/CloudAppSecurityDocs/blob/master/CloudAppSecurityDocs/wdatp-integration.md)
* Service: **cloud-app-security**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by JTRealms** [comment]
Its not mentioned in the article, but you need to toggle "Preview Features".

**Comment by rkarlin** [comment]
Thanks @JTRealms , I'll update it in the next release.

**Comment by rkarlin** [comment]
#please-close
